import type{CardTriggerInput,CardTriggerScript}from'../trigger-runtime.ts';
import type{RuntimeEffect,RuntimeWarning}from'../worker/contract.ts';
export type EffectDisposition='apply'|'block'|'approval';
const BLOCK=new Set(['triggercode','triggerlua','command','sendAIprompt','runLLM','runAxLLM','runImgGen','checkSimilarity','v2Command','v2SendAIprompt','v2RunLLM','v2ImgGen','v2CheckSimilarity','v2ConsoleLog']);
const APPROVAL=new Set(['cutchat','modifychat','systemprompt','impersonate','showAlert','v2CutChat','v2ModifyChat','v2SystemPrompt','v2Impersonate','v2ShowAlert','v2GetAlertInput','v2GetAlertSelect','v2ModifyLorebook','v2SetLorebookActivation','v2SetCharacterDesc','v2SetPersonaDesc','v2SetReplaceGlobalNote','v2UpdateGUI','v2UpdateChatAt','v2CreateLorebook','v2ModifyLorebookByIndex','v2DeleteLorebookByIndex','v2SetLorebookAlwaysActive','v2SetAuthorNote']);
export const KNOWN_TRIGGER_EFFECTS=['setvar','cutchat','modifychat','systemprompt','impersonate','command','extractRegex','showAlert','runtrigger','stop','sendAIprompt','runImgGen','checkSimilarity','runLLM','runAxLLM','triggercode','triggerlua','v2Header','v2SetVar','v2DeclareLocalVar','v2If','v2IfAdvanced','v2Else','v2EndIndent','v2Loop','v2LoopNTimes','v2BreakLoop','v2RunTrigger','v2ConsoleLog','v2StopTrigger','v2CutChat','v2ModifyChat','v2SystemPrompt','v2Impersonate','v2Command','v2SendAIprompt','v2ImgGen','v2CheckSimilarity','v2RunLLM','v2ShowAlert','v2ExtractRegex','v2GetLastMessage','v2GetMessageAtIndex','v2GetMessageCount','v2ModifyLorebook','v2GetLorebook','v2GetLorebookCount','v2GetLorebookEntry','v2SetLorebookActivation','v2GetLorebookIndexViaName','v2Random','v2GetCharAt','v2GetCharCount','v2ToLowerCase','v2ToUpperCase','v2SetCharAt','v2SplitString','v2JoinArrayVar','v2GetCharacterDesc','v2SetCharacterDesc','v2GetPersonaDesc','v2SetPersonaDesc','v2GetReplaceGlobalNote','v2SetReplaceGlobalNote','v2MakeArrayVar','v2GetArrayVarLength','v2GetArrayVar','v2SetArrayVar','v2PushArrayVar','v2PopArrayVar','v2ShiftArrayVar','v2UnshiftArrayVar','v2SpliceArrayVar','v2SliceArrayVar','v2GetIndexOfValueInArrayVar','v2RemoveIndexFromArrayVar','v2ConcatString','v2GetLastUserMessage','v2GetLastCharMessage','v2GetFirstMessage','v2GetAlertInput','v2GetAlertSelect','v2GetDisplayState','v2SetDisplayState','v2UpdateGUI','v2UpdateChatAt','v2Wait','v2GetRequestState','v2SetRequestState','v2GetRequestStateRole','v2SetRequestStateRole','v2GetRequestStateLength','v2QuickSearchChat','v2Tokenize','v2GetAllLorebooks','v2GetLorebookByName','v2GetLorebookByIndex','v2CreateLorebook','v2ModifyLorebookByIndex','v2DeleteLorebookByIndex','v2GetLorebookCountNew','v2SetLorebookAlwaysActive','v2RegexTest','v2GetAuthorNote','v2SetAuthorNote','v2MakeDictVar','v2GetDictVar','v2SetDictVar','v2DeleteDictKey','v2HasDictKey','v2ClearDict','v2GetDictSize','v2GetDictKeys','v2GetDictValues','v2Calculate','v2ReplaceString','v2Comment','v2StopPromptSending']as const;
const KNOWN=new Set<string>(KNOWN_TRIGGER_EFFECTS);
export function effectDisposition(type:string):EffectDisposition{if(BLOCK.has(type)||!KNOWN.has(type))return'block';if(APPROVAL.has(type))return'approval';return'apply';}
export function prepareRuntimeEffects(input:Omit<CardTriggerInput,'variables'|'alert'>){const effects:RuntimeEffect[]=[],warnings:RuntimeWarning[]=[];const sanitize=(script:CardTriggerScript):CardTriggerScript=>({...script,effect:(script.effect??[]).map(raw=>{const value=raw&&typeof raw==='object'?raw as Record<string,unknown>:{},type=String(value.type??''),disposition=effectDisposition(type);if(disposition==='apply')return raw;const reason=KNOWN.has(type)?`runtime_effect_${disposition}`:'runtime_effect_unknown';effects.push({type,disposition,payload:{reason}});warnings.push({code:disposition==='approval'?'runtime_effect_approval':'runtime_effect_blocked',message:`${type||'(empty)'}:${reason}`,effect:type});return{...value,type:'__luckyBlocked'};})});return{input:{...input,triggers:(input.triggers??[]).map(sanitize),moduleTriggers:(input.moduleTriggers??[]).map(sanitize)},effects,warnings};}
