import type { ModelProvider,ModelRequest } from '../index.ts';
import {createCopilotProvider,createOpenAICompatibleProvider,listCopilotModels,listModels,maskSecrets,type OpenAICompatibleOptions} from './openai.ts';
import {createAnthropicProvider,listAnthropicModels} from './anthropic.ts';import {createGoogleProvider,listGoogleModels} from './google.ts';import {createVertexProvider} from './vertex.ts';
import {createOllamaCloudProvider} from './ollama.ts';
export type ProviderId='openai'|'anthropic'|'google'|'vertex'|'copilot'|'openrouter'|'deepseek'|'vercel'|'nanogpt'|'cerebras'|'ollama-cloud'|'ollama'|'custom';
export interface ProviderConfig{provider:ProviderId;model:string;apiKey:string;endpoint?:string;location?:string;temperature?:number;maxTokens?:number;topP?:number;topK?:number;frequencyPenalty?:number;presencePenalty?:number;minP?:number;topA?:number;repetitionPenalty?:number;seed?:number;maxContext?:number;}
interface Preset{endpoint:string;modelsEndpoint?:string;headers?:Record<string,string>}
export const OPENAI_PRESETS:Partial<Record<ProviderId,Preset>>={
  openai:{endpoint:'https://api.openai.com/v1/chat/completions'},
  openrouter:{endpoint:'https://openrouter.ai/api/v1/chat/completions',modelsEndpoint:'https://openrouter.ai/api/v1/models',headers:{'X-Title':'Lucky Simulator'}},
  deepseek:{endpoint:'https://api.deepseek.com/v1/chat/completions',modelsEndpoint:'https://api.deepseek.com/models'},
  vercel:{endpoint:'https://ai-gateway.vercel.sh/v1/chat/completions',modelsEndpoint:'https://ai-gateway.vercel.sh/v1/models'},
  nanogpt:{endpoint:'https://nano-gpt.com/api/v1/chat/completions',modelsEndpoint:'https://nano-gpt.com/api/v1/models'},
  cerebras:{endpoint:'https://api.cerebras.ai/v1/chat/completions'},
  // Ollama — CPM v1.35.11 참조 이식(지식만, 코드·프록시 URL 미복사): OpenAI 호환 /v1/chat/completions 기본,
  // 모델 목록은 /v1/models 실패 시 네이티브 /api/tags 폴백. Base URL은 설정에서 교체(로컬 기본).
  ollama:{endpoint:'http://localhost:11434/v1/chat/completions',modelsEndpoint:'http://localhost:11434/v1/models'}
};
// 사용자가 넣은 Base URL(예: http://192.168.0.5:11434, https://ollama.com)을 채팅 엔드포인트로 정규화한다.
export function isOllamaCloud(base:string){try{return new URL(base.trim()).hostname.toLowerCase()==='ollama.com';}catch{return false;}}
export function isOllamaCloudConfig(config:ProviderConfig){return config.provider==='ollama-cloud'||(config.provider==='ollama'&&isOllamaCloud(config.endpoint??''));}
export function ollamaEndpoint(base:string){const trimmed=base.trim().replace(/[/]+$/,'');if(!trimmed)return OPENAI_PRESETS.ollama!.endpoint;if(isOllamaCloud(trimmed))return 'https://ollama.com/api/chat';return /[/](?:v1[/]chat[/]completions|api[/]chat)$/.test(trimmed)?trimmed:`${trimmed}/v1/chat/completions`;}
export function ollamaCloudProxyPath(route:'chat'|'tags',hostname=globalThis.location?.hostname??''){return /(?:^|\.)(?:web\.app|firebaseapp\.com)$/.test(hostname)?`/api/ollama/${route}`:'';}
export function ollamaBase(config:ProviderConfig){return ollamaEndpoint(config.endpoint??'').replace(/[/](?:v1[/]chat[/]completions|api[/]chat)$/,'');}
const CATALOG:Record<ProviderId,string[]>={'ollama-cloud':['glm-5.2','deepseek-v4-pro','deepseek-v4-flash','kimi-k2.7-code','nemotron-3-ultra','minimax-m3','qwen3.5:397b','gpt-oss:120b','gpt-oss:20b'],ollama:['llama3.3','qwen3','gemma3','mistral-small'],openai:['gpt-5.6','gpt-5.6-mini','gpt-5.2','gpt-4.1','gpt-4.1-mini'],anthropic:['claude-opus-4-8','claude-sonnet-5','claude-opus-4-6','claude-haiku-4-5-20251001'],google:['gemini-3.5-flash','gemini-3.1-pro-preview','gemini-3.1-flash-lite','gemini-2.5-pro','gemini-2.5-flash','gemini-2.5-flash-lite'],vertex:['gemini-3.1-pro-preview','gemini-3.1-flash-lite','gemini-2.5-pro','gemini-2.5-flash','gemini-2.5-flash-lite'],copilot:['gpt-4.1'],openrouter:[],deepseek:[],vercel:[],nanogpt:[],cerebras:['gemma-4-31b'],custom:[]};
export function catalogFor(provider:ProviderId){return CATALOG[provider].map(id=>({id,label:id}));}
function openAIOptions(config:ProviderConfig,key:string,fetchImpl?:typeof fetch):OpenAICompatibleOptions{const preset=OPENAI_PRESETS[config.provider],endpoint=config.provider==='custom'?config.endpoint:config.provider==='ollama'?ollamaEndpoint(config.endpoint??''):preset?.endpoint;if(!endpoint)throw new Error('custom_endpoint_required');return{endpoint,apiKey:key,model:config.model,...(config.provider==='ollama'?{modelsEndpoint:`${ollamaBase(config)}/v1/models`}:preset?.modelsEndpoint?{modelsEndpoint:preset.modelsEndpoint}:{}),...(preset?.headers?{headers:preset.headers}:{}),...(config.temperature===undefined?{}:{temperature:config.temperature}),...(config.maxTokens===undefined?{}:{maxTokens:config.maxTokens}),...(config.topP===undefined?{}:{topP:config.topP}),...(config.frequencyPenalty===undefined?{}:{frequencyPenalty:config.frequencyPenalty}),...(config.presencePenalty===undefined?{}:{presencePenalty:config.presencePenalty}),...(config.seed===undefined?{}:{seed:config.seed}),...(fetchImpl?{fetch:fetchImpl}:{})};}
function one(config:ProviderConfig,key:string,fetchImpl?:typeof fetch):ModelProvider{const common={apiKey:key,model:config.model,...(config.temperature===undefined?{}:{temperature:config.temperature}),...(config.maxTokens===undefined?{}:{maxTokens:config.maxTokens}),...(config.topP===undefined?{}:{topP:config.topP}),...(config.topK===undefined?{}:{topK:config.topK}),...(config.frequencyPenalty===undefined?{}:{frequencyPenalty:config.frequencyPenalty}),...(config.presencePenalty===undefined?{}:{presencePenalty:config.presencePenalty}),...(config.seed===undefined?{}:{seed:config.seed}),...(fetchImpl?{fetch:fetchImpl}:{})};if(config.provider==='anthropic')return createAnthropicProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='google')return createGoogleProvider({...common,...(config.endpoint?{endpoint:config.endpoint}:{})});if(config.provider==='vertex')return createVertexProvider({...common,...(config.location?{location:config.location}:{})});if(config.provider==='copilot')return createCopilotProvider(common);if(isOllamaCloudConfig(config))return createOllamaCloudProvider({...common,endpoint:ollamaCloudProxyPath('chat')||'https://ollama.com/api/chat'});return createOpenAICompatibleProvider(openAIOptions(config,key,fetchImpl));}
export function createProvider(config:ProviderConfig,fetchImpl?:typeof fetch):ModelProvider{const keys=config.provider==='vertex'?[config.apiKey.trim()].filter(Boolean):config.apiKey.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!keys.length){if(config.provider==='ollama'&&!isOllamaCloudConfig(config))keys.push('ollama');/* 로컬 Ollama는 무키 — 자리표시자 Bearer는 서버가 무시 */else throw new Error('api_key_required');}let cursor=0;return{async complete(request:ModelRequest){const first=cursor++%keys.length;try{return await one(config,keys[first]!,fetchImpl).complete(request);}catch(error){const message=error instanceof Error?error.message:String(error);if(!/model_http_(401|429):/.test(message)||keys.length<2)throw new Error(maskSecrets(message,...keys));const second=(first+1)%keys.length;try{return await one(config,keys[second]!,fetchImpl).complete(request);}catch(next){throw new Error(maskSecrets(next instanceof Error?next.message:String(next),...keys));}}}};}
export async function fetchModels(config:ProviderConfig,fetchImpl?:typeof fetch){
 if(config.provider==='ollama-cloud'||config.provider==='ollama'){const key=(config.apiKey.split(/\r?\n/)[0]??'').trim();
  if(isOllamaCloudConfig(config)){try{const response=await (fetchImpl??globalThis.fetch)(ollamaCloudProxyPath('tags')||'https://ollama.com/api/tags',{headers:key?{authorization:`Bearer ${key}`}:{}});if(response.ok){const body=await response.json()as{models?:Array<{name?:unknown;model?:unknown}>};const ids=(body.models??[]).map(item=>String(item.model??item.name??'')).filter(Boolean);if(ids.length)return ids.map(id=>({id,label:id}));}}catch{/* static fallback */}return catalogFor('ollama-cloud');}
  try{const models=await listModels(openAIOptions(config,key,fetchImpl));if(models.length)return models;}catch{/* 네이티브 폴백 */}
  try{const response=await (fetchImpl??globalThis.fetch)(`${ollamaBase(config)}/api/tags`,{headers:key?{authorization:`Bearer ${key}`}:{}});if(response.ok){const body=await response.json()as{models?:Array<{name?:unknown}>};const ids=(body.models??[]).map(item=>String(item.name??'')).filter(Boolean);if(ids.length)return ids.map(id=>({id,label:id}));}}catch{/* 정적 폴백 */}
  return catalogFor('ollama');}
const key=config.apiKey.split(/\r?\n/)[0]??'';if(config.provider==='copilot')return listCopilotModels(key,fetchImpl);if(config.provider==='anthropic'){try{return await listAnthropicModels(key,fetchImpl);}catch{return catalogFor(config.provider);}}if(config.provider==='google'){try{return await listGoogleModels(key,fetchImpl);}catch{return catalogFor(config.provider);}}if(OPENAI_PRESETS[config.provider]||config.provider==='custom'){try{return await listModels(openAIOptions(config,key,fetchImpl),CATALOG[config.provider]);}catch{/* 정적 폴백 */}}return catalogFor(config.provider);}
export * from './openai.ts';export * from './anthropic.ts';export * from './google.ts';export * from './vertex.ts';export * from './auxiliary.ts';
