import{inflateSync}from'fflate';
export interface ZipIndexEntry{path:string;compression:0|8;crc32:number;compressedSize:number;size:number;localHeaderOffset:number}
export interface ZipAssetIndex{contract:'simbot-zip-asset-index/0.1';entries:ZipIndexEntry[];totalEntries:number;centralDirectoryBytes:number;fingerprint:string}
const EOCD=0x06054b50,CENTRAL=0x02014b50,LOCAL=0x04034b50,TAIL=65557,MAX_ENTRY=64*1024*1024,decoder=new TextDecoder();
export async function indexZipAssets(blob:Blob):Promise<ZipAssetIndex>{const tailStart=Math.max(0,blob.size-TAIL),tail=new Uint8Array(await blob.slice(tailStart).arrayBuffer()),eocd=findEocd(tail),view=new DataView(tail.buffer,tail.byteOffset,tail.byteLength),total=view.getUint16(eocd+10,true),centralSize=view.getUint32(eocd+12,true),centralOffset=view.getUint32(eocd+16,true);if(total===0xffff||centralSize===0xffffffff||centralOffset===0xffffffff)throw new Error('zip64_not_supported');if(centralOffset+centralSize>blob.size)throw new Error('zip_central_directory_invalid');const central=new Uint8Array(await blob.slice(centralOffset,centralOffset+centralSize).arrayBuffer()),entries:ZipIndexEntry[]=[];for(let offset=0,count=0;offset<central.length&&count<total;count++){const item=new DataView(central.buffer,central.byteOffset+offset,central.length-offset);if(item.getUint32(0,true)!==CENTRAL)throw new Error('zip_central_entry_invalid');const flags=item.getUint16(8,true),compression=item.getUint16(10,true),nameLength=item.getUint16(28,true),extraLength=item.getUint16(30,true),commentLength=item.getUint16(32,true),path=cleanPath(decoder.decode(central.subarray(offset+46,offset+46+nameLength)));if((flags&1)!==0)throw new Error('zip_encrypted_not_supported');if((compression===0||compression===8)&&image(path))entries.push({path,compression,crc32:item.getUint32(16,true),compressedSize:item.getUint32(20,true),size:item.getUint32(24,true),localHeaderOffset:item.getUint32(42,true)});offset+=46+nameLength+extraLength+commentLength;}return{contract:'simbot-zip-asset-index/0.1',entries,totalEntries:total,centralDirectoryBytes:centralSize,fingerprint:await fingerprint(central)};}
export async function readIndexedZipEntry(blob:Blob,entry:ZipIndexEntry){if(entry.size>MAX_ENTRY)throw new Error('zip_asset_too_large');const header=new Uint8Array(await blob.slice(entry.localHeaderOffset,entry.localHeaderOffset+30).arrayBuffer()),view=new DataView(header.buffer,header.byteOffset,header.byteLength);if(header.length!==30||view.getUint32(0,true)!==LOCAL)throw new Error('zip_local_header_invalid');const start=entry.localHeaderOffset+30+view.getUint16(26,true)+view.getUint16(28,true),compressed=new Uint8Array(await blob.slice(start,start+entry.compressedSize).arrayBuffer()),value=entry.compression===0?compressed:inflateSync(compressed);if(value.length!==entry.size)throw new Error('zip_asset_size_mismatch');return value;}
function findEocd(bytes:Uint8Array){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let offset=bytes.length-22;offset>=0;offset--)if(view.getUint32(offset,true)===EOCD)return offset;throw new Error('zip_eocd_missing');}
function cleanPath(value:string){const path=value.replace(/\\/g,'/').replace(/^\.\//,'');if(!path||path.startsWith('/')||/^[a-z]:/i.test(path)||path.split('/').includes('..'))throw new Error('zip_path_unsafe');return path;}
function image(path:string){return/\.(?:png|jpe?g|webp|gif|avif)$/i.test(path);}
async function fingerprint(bytes:Uint8Array){const digest=await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer);return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');}
