import{describe,expect,it}from'vitest';
import type{PromptPreset,RuntimeWorkerSuccess}from'@simbot/risu';
import{ProjectRuntime}from'@simbot/runtime';
import{PlaySession}from'../src/index.ts';

const source={source:'user' as const,path:'test'},preset:PromptPreset={contract:'prompt-preset/0.1',id:'p',name:'p',compatibilityMode:'simpack',version:1,raw:null,settings:{assistantPrefill:'',sendNames:false,sendChatAsSystem:false},blocks:[{id:'chat',type:'chat',name:'chat',enabled:true,rangeStart:-1000,rangeEnd:'end',source}]};
const make=()=>new PlaySession({id:'chat-a',runtime:new ProjectRuntime({projectId:'card-a',schema:{initialState:{}},screens:[],navigation:[],content:{},featureToggles:{},moduleIds:[]}),preset,card:{name:'Card'},defaultVariables:{kept:'yes'},provider:{async complete(){return{text:'ok'};}}});
const response=(session:PlaySession,patch:RuntimeWorkerSuccess['patch']):RuntimeWorkerSuccess=>{const snapshot=session.cardRuntimeSnapshot();return{type:'result',ok:true,requestId:'r1',sessionId:'chat-a',cardId:'card-a',baseRevision:session.cardRuntimeRevision,patch,effects:[],warnings:[],result:{displayData:null,stopSending:false,ephemeral:{}},randomState:snapshot.randomState,logicalTimeMs:snapshot.logicalTimeMs+1_000,durationMs:1};};

describe('session card-runtime transaction',()=>{
 it('applies a validated patch atomically',async()=>{const session=make(),result=await session.applyCardRuntimeTransaction(response(session,[{op:'set',key:'count',value:'2'},{op:'delete',key:'kept'}]),'r1');expect(result).toEqual({applied:true});expect(session.cbsVariables).toEqual({count:'2'});});
 it('rejects a stale revision without changing any variable',async()=>{const session=make(),stale={...response(session,[{op:'set',key:'count',value:'2'}]),baseRevision:'old'};expect(await session.applyCardRuntimeTransaction(stale,'r1')).toEqual({applied:false,reason:'revision_mismatch'});expect(session.cbsVariables).toEqual({kept:'yes'});});
 it('rejects the entire transaction when one patch or unclassified applied effect is unsafe',async()=>{const session=make(),bad=response(session,[{op:'set',key:'count',value:'2'},{op:'set',key:'__proto__',value:'bad'}]);expect(await session.applyCardRuntimeTransaction(bad,'r1')).toEqual({applied:false,reason:'unsafe_patch_key'});expect(session.cbsVariables).toEqual({kept:'yes'});const effect={...response(session,[]),effects:[{type:'unknown',disposition:'apply' as const,payload:{}}]};expect(await session.applyCardRuntimeTransaction(effect,'r1')).toEqual({applied:false,reason:'effects_unclassified'});});
 it('keeps safe patches when a separate effect is explicitly blocked or awaits approval',async()=>{const session=make(),value={...response(session,[{op:'set',key:'count',value:'2'}]),effects:[{type:'command',disposition:'block' as const,payload:{}},{type:'modifychat',disposition:'approval' as const,payload:{}}]};expect(await session.applyCardRuntimeTransaction(value,'r1')).toEqual({applied:true});expect(session.cbsVariables.count).toBe('2');});
 it('journals card variables so undo and reopen restore variables, RNG and logical time together',async()=>{const session=make();await session.send('one');const first={...response(session,[{op:'set' as const,key:'count',value:'1'}]),requestId:'r1'};await session.applyCardRuntimeTransaction(first,'r1');const afterFirst=session.cardRuntimeSnapshot();await session.send('two');const second={...response(session,[{op:'set' as const,key:'count',value:'2'}]),requestId:'r2'};await session.applyCardRuntimeTransaction(second,'r2');expect(session.cbsVariables.count).toBe('2');await session.undoTurn();expect(session.cbsVariables.count).toBe('1');expect(session.cardRuntimeSnapshot()).toMatchObject({randomState:afterFirst.randomState,logicalTimeMs:afterFirst.logicalTimeMs});const saved=session.snapshot(),restored=make();restored.restore(saved);expect(restored.cbsVariables).toEqual(session.cbsVariables);expect(restored.cardRuntimeSnapshot()).toMatchObject({randomState:session.cardRuntimeSnapshot().randomState,logicalTimeMs:session.cardRuntimeSnapshot().logicalTimeMs});});
});
