import type { ModuleDefinition, RuntimeRecord } from '@simbot/kernel';
import { addOwned, fail, list, moduleDefinition, number, ok, owned, record, rewards, safeKey, scoped, string, type Context } from './support.ts';
function items(schema:RuntimeRecord){return list<RuntimeRecord>(list<RuntimeRecord>(schema.entities).find((entry)=>entry.type==='item')?.instances);}
export function equipmentModule():ModuleDefinition{return moduleDefinition('core.equipment',['core.inventory'],['equipment'],['resources','items'],{
  'equipment/equip':scoped((c)=>{const slot=string(c.params.slot),itemId=string(c.params.itemId),slots=list<unknown>(record(c.schema.equipment).slots);if(!safeKey(slot)||!slots.some((entry)=>typeof entry==='string'?entry===slot:record(entry).id===slot))return fail(c,'unknown_slot',slot);const item=items(c.schema).find((entry)=>entry.id===itemId);if(!item)return fail(c,'unknown_item',itemId);if(item.slot&&item.slot!==slot)return fail(c,'wrong_slot',`${itemId}:${slot}`);if(owned(c.state,itemId)<1)return fail(c,'item_not_owned',itemId);const equipment=record(c.state.equipment),before=equipment[slot]??null;equipment[slot]=itemId;c.state.equipment=equipment;return ok(c,{slot,before,itemId});}),
  'equipment/unequip':scoped((c)=>{const slot=string(c.params.slot),equipment=record(c.state.equipment);if(!equipment[slot])return fail(c,'slot_empty',slot);const itemId=equipment[slot];delete equipment[slot];c.state.equipment=equipment;return ok(c,{slot,itemId});})
},{'equipment/slots':(...args)=>{const schema=record(args[0]),state=record(args[1]),equipment=record(state.equipment);return list<unknown>(record(schema.equipment).slots).map((slot)=>{const id=typeof slot==='string'?slot:string(record(slot).id);return{slot:id,itemId:equipment[id]??null};});}});}

export function questsModule():ModuleDefinition{return moduleDefinition('rpg.quests',[],['questProgress'],['gold','resources'],{
  'quest/start':scoped((c)=>{const quest=list<RuntimeRecord>(c.schema.rpgQuests).find((entry)=>entry.id===c.params.questId),id=string(quest?.id);if(!quest||!safeKey(id))return fail(c,'unknown_quest',c.params.questId);const all=record(c.state.questProgress),existing=record(all[id]);if(Object.keys(existing).length&&existing.status!=='failed')return fail(c,'quest_already_started',id);all[id]={status:'active',steps:{},startedDay:c.state.day as never};c.state.questProgress=all;return ok(c,{questId:id});}),
  'quest/progress':scoped((c)=>{const quest=list<RuntimeRecord>(c.schema.rpgQuests).find((entry)=>entry.id===c.params.questId),all=record(c.state.questProgress),progress=record(all[string(c.params.questId)]);if(!quest||progress.status!=='active')return fail(c,'quest_not_active',c.params.questId);const step=list<RuntimeRecord>(quest.steps).find((entry)=>entry.id===c.params.stepId),id=string(step?.id);if(!step||!safeKey(id))return fail(c,'unknown_quest_step',c.params.stepId);const steps=record(progress.steps);steps[id]=Math.min(number(step.target,1),number(steps[id])+1);progress.steps=steps;const complete=list<RuntimeRecord>(quest.steps).every((entry)=>number(steps[string(entry.id)])>=number(entry.target,1));if(complete)progress.status='complete';all[string(quest.id)]=progress;c.state.questProgress=all;return ok(c,{questId:quest.id,stepId:id,value:steps[id],complete});}),
  'quest/claim':scoped((c)=>{const quest=list<RuntimeRecord>(c.schema.rpgQuests).find((entry)=>entry.id===c.params.questId),all=record(c.state.questProgress),progress=record(all[string(c.params.questId)]);if(!quest||progress.status!=='complete')return fail(c,'quest_not_complete',c.params.questId);rewards(c.state,quest.rewards,c);progress.status='claimed';all[string(quest.id)]=progress;c.state.questProgress=all;return ok(c,{questId:quest.id,rewards:record(quest.rewards)});}),
  'quest/fail':scoped((c)=>{const all=record(c.state.questProgress),id=string(c.params.questId),progress=record(all[id]);if(progress.status!=='active')return fail(c,'quest_not_active',id);progress.status='failed';all[id]=progress;c.state.questProgress=all;return ok(c,{questId:id});})
},{'quests/list':(...args)=>{const schema=record(args[0]),state=record(args[1]),progress=record(state.questProgress);return list<RuntimeRecord>(schema.rpgQuests).map((quest)=>({...quest,progress:progress[string(quest.id)]??null}));}});}

export function shopModule():ModuleDefinition{return moduleDefinition('rpg.shop',['core.inventory'],['shopHistory'],['gold','resources','items'],{
  'shop/buy':scoped((c)=>trade(c,'buy')),'shop/sell':scoped((c)=>trade(c,'sell'))
},{'shop/catalog':(...args)=>{const schema=record(args[0]),state=record(args[1]),shop=list<RuntimeRecord>(schema.shops).find((entry)=>entry.id===args[2]);return list<RuntimeRecord>(shop?.items).map((entry)=>({...entry,owned:owned(state,string(entry.itemId)),affordable:number(state.gold)>=number(entry.buyPrice)}));}});}
function trade(c:Context,direction:'buy'|'sell'){const shop=list<RuntimeRecord>(c.schema.shops).find((entry)=>entry.id===c.params.shopId),item=list<RuntimeRecord>(shop?.items).find((entry)=>entry.itemId===c.params.itemId);if(!item)return fail(c,'unknown_shop_item',`${string(c.params.shopId)}:${string(c.params.itemId)}`);const qty=Math.max(1,Math.trunc(number(c.params.qty,1))),price=number(direction==='buy'?item.buyPrice:item.sellPrice,-1),total=price*qty,id=string(item.itemId);if(price<0)return fail(c,'price_unavailable',direction);if(direction==='buy'){if(number(c.state.gold)<total)return fail(c,'insufficient_gold');c.state.gold=number(c.state.gold)-total;addOwned(c.state,id,qty);}else{if(owned(c.state,id)<qty)return fail(c,'insufficient_items');addOwned(c.state,id,-qty);c.state.gold=number(c.state.gold)+total;}c.state.shopHistory=[...list(c.state.shopHistory),{shopId:shop?.id,itemId:id,qty,direction,total}].slice(-100);return ok(c,{shopId:shop?.id,itemId:id,qty,direction,total});}

export function craftingModule():ModuleDefinition{return moduleDefinition('rpg.crafting',['core.inventory'],['craftingHistory'],['resources','items'],{'crafting/craft':scoped((c)=>{const recipe=list<RuntimeRecord>(c.schema.recipes).find((entry)=>entry.id===c.params.recipeId);if(!recipe)return fail(c,'unknown_recipe',c.params.recipeId);for(const[id,qty]of Object.entries(record(recipe.inputs)))if(owned(c.state,id)<number(qty))return fail(c,'missing_ingredient',id);for(const[id,qty]of Object.entries(record(recipe.inputs)))addOwned(c.state,id,-number(qty));for(const[id,qty]of Object.entries(record(recipe.outputs)))addOwned(c.state,id,number(qty));c.state.craftingHistory=[...list(c.state.craftingHistory),recipe.id].slice(-100);return ok(c,{recipeId:recipe.id,outputs:record(recipe.outputs)});})},{'crafting/recipes':(...args)=>{const schema=record(args[0]),state=record(args[1]);return list<RuntimeRecord>(schema.recipes).map((recipe)=>({...recipe,craftable:Object.entries(record(recipe.inputs)).every(([id,qty])=>owned(state,id)>=number(qty))}));}});}
