import type { ModuleDefinition, RuntimeRecord } from '@simbot/kernel';
import { fail, list, moduleDefinition, number, ok, record, scoped, string } from './support.ts';

type Pool={cur:number;max:number};
type Enemy=RuntimeRecord&{id:string;name:string;rank:string|null;hp:Pool;atk:number;def:number;evade:number;acc:number;dead:boolean};
type Combat=RuntimeRecord&{active:boolean;round:number;enemies:Enemy[];guard:boolean;cleared:boolean;fled:boolean;intents:RuntimeRecord};

function int(value:unknown,fallback=0){const n=Math.trunc(Number(value));return Number.isFinite(n)?n:fallback;}
function num(value:unknown,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function normalizePool(value:unknown):Pool{const p=record(value),max=num(p.max,p.cur==null?0:num(p.cur)),cur=Math.min(max,Math.max(0,num(p.cur,max)));return{cur,max};}
function damage(pool:unknown,amount:unknown):Pool{const p=normalizePool(pool);return{cur:Math.min(p.max,Math.max(0,p.cur-Math.max(0,num(amount)))),max:p.max};}
function spend(pool:unknown,amount:unknown):Pool|null{const p=normalizePool(pool),cost=Math.max(0,num(amount));return p.cur<cost?null:{cur:p.cur-cost,max:p.max};}
function check(c:Parameters<Parameters<typeof scoped>[0]>[0],spec:RuntimeRecord){if(spec.mode==='rate'){const rate=Math.min(100,Math.max(0,int(spec.rate,50))),rand=c.rng.int(1,100),success=rand<=rate;return{mode:'rate',rand,total:rand,success,tier:success?(rand<=5?'critical_success':'success'):(rand>=95?'critical_failure':'failure')};}const sides=int(spec.sides,20),dc=int(spec.dc,10),mod=int(spec.mod),rand=c.rng.int(1,Math.max(1,sides)),total=rand+mod,success=total>=dc;return{mode:'dc',rand,total,success,tier:success?(rand===sides?'critical_success':'success'):(rand===1?'critical_failure':'failure')};}
function config(schema:RuntimeRecord){const c=record(schema.combat);return{d:int(c.d,20),minDamage:int(c.minDamage,1),critMult:num(c.critMult,2),guardMult:num(c.guardMult,.5),fleeRate:int(c.fleeRate,50),heavyRate:int(c.heavyRate,30),heavyMult:num(c.heavyMult,1.5),heavyAcc:int(c.heavyAcc,-2),defeatReviveRatio:Math.min(1,Math.max(0,num(c.defeatReviveRatio,.2))),expTable:record(c.expTable),lootGold:record(c.lootGold)};}
function player(state:RuntimeRecord){const p=record(state.player);return{atk:int(p.atk,5),def:int(p.def),evade:int(p.evade,10),acc:int(p.acc)};}
function combat(state:RuntimeRecord):Combat|null{const c=record(state.combat);return c.active!=null?c as Combat:null;}
function enemy(c:Combat,ref:unknown){const key=string(ref);return c.enemies.find((e)=>e.id===key||e.name===key)??null;}
function publicEnemy(e:Enemy){return{id:e.id,name:e.name,rank:e.rank,hp:{...e.hp},dead:e.dead};}
function forbidden(params:RuntimeRecord){return['power','damage','dmg','roll','amount','hp'].some((key)=>key in params);}
function rollIntents(c:Parameters<Parameters<typeof scoped>[0]>[0],enemies:Enemy[]){const cfg=config(c.schema),result:RuntimeRecord={};for(const e of enemies)result[e.id]=c.rng.int(1,100)<=cfg.heavyRate?'heavy':'attack';return result;}
function attackPlayer(c:Parameters<Parameters<typeof scoped>[0]>[0],foe:Enemy,skill:RuntimeRecord={},intent='attack'){const battle=combat(c.state)!,cfg=config(c.schema),pc=player(c.state),heavy=intent==='heavy',hit=check(c,{mode:'dc',sides:cfg.d,dc:pc.evade,mod:foe.acc+int(skill.acc)+(heavy?cfg.heavyAcc:0)});let dealt=0;if(hit.success){dealt=Math.max(cfg.minDamage,foe.atk+int(skill.power)-pc.def);if(heavy)dealt=Math.round(dealt*cfg.heavyMult);if(hit.tier==='critical_success')dealt=Math.round(dealt*cfg.critMult);if(battle.guard)dealt=Math.max(0,Math.floor(dealt*cfg.guardMult));const p=record(c.state.player),pools=record(p.pools);pools.hp=damage(pools.hp,dealt);p.pools=pools;if(normalizePool(pools.hp).cur<=0)p.dead=true;c.state.player=p;}const p=record(c.state.player),pools=record(p.pools);return{hit:hit.success,tier:hit.tier,roll:hit.rand,damage:dealt,playerHp:normalizePool(pools.hp),playerDead:!!p.dead};}
function range(value:unknown):[number,number]|null{const a=list<unknown>(value);return a.length===2&&Number.isFinite(Number(a[0]))&&Number.isFinite(Number(a[1]))?[num(a[0]),num(a[1])]:null;}
function applyExp(schema:RuntimeRecord,state:RuntimeRecord,amount:number,levelUps:number[]){const p=record(state.player);p.exp=num(p.exp)+amount;const ladder=list<RuntimeRecord>(schema.ladders).find((x)=>x.id==='player_level');for(const threshold of list<unknown>(ladder?.thresholds).slice(Math.max(0,int(p.level,1)-1))){if(!num(threshold)||num(p.exp)<num(threshold))break;p.exp=num(p.exp)-num(threshold);p.level=int(p.level,1)+1;levelUps.push(int(p.level));}state.player=p;}

export function statsModule():ModuleDefinition{return moduleDefinition('core.stats',[],['player.level','player.exp'],[],{},{});}
export function combatModule():ModuleDefinition{return moduleDefinition('combat.turnbased',['core.stats','core.inventory'],['combat'],['player','gold','pendingQuest'],{
  start_encounter:scoped((c)=>{const current=combat(c.state);if(current?.active)return fail(c,'encounter_active');const roster=list<RuntimeRecord>(c.params.enemies);if(!roster.length)return fail(c,'no_enemies');const enemies:Enemy[]=[];for(let i=0;i<roster.length;i++){const source=roster[i]!,hp=int(source.hp);if(hp<=0)return fail(c,'invalid_enemy_hp',source.name??`e${i+1}`);enemies.push({id:`e${i+1}`,name:string(source.name||`적${i+1}`),rank:source.rank==null?null:string(source.rank),hp:{cur:hp,max:hp},atk:int(source.atk,5),def:int(source.def),evade:int(source.evade,10),acc:int(source.acc),dead:false});}const p=record(c.state.player),pools=record(p.pools);if(!Object.prototype.hasOwnProperty.call(pools,'hp'))return fail(c,'player_hp_pool_missing','pools에 hp가 없어 전투를 시작할 수 없습니다');const battle:Combat={active:true,round:1,enemies,guard:false,cleared:false,fled:false,intents:{}};c.state.combat=battle;battle.intents=rollIntents(c,enemies);return ok(c,{enemies:enemies.map(publicEnemy)});} ),
  combat_action:scoped((c)=>{const battle=combat(c.state),p=record(c.state.player);if(!battle?.active)return fail(c,'no_encounter');if(p.dead)return fail(c,'player_dead');if(forbidden(c.params))return fail(c,'combat_number_not_allowed');const action=string(c.params.action);if(action==='defend'){battle.guard=true;return ok(c,{action,guard:true});}if(action==='flee'){const result=check(c,{mode:'rate',rate:config(c.schema).fleeRate});if(result.success){battle.active=false;battle.fled=true;}return ok(c,{action,check:result,fled:result.success});}if(action!=='attack'&&action!=='skill')return fail(c,'unknown_combat_action',action);const target=enemy(battle,c.params.target);if(!target)return fail(c,'unknown_target',c.params.target);if(target.dead)return fail(c,'target_dead',target.id);let skill:RuntimeRecord={},skillId:null|string=null;if(action==='skill'){skillId=string(c.params.skill);skill=record(record(c.schema.skills)[skillId]);if(!Object.keys(skill).length)return fail(c,'unknown_skill',skillId);const poolId=string(skill.pool||'mp'),pools=record(p.pools),next=spend(pools[poolId],skill.cost);if(!next)return fail(c,`insufficient_${poolId}`,skillId);pools[poolId]=next;p.pools=pools;c.state.player=p;}const cfg=config(c.schema),pc=player(c.state),hit=check(c,{mode:'dc',sides:cfg.d,dc:target.evade,mod:pc.acc+int(skill.acc)});let dealt=0;if(hit.success){dealt=Math.max(cfg.minDamage,pc.atk+int(skill.power)-target.def);if(hit.tier==='critical_success')dealt=Math.round(dealt*cfg.critMult);target.hp=damage(target.hp,dealt);target.dead=target.hp.cur<=0;}battle.cleared=battle.enemies.every((e)=>e.dead);return ok(c,{action,skill:skillId,target:target.id,hit:hit.success,tier:hit.tier,roll:hit.rand,damage:dealt,enemy:publicEnemy(target),cleared:battle.cleared});}),
  enemy_action:scoped((c)=>{const battle=combat(c.state),p=record(c.state.player);if(!battle?.active)return fail(c,'no_encounter');if(p.dead)return fail(c,'player_dead');if(forbidden(c.params))return fail(c,'combat_number_not_allowed');const foe=enemy(battle,c.params.enemyId);if(!foe)return fail(c,'unknown_enemy',c.params.enemyId);if(foe.dead)return fail(c,'enemy_dead',foe.id);const result=attackPlayer(c,foe,record(record(c.schema.skills)[string(c.params.skill)]));battle.guard=false;return ok(c,{enemyId:foe.id,action:string(c.params.action||'attack'),skill:c.params.skill??null,...result});}),
  enemy_turn:scoped((c)=>{const battle=combat(c.state);if(!battle)return fail(c,'no_encounter');const p=record(c.state.player),pools=record(p.pools);if(battle.cleared||battle.fled)return ok(c,{results:[],playerHp:normalizePool(pools.hp),playerDead:!!p.dead});if(p.dead)return fail(c,'player_dead');if(!battle.active)return fail(c,'no_encounter');const results:RuntimeRecord[]=[];for(const foe of battle.enemies){if(foe.dead||foe.hp.cur<=0)continue;const intent=battle.intents[foe.id]==='heavy'?'heavy':'attack',result=attackPlayer(c,foe,{},intent);results.push({enemyId:foe.id,intent,hit:result.hit,tier:result.tier,roll:result.roll,damage:result.damage});if(result.hit)battle.guard=false;if(result.playerDead)break;}battle.guard=false;const after=record(c.state.player);battle.intents=after.dead?{}:rollIntents(c,battle.enemies.filter((e)=>!e.dead&&e.hp.cur>0));return ok(c,{results,playerHp:normalizePool(record(after.pools).hp),playerDead:!!after.dead});}),
  end_encounter:scoped((c)=>{const battle=combat(c.state);if(!battle)return fail(c,'no_encounter_to_end');const p=record(c.state.player);if(battle.active&&!battle.cleared&&!battle.fled&&!p.dead)return fail(c,'encounter_unresolved');const cfg=config(c.schema),levelUps:number[]=[];let expGained=0,goldGained=0;if(battle.cleared)for(const foe of battle.enemies){const exp=range(cfg.expTable[foe.rank??'']??cfg.expTable.default),gold=range(cfg.lootGold[foe.rank??'']??cfg.lootGold.default);if(exp)expGained+=c.rng.int(...exp);if(gold)goldGained+=c.rng.int(...gold);}if(expGained)applyExp(c.schema,c.state,expGained,levelUps);if(goldGained)c.state.gold=num(c.state.gold)+goldGained;const outcome=battle.cleared?'victory':battle.fled?'fled':p.dead?'defeat':'ended';let revivedHp:null|number=null;if(p.dead){const pools=record(p.pools),hp=normalizePool(pools.hp);revivedHp=Math.max(1,Math.floor(hp.max*cfg.defeatReviveRatio));pools.hp={cur:revivedHp,max:hp.max};p.pools=pools;p.dead=false;c.state.player=p;}const questId=battle.questId;c.state.combat=null;const pending=record(c.state.pendingQuest);if(outcome==='victory'&&pending.questId===questId)pending.cleared=true;return ok(c,{outcome,expGained,goldGained,levelUps,player:structuredClone(record(c.state.player)),...(revivedHp==null?{}:{revivedHp})});})
},{'combat/available-actions':(...args)=>{const state=record(args[1]),battle=combat(state);if(!battle?.active)return[];return['attack','skill','defend','flee'];}});}
