import type { ModuleDefinition, RuntimeRecord } from '@simbot/kernel';
import { addOwned, fail, list, moduleDefinition, number, ok, owned, record, rewards, roll, safeKey, scoped, string } from './support.ts';

export function progressionModule():ModuleDefinition{return moduleDefinition('core.progression',[],['player.statPoints'],['player.level','player.exp'],{
  'progression/gain':scoped((c)=>{const config=record(c.schema.progression),sources=record(config.sources),source=sources[string(c.params.source)];if(source==null)return fail(c,'unknown_progression_source',c.params.source);const player=record(c.state.player),amount=roll(source,c),levels=number(player.level,1),beforeExp=number(player.exp);player.exp=beforeExp+amount;player.level=levels;const thresholds=list<unknown>(config.thresholds),ups=number(config.statPointsPerLevel);const levelUps:number[]=[];while(thresholds[number(player.level)-1]!=null&&number(player.exp)>=number(thresholds[number(player.level)-1])){player.exp=number(player.exp)-number(thresholds[number(player.level)-1]);player.level=number(player.level)+1;player.statPoints=number(player.statPoints)+ups;levelUps.push(number(player.level));}c.state.player=player;return ok(c,{source:string(c.params.source),amount,before:{level:levels,exp:beforeExp},after:{level:player.level,exp:player.exp},levelUps,statPoints:number(player.statPoints)});}),
  'progression/allocate':scoped((c)=>{const config=record(c.schema.progression),stat=string(c.params.stat);if(!safeKey(stat)||!list<string>(config.allocatableStats).includes(stat))return fail(c,'unknown_stat',stat);const player=record(c.state.player);if(number(player.statPoints)<1)return fail(c,'no_stat_points');const stats=record(player.stats),before=number(stats[stat]??player[stat]);stats[stat]=before+1;player.stats=stats;player.statPoints=number(player.statPoints)-1;c.state.player=player;return ok(c,{stat,before,after:before+1,remaining:player.statPoints});})
},{'progression/summary':(...args)=>{const schema=record(args[0]),state=record(args[1]),player=record(state.player),config=record(schema.progression),thresholds=list<unknown>(config.thresholds);return{level:player.level,exp:player.exp,next:thresholds[number(player.level)-1]??null,statPoints:number(player.statPoints)};}});}

export function partyModule():ModuleDefinition{return moduleDefinition('rpg.party',[],['party'],['npcs'],{
  'party/add':scoped((c)=>{const id=string(c.params.memberId),entities=list<RuntimeRecord>(c.schema.entities),npcs=list<RuntimeRecord>(entities.find((e)=>e.type==='npc')?.instances);if(!npcs.some((npc)=>npc.id===id))return fail(c,'unknown_member',id);const party=record(c.state.party),members=list<string>(party.members);if(members.includes(id))return fail(c,'already_in_party',id);if(members.length>=number(record(c.schema.party).maxSize,4))return fail(c,'party_full');party.members=[...members,id];party.formation=record(party.formation);c.state.party=party;return ok(c,{memberId:id});}),
  'party/remove':scoped((c)=>{const id=string(c.params.memberId),party=record(c.state.party),members=list<string>(party.members);if(!members.includes(id))return fail(c,'not_in_party',id);party.members=members.filter((value)=>value!==id);const formation=record(party.formation);for(const[role,value]of Object.entries(formation))if(value===id)delete formation[role];party.formation=formation;c.state.party=party;return ok(c,{memberId:id});}),
  'party/assign':scoped((c)=>{const id=string(c.params.memberId),role=string(c.params.role),config=record(c.schema.party),party=record(c.state.party);if(!safeKey(role)||!list<string>(config.roles).includes(role))return fail(c,'unknown_party_role',role);if(!list<string>(party.members).includes(id))return fail(c,'not_in_party',id);const formation=record(party.formation);formation[role]=id;party.formation=formation;c.state.party=party;return ok(c,{role,memberId:id});})
},{'party/formation':(...args)=>record(record(args[1]).party)});}

export function timeModule():ModuleDefinition{return moduleDefinition('core.time',[],['clock'],['day'],{'time/advance':scoped((c)=>{const unit=string(c.params.unit||'turn');if(!['turn','hour','day'].includes(unit))return fail(c,'unknown_time_unit',unit);const clock=Object.keys(record(c.state.clock)).length?record(c.state.clock):{day:number(c.state.day,1),hour:8,turn:0};const before={...clock};if(unit==='turn')clock.turn=number(clock.turn)+1;if(unit==='hour')clock.hour=number(clock.hour)+number(record(c.schema.time).hoursPerStep,1);if(unit==='day')clock.day=number(clock.day)+1;while(number(clock.hour)>=24){clock.hour=number(clock.hour)-24;clock.day=number(clock.day)+1;}c.state.clock=clock;c.state.day=clock.day;return ok(c,{unit,before,after:{...clock}});})},{'time/current':(...args)=>record(record(args[1]).clock)});}

export function locationModule():ModuleDefinition{return moduleDefinition('core.location',[],['location'],[],{'location/move':scoped((c)=>{const target=string(c.params.locationId),locations=list<RuntimeRecord>(c.schema.locations),destination=locations.find((value)=>value.id===target);if(!destination)return fail(c,'unknown_location',target);const current=locations.find((value)=>value.id===c.state.location),links=list<string>(current?.links);if(current&&links.length&&!links.includes(target))return fail(c,'location_not_connected',`${string(c.state.location)}:${target}`);const before=c.state.location??null;c.state.location=target;return ok(c,{before,locationId:target});})},{'location/map':(...args)=>{const schema=record(args[0]),state=record(args[1]),locations=list<RuntimeRecord>(schema.locations),current=locations.find((value)=>value.id===state.location),links=list<string>(current?.links);return locations.map((location)=>({...location,current:location.id===state.location,reachable:location.id===state.location||!current||links.includes(string(location.id))}));}});}

export function lootModule():ModuleDefinition{return moduleDefinition('rpg.loot',['core.inventory'],['lootHistory'],['resources','items'],{'loot/roll':scoped((c)=>{const table=list<RuntimeRecord>(c.schema.lootTables).find((value)=>value.id===c.params.tableId),entries=list<RuntimeRecord>(table?.entries);if(!table||!entries.length)return fail(c,'unknown_loot_table',c.params.tableId);const total=entries.reduce((sum,e)=>sum+Math.max(0,number(e.weight,1)),0);let ticket=c.rng.int(1,Math.max(1,total));const entry=entries.find((e)=>{ticket-=Math.max(0,number(e.weight,1));return ticket<=0;})??entries[entries.length-1];if(!entry)return fail(c,'unknown_loot_table',c.params.tableId);const qty=roll(entry.qty??1,c),itemId=string(entry.itemId);addOwned(c.state,itemId,qty);c.state.lootHistory=[...list(c.state.lootHistory),{tableId:table.id,itemId,qty}].slice(-100);return ok(c,{tableId:table.id,itemId,qty});})},{'loot/tables':(...args)=>list(record(args[0]).lootTables)});}

export function factionsModule():ModuleDefinition{return moduleDefinition('core.factions',[],['factions'],[],{'factions/change':scoped((c)=>{const id=string(c.params.factionId),faction=list<RuntimeRecord>(c.schema.factions).find((value)=>value.id===id),source=faction&&record(faction.sources)[string(c.params.source)];if(!faction||!safeKey(id)||source==null)return fail(c,'unknown_faction_source',`${id}:${string(c.params.source)}`);const factions=record(c.state.factions),before=number(factions[id]??faction.initial),delta=roll(source,c),after=Math.max(number(faction.min,-100),Math.min(number(faction.max,100),before+delta));factions[id]=after;c.state.factions=factions;return ok(c,{factionId:id,source:string(c.params.source),before,delta,after});})},{'factions/list':(...args)=>{const schema=record(args[0]),state=record(args[1]),values=record(state.factions);return list<RuntimeRecord>(schema.factions).map((faction)=>({...faction,value:values[string(faction.id)]??faction.initial??0}));}});}

export function jobsModule():ModuleDefinition{return moduleDefinition('core.jobs',['core.time'],['jobs'],['resources','items','gold'],{
  'jobs/start':scoped((c)=>{const def=list<RuntimeRecord>(c.schema.jobs).find((value)=>value.id===c.params.jobId);if(!def)return fail(c,'unknown_job',c.params.jobId);for(const[id,qty]of Object.entries(record(def.cost)))if(id==='gold'?number(c.state.gold)<number(qty):owned(c.state,id)<number(qty))return fail(c,'job_cost_missing',id);for(const[id,qty]of Object.entries(record(def.cost)))if(id==='gold')c.state.gold=number(c.state.gold)-number(qty);else addOwned(c.state,id,-number(qty));const jobs=list<RuntimeRecord>(c.state.jobs),instanceId=`${string(def.id)}:${number(record(c.state.clock).turn)}:${jobs.length}`;c.state.jobs=[...jobs,{id:instanceId,jobId:def.id,remaining:Math.max(1,number(def.duration,1)),status:'active'}];return ok(c,{instanceId,jobId:def.id});}),
  'jobs/tick':scoped((c)=>{const jobs=list<RuntimeRecord>(c.state.jobs),job=jobs.find((value)=>value.id===c.params.instanceId);if(!job||job.status!=='active')return fail(c,'job_not_active',c.params.instanceId);job.remaining=number(job.remaining)-1;if(number(job.remaining)<=0){const def=list<RuntimeRecord>(c.schema.jobs).find((value)=>value.id===job.jobId);rewards(c.state,def?.outputs,c);job.remaining=0;job.status='complete';}c.state.jobs=jobs;return ok(c,{instanceId:job.id,remaining:job.remaining,status:job.status});}),
  'jobs/collect':scoped((c)=>{const jobs=list<RuntimeRecord>(c.state.jobs),index=jobs.findIndex((value)=>value.id===c.params.instanceId&&value.status==='complete');if(index<0)return fail(c,'job_not_complete',c.params.instanceId);const job=jobs[index];c.state.jobs=jobs.filter((_,i)=>i!==index);return ok(c,{instanceId:job?.id,jobId:job?.jobId});})
},{'jobs/queue':(...args)=>list(record(args[1]).jobs)});}

export function inventoryModule():ModuleDefinition{return moduleDefinition('core.inventory',[],['resources','items'],['gold'],{},{});}
export const commonModules=()=>[inventoryModule(),progressionModule(),partyModule(),timeModule(),locationModule(),lootModule(),factionsModule(),jobsModule()];
