import type { ModuleDefinition, RuntimeRecord } from '@simbot/kernel'; import { addOwned, fail, list, moduleDefinition, number, ok, record, roll, scoped, string } from './support.ts';
function config(schema:RuntimeRecord){return record(schema.hunter);} function ranks(schema:RuntimeRecord){return list<RuntimeRecord>(record(config(schema).assessment).ranks);} function gates(schema:RuntimeRecord){return list<RuntimeRecord>(config(schema).gates);} function rankIndex(schema:RuntimeRecord,id:unknown){return ranks(schema).findIndex((rank)=>rank.id===id);} function rankFor(schema:RuntimeRecord,score:number){return ranks(schema).filter((rank)=>score>=number(rank.min)).sort((a,b)=>number(b.min)-number(a.min))[0];}
export function hunterModule():ModuleDefinition{return moduleDefinition('genre.hunter',['core.progression','rpg.party','rpg.loot'],['hunter'],['gold','resources','player.exp'],{
  'hunter/register':scoped((c)=>{const hunter=record(c.state.hunter);if(hunter.registered)return fail(c,'hunter_already_registered');const name=string(c.params.name).trim();if(!name)return fail(c,'hunter_name_required');c.state.hunter={...hunter,registered:true,name,rank:null,assessmentScore:null,activeGateId:null,clearedGateId:null,guildId:null};return ok(c,{name});}),
  'hunter/assess':scoped((c)=>{const hunter=record(c.state.hunter);if(!hunter.registered)return fail(c,'hunter_not_registered');if(hunter.rank)return fail(c,'hunter_already_assessed');if('score'in c.params)return fail(c,'hunter_score_not_allowed');const assessment=record(config(c.schema).assessment),base=number(assessment.defaultScore),variance=list<unknown>(assessment.variance),score=Math.max(0,base+(variance.length>=2?c.rng.int(number(variance[0]),number(variance[1])):0)),rank=rankFor(c.schema,score);if(!rank)return fail(c,'hunter_rank_unresolved',score);hunter.assessmentScore=score;hunter.rank=rank.id;c.state.hunter=hunter;return ok(c,{score,rank:rank.id});}),
  'hunter/gate-accept':scoped((c)=>{const hunter=record(c.state.hunter);if(!hunter.rank)return fail(c,'hunter_not_assessed');if(hunter.activeGateId)return fail(c,'gate_already_active');const gate=gates(c.schema).find((entry)=>entry.id===c.params.gateId);if(!gate)return fail(c,'unknown_gate',c.params.gateId);if(rankIndex(c.schema,hunter.rank)<rankIndex(c.schema,gate.minRank??'E'))return fail(c,'hunter_rank_too_low',gate.minRank);if(list(record(c.state.party).members).length<number(gate.minParty))return fail(c,'party_too_small',gate.minParty);hunter.activeGateId=gate.id;hunter.clearedGateId=null;c.state.hunter=hunter;return ok(c,{gateId:gate.id});}),
  'hunter/gate-clear':scoped((c)=>{const hunter=record(c.state.hunter);if(hunter.activeGateId!==c.params.gateId)return fail(c,'gate_not_active',c.params.gateId);hunter.clearedGateId=c.params.gateId;c.state.hunter=hunter;return ok(c,{gateId:c.params.gateId});}),
  'hunter/settle':scoped((c)=>{const hunter=record(c.state.hunter),gate=gates(c.schema).find((entry)=>entry.id===c.params.gateId);if(!gate||hunter.clearedGateId!==gate.id)return fail(c,'gate_not_cleared',c.params.gateId);const settlement=record(gate.settlement),gold=roll(settlement.gold,c),exp=roll(settlement.exp,c),manaStone=roll(settlement.manaStone,c);c.state.gold=number(c.state.gold)+gold;const player=record(c.state.player);player.exp=number(player.exp)+exp;c.state.player=player;const resources=record(c.state.resources);resources.mana_stone=number(resources.mana_stone)+manaStone;c.state.resources=resources;hunter.activeGateId=null;hunter.clearedGateId=null;c.state.hunter=hunter;return ok(c,{gateId:gate.id,gold,exp,manaStone});})
},{'hunter/status':(...args)=>{const schema=record(args[0]),state=record(args[1]),hunter=record(state.hunter),player=record(state.player),rank=ranks(schema).find((entry)=>entry.id===hunter.rank);return{...hunter,level:player.level,exp:player.exp,rankLabel:rank?.label??null};},'hunter/gates':(...args)=>{const schema=record(args[0]),state=record(args[1]),hunter=record(state.hunter);return gates(schema).map((gate)=>({...gate,available:!!hunter.rank&&rankIndex(schema,hunter.rank)>=rankIndex(schema,gate.minRank??'E')}));}});}
