import type { ModuleDefinition, RuntimeRecord } from '@simbot/kernel';
import { fail, list, moduleDefinition, number, ok, record, roll, scoped, string } from './support.ts';

function config(schema:RuntimeRecord){return record(schema.hunter);}
function ranks(schema:RuntimeRecord){return list<RuntimeRecord>(record(config(schema).assessment).ranks);}
function gates(schema:RuntimeRecord){return list<RuntimeRecord>(config(schema).gates);}
function rankIndex(schema:RuntimeRecord,id:unknown){return ranks(schema).findIndex((rank)=>rank.id===id);}
function rankFor(schema:RuntimeRecord,score:number){return ranks(schema).filter((rank)=>score>=number(rank.min)).sort((a,b)=>number(b.min)-number(a.min))[0];}
function activeCombat(state:RuntimeRecord){return record(state.combat).active===true;}
function gateFor(schema:RuntimeRecord,id:unknown){return gates(schema).find((entry)=>entry.id===id);}
function gateQuestId(id:unknown){return `gate:${string(id)}`;}

export function hunterModule():ModuleDefinition{return moduleDefinition('genre.hunter',['core.progression','rpg.party','rpg.loot'],['hunter'],['gold','resources','player.exp','combat','pendingQuest'],{
  'hunter/register':scoped((c)=>{const hunter=record(c.state.hunter);if(hunter.registered)return fail(c,'hunter_already_registered');const name=string(c.params.name).trim();if(!name)return fail(c,'hunter_name_required');c.state.hunter={...hunter,registered:true,name,rank:null,assessmentScore:null,activeGateId:null,clearedGateId:null,guildId:null};return ok(c,{name});}),
  'hunter/assess':scoped((c)=>{const hunter=record(c.state.hunter);if(!hunter.registered)return fail(c,'hunter_not_registered');if(hunter.rank)return fail(c,'hunter_already_assessed');if('score'in c.params)return fail(c,'hunter_score_not_allowed');const assessment=record(config(c.schema).assessment),base=number(assessment.defaultScore),variance=list<unknown>(assessment.variance),score=Math.max(0,base+(variance.length>=2?c.rng.int(number(variance[0]),number(variance[1])):0)),rank=rankFor(c.schema,score);if(!rank)return fail(c,'hunter_rank_unresolved',score);hunter.assessmentScore=score;hunter.rank=rank.id;c.state.hunter=hunter;return ok(c,{score,rank:rank.id});}),
  'hunter/gate-accept':scoped((c)=>{const hunter=record(c.state.hunter);if(!hunter.rank)return fail(c,'hunter_not_assessed');if(hunter.activeGateId)return fail(c,'gate_already_active');const gate=gateFor(c.schema,c.params.gateId);if(!gate)return fail(c,'unknown_gate',c.params.gateId);if(rankIndex(c.schema,hunter.rank)<rankIndex(c.schema,gate.minRank??'E'))return fail(c,'hunter_rank_too_low',gate.minRank);if(list(record(c.state.party).members).length<number(gate.minParty))return fail(c,'party_too_small',gate.minParty);hunter.activeGateId=gate.id;hunter.clearedGateId=null;c.state.hunter=hunter;return ok(c,{gateId:gate.id});}),
  'hunter/gate-raid':scoped((c)=>{const hunter=record(c.state.hunter),gate=gateFor(c.schema,c.params.gateId);if(hunter.activeGateId!==c.params.gateId)return fail(c,'gate_not_active',c.params.gateId);if(!gate)return fail(c,'unknown_gate',c.params.gateId);if(activeCombat(c.state))return fail(c,'in_combat');const encounter=record(gate.encounter);if(!Object.keys(encounter).length)return ok(c,{gateId:gate.id,encounter:false});const questId=gateQuestId(gate.id),chance=Math.max(0,Math.min(100,number(encounter.chance,100)));if(c.rng.int(1,100)>chance){c.state.pendingQuest={questId,day:c.state.day,cleared:true};return ok(c,{gateId:gate.id,encounter:false});}const started=c.registry.dispatch(c.schema,c.state,{id:'start_encounter',params:{enemies:list<RuntimeRecord>(encounter.enemies)}},c.rng);if(!started.log[0]?.ok)return started;c.state=started.state;const combat=record(c.state.combat);combat.questId=questId;combat.gateId=gate.id;c.state.combat=combat;c.state.pendingQuest={questId,day:c.state.day};return ok(c,{gateId:gate.id,encounter:true,enemies:started.log[0].enemies});}),
  'hunter/gate-clear':scoped((c)=>{const hunter=record(c.state.hunter),gate=gateFor(c.schema,c.params.gateId);if(hunter.activeGateId!==c.params.gateId)return fail(c,'gate_not_active',c.params.gateId);if(!gate)return fail(c,'unknown_gate',c.params.gateId);if(gate.encounter){const pending=record(c.state.pendingQuest);if(pending.questId!==gateQuestId(gate.id)||pending.cleared!==true)return fail(c,'gate_not_conquered',gate.id);}hunter.clearedGateId=gate.id;c.state.hunter=hunter;delete c.state.pendingQuest;return ok(c,{gateId:gate.id});}),
  'hunter/settle':scoped((c)=>{const hunter=record(c.state.hunter),gate=gateFor(c.schema,c.params.gateId);if(!gate||hunter.clearedGateId!==gate.id)return fail(c,'gate_not_cleared',c.params.gateId);const settlement=record(gate.settlement),gold=roll(settlement.gold,c),exp=roll(settlement.exp,c),manaStone=roll(settlement.manaStone,c),goldBefore=number(c.state.gold);c.state.gold=goldBefore+gold;const player=record(c.state.player),expBefore=number(player.exp);player.exp=expBefore+exp;c.state.player=player;const resources=record(c.state.resources);resources.mana_stone=number(resources.mana_stone)+manaStone;c.state.resources=resources;hunter.activeGateId=null;hunter.clearedGateId=null;c.state.hunter=hunter;return{state:c.state,log:[{ok:true,event:c.event.id,gateId:gate.id,gold,exp,manaStone},{ok:true,event:'gold_delta',amount:gold,before:goldBefore,after:c.state.gold,reason:'게이트 정산'},{ok:true,event:'exp_gain',amount:exp,before:expBefore,after:player.exp,reason:'게이트 정산'}]};})
},{
  'hunter/status':(...args)=>{const schema=record(args[0]),state=record(args[1]),hunter=record(state.hunter),player=record(state.player),rank=ranks(schema).find((entry)=>entry.id===hunter.rank),gate=gateFor(schema,hunter.activeGateId),pending=record(state.pendingQuest),combat=activeCombat(state),conquered=!!gate?.encounter&&pending.questId===gateQuestId(gate.id)&&pending.cleared===true,canRegister=!hunter.registered,canAssess=!!hunter.registered&&!hunter.rank,canSettle=!!hunter.clearedGateId,canRaid=!!gate?.encounter&&!combat&&!conquered&&!canSettle,canClear=!!gate&&!canSettle&&(!gate.encounter||conquered);let reason='먼저 헌터 등록을 진행하세요.';if(canRegister)reason='헌터 등록이 가능합니다.';else if(canAssess)reason='헌터 등급 평가가 가능합니다.';else if(!gate&&!canSettle)reason='공략할 게이트를 수락하세요.';else if(combat)reason='진행 중인 전투를 먼저 마쳐야 합니다.';else if(canRaid)reason='게이트 공략이 가능합니다.';else if(canClear)reason='클리어 보고가 가능합니다.';else if(canSettle)reason='보상 정산이 가능합니다.';return{...hunter,level:player.level,exp:player.exp,rankLabel:rank?.label??null,canRegister,canAssess,canRaid,canClear,canSettle,reason};},
  'hunter/gates':(...args)=>{const schema=record(args[0]),state=record(args[1]),hunter=record(state.hunter);return gates(schema).map((gate)=>({...gate,available:!!hunter.rank&&rankIndex(schema,hunter.rank)>=rankIndex(schema,gate.minRank??'E')}));}
});}
