import { deriveRng,type ModuleDefinition,type RuntimeRecord } from '@simbot/kernel';
import { fail,list,moduleDefinition,number,ok,own,record,safeKey,scoped,string } from './support.ts';

function entities(schema:RuntimeRecord,type:string){return list<RuntimeRecord>(schema.entities).find((block)=>block.type===type)?.instances as RuntimeRecord[]|undefined??[];}
function byId(schema:RuntimeRecord,type:string,id:unknown){const key=string(id);return entities(schema,type).find((value)=>string(value.id)===key)??null;}
function room(schema:RuntimeRecord,no:unknown){const key=string(no);return entities(schema,'room').find((value)=>string(value.no)===key)??null;}
function menu(schema:RuntimeRecord,name:unknown){const normalize=(value:unknown)=>string(value).replace(/\s+/g,'').toLocaleLowerCase();const key=normalize(name);return entities(schema,'menuItem').find((value)=>normalize(value.name)===key)??null;}
function staffing(schema:RuntimeRecord,state:RuntimeRecord){const config=record(schema.staffing),facility=string(config.facility||'quarters'),level=string(record(state.facilities)[facility]||1),table=Object.keys(record(config.capacityByLevel)).length?record(config.capacityByLevel):record(record(schema.gates).staffMaxByQuartersLevel);return number(table[level]);}
function consumption(item:RuntimeRecord,state:RuntimeRecord){const explicit=record(item.consumes);if(Object.keys(explicit).length)return explicit;const category=string(item.category),resources=record(state.resources);if(/drink|liquor|주류|주점/i.test(category)&&'drink'in resources)return{drink:1};if(/food|cuisine|dish|meal|요리|식사/i.test(category)&&'food'in resources)return{food:1};if(/special|material|특수|재료/i.test(category)&&'material'in resources)return{material:1};return{};}
function inCombat(state:RuntimeRecord){return record(state.combat).active===true;}
function questEligible(state:RuntimeRecord,quest:RuntimeRecord){const requires=record(quest.requires),facility=requires.facility;if(!facility)return true;const id=typeof facility==='string'?facility:string(record(facility).id),level=typeof facility==='string'?number(requires.level,1):number(record(facility).level,1);return number(record(state.facilities)[id])>=level;}
function activeQuests(schema:RuntimeRecord,state:RuntimeRecord){const board=record(schema.questBoard);if(Object.keys(board).length&&number(record(state.facilities)[string(board.facility)])<number(board.unlockLevel,1))return[];const candidates=list<RuntimeRecord>(schema.quests).filter((quest)=>questEligible(state,quest)),rng=deriveRng(state.seed??0,`questboard/${string(board.facility||'none')}`),shuffled=[...candidates];for(let i=shuffled.length-1;i>0;i--){const j=rng.int(0,i),hold=shuffled[i];shuffled[i]=shuffled[j]!;shuffled[j]=hold!;}if(!Object.keys(board).length)return shuffled;const size=Math.max(1,Math.trunc(number(board.size,3))),offset=shuffled.length?((Math.max(1,number(state.day,1))-1)*size)%shuffled.length:0;return[...shuffled.slice(offset),...shuffled.slice(0,offset)].slice(0,size);}
const RANKS=['E','D','C','B','A','S'];
const QUEST_ENCOUNTER_STATS:Record<string,RuntimeRecord>={E:{hp:8,atk:4,def:0,evade:8,acc:0},D:{hp:12,atk:6,def:1,evade:9,acc:1},C:{hp:18,atk:8,def:2,evade:10,acc:2},B:{hp:26,atk:11,def:3,evade:11,acc:3},A:{hp:36,atk:14,def:5,evade:12,acc:4},S:{hp:50,atk:18,def:7,evade:14,acc:6}};
function rewardRange(value:unknown):[number,number]|null{const range=list<unknown>(value),min=Number(range[0]),max=Number(range[1]);return range.length===2&&Number.isFinite(min)&&Number.isFinite(max)&&max>=min?[min,max]:null;}
function questChance(quest:RuntimeRecord,state:RuntimeRecord){const check=record(quest.check);if(check.mode==='rate')return Math.max(0,Math.min(100,number(check.rate)));const sides=Math.max(1,Math.trunc(number(check.sides,20))),dc=Math.trunc(number(check.dc,10)),stat=string(check.stat),modifier=stat?number(record(state.player)[stat]??record(record(state.player).stats)[stat]):number(check.mod);let success=0;for(let roll=1;roll<=sides;roll++)if(roll+modifier>=dc)success++;return Math.round(success/sides*100);}
function management(schema:RuntimeRecord,state:RuntimeRecord){const gold=number(state.gold),facilityState=record(state.facilities),facilities=entities(schema,'facility').map(value=>{const id=string(value.id),level=number(facilityState[id],1),maxLevel=number(value.maxLevel),maxed=level>=maxLevel,cost=maxed?null:Number(record(value.upgradeCosts)[string(level+1)]),known=cost!==null&&Number.isFinite(cost),shortfall=known?Math.max(0,cost-gold):0;return{id,label:string(value.label||id),level,maxLevel,nextLevel:maxed?null:level+1,cost:known?cost:null,maxed,available:!maxed&&known&&shortfall===0,reason:maxed?'최대 레벨':!known?'증축 비용 정보 없음':shortfall?`${shortfall.toLocaleString('ko-KR')}원 부족`:''};}),npcNames=new Map(entities(schema,'npc').map(value=>[string(value.id),string(value.nameKo||value.nameEn||value.name||value.id)])),staff=list<RuntimeRecord>(state.staff).map(entry=>({...entry,name:npcNames.get(string(entry.npcId))||string(entry.npcId)})),capacity=staffing(schema,state),attempts=number(record(state.questAttempts).day)===number(state.day)?list<string>(record(state.questAttempts).ids):[],claimed=list<string>(state.claimedRewards),pending=record(state.pendingQuest),rewards=record(record(schema.rewards).gold),quests=activeQuests(schema,state).map(quest=>{const id=string(quest.id),done=!quest.repeatable&&claimed.includes(id),attemptedToday=attempts.includes(id),questPending=number(pending.day)===number(state.day)&&pending.questId===id,reward=rewardRange(rewards[string(quest.rewardTier)]),reason=done?'이미 완료':attemptedToday?'오늘 이미 시도함':questPending?'진행 중':'';return{id,name:string(quest.name||id),chance:questChance(quest,state),reward,done,attemptedToday,pending:questPending,available:!reason,reason};}),resources=list<RuntimeRecord>(schema.resources).filter(value=>value.id!=='gold'&&Number.isFinite(Number(value.basePrice))).map(value=>({id:string(value.id),label:string(value.label||value.id),unit:string(value.unit),basePrice:number(value.basePrice)}));return{gold,facilities,staff:{items:staff,capacity,count:staff.length,full:staff.length>=capacity,remaining:Math.max(0,capacity-staff.length),reason:staff.length>=capacity?'직원 숙소 증축 필요':''},quests,resources};}
export function rollQuestEncounter(schema:RuntimeRecord,state:RuntimeRecord,quest:RuntimeRecord):{encounter:RuntimeRecord;enemies:RuntimeRecord[]}|null{const chance=Number(quest.encounterChance||0),pool=list<RuntimeRecord>(record(schema.encounters).pool);if(!(chance>0)||!schema.combat||!pool.length)return null;const rng=deriveRng(state.seed??0,`questenc/${state.day}/${quest.id}`);if(rng.next()*100>=chance)return null;const target=Math.max(0,RANKS.indexOf(string(quest.rewardTier)));let picked=pool[0]!,distance=Infinity;for(const entry of pool){const index=RANKS.indexOf(string(entry.rank)),nextDistance=Math.abs((index<0?0:index)-target);if(nextDistance<distance){picked=entry;distance=nextDistance;}}const countRange=Array.isArray(picked.count)?picked.count:[1,1],count=rng.int(number(countRange[0],1),number(countRange[1],1)),rank=string(picked.rank),stats=QUEST_ENCOUNTER_STATS[rank]??QUEST_ENCOUNTER_STATS.E!;return{encounter:picked,enemies:Array.from({length:count},(_,index)=>({name:count>1?`${string(picked.name)} ${index+1}`:picked.name,rank:picked.rank,...stats}))};}

export function innModule():ModuleDefinition{return moduleDefinition('genre.inn',['core.stats','core.inventory'],['facilities','staff','rooms'],['gold','resources','npcs'],{
  upgrade:scoped((c)=>{if(inCombat(c.state))return fail(c,'in_combat');const id=string(c.params.facility||c.params.facilityId),definition=byId(c.schema,'facility',id);if(!definition)return fail(c,'unknown_facility',id);const facilities=record(c.state.facilities),current=number(facilities[id],1);if(current>=number(definition.maxLevel))return fail(c,'max_level',id);const level=current+1,cost=number(record(definition.upgradeCosts)[string(level)],Number.NaN);if(!Number.isFinite(cost))return fail(c,'no_upgrade_cost',id);if(number(c.state.gold)<cost)return fail(c,'insufficient_gold',id);c.state.gold=number(c.state.gold)-cost;facilities[id]=level;c.state.facilities=facilities;return ok(c,{facility:id,level,goldDelta:-cost});}),
  hire:scoped((c)=>{const id=string(c.params.npcId),wage=Math.trunc(number(c.params.dailyWage));if(!byId(c.schema,'npc',id))return fail(c,'unknown_npc',id);if(wage<0)return fail(c,'invalid_wage',wage);const staff=list<RuntimeRecord>(c.state.staff);if(staff.some((entry)=>entry.npcId===id))return fail(c,'already_hired',id);if(staff.length>=staffing(c.schema,c.state))return fail(c,'staff_full',id);c.state.staff=[...staff,{npcId:id,dailyWage:wage}];return ok(c,{npcId:id,dailyWage:wage});}),
  set_wage:scoped((c)=>{const id=string(c.params.npcId),wage=Math.trunc(number(c.params.dailyWage));if(wage<0)return fail(c,'invalid_wage',wage);const staff=list<RuntimeRecord>(c.state.staff),entry=staff.find((value)=>value.npcId===id);if(!entry)return fail(c,'not_hired',id);const before=number(entry.dailyWage);entry.dailyWage=wage;c.state.staff=staff;return ok(c,{npcId:id,before,dailyWage:wage});}),
  fire:scoped((c)=>{const id=string(c.params.npcId),staff=list<RuntimeRecord>(c.state.staff);if(!staff.some((entry)=>entry.npcId===id))return fail(c,'not_hired',id);c.state.staff=staff.filter((entry)=>entry.npcId!==id);return ok(c,{npcId:id});}),
  set_outfit:scoped((c)=>{const id=string(c.params.npcId),outfit=Math.trunc(number(c.params.outfit));if(!safeKey(id)||!Object.prototype.hasOwnProperty.call(record(c.state.npcs),id))return fail(c,'unknown_target',id);if(outfit<0||outfit>9)return fail(c,'invalid_outfit',c.params.outfit);const npcs=record(c.state.npcs),npc=record(npcs[id]),before=npc.outfit;npc.outfit=outfit;npcs[id]=npc;c.state.npcs=npcs;return ok(c,{npcId:id,before,outfit});}),
  checkin:scoped((c)=>{const no=string(c.params.roomNo),definition=room(c.schema,no),guestName=string(c.params.guestName),stayDays=Math.trunc(number(c.params.stayDays,1));if(!definition||!safeKey(no))return fail(c,'unknown_room',no);if(!guestName)return fail(c,'missing_guestName');if(stayDays<=0)return fail(c,'invalid_stayDays',stayDays);if(number(definition.requiresRoomLevel,1)>number(record(c.state.facilities).room,1))return fail(c,'room_locked',no);const rooms=record(c.state.rooms),guests=list<RuntimeRecord>(own(rooms,no));if(definition.capacity!=null&&guests.length>=number(definition.capacity))return fail(c,'room_full',no);const price=number(definition.pricePerNight)*stayDays;rooms[no]=[...guests,{guestName,nightsLeft:stayDays}];c.state.rooms=rooms;c.state.gold=number(c.state.gold)+price;return ok(c,{roomNo:no,guestName,stayDays,goldDelta:price});}),
  checkout:scoped((c)=>{const no=string(c.params.roomNo),guestName=string(c.params.guestName),rooms=record(c.state.rooms),guests=list<RuntimeRecord>(own(rooms,no)),index=guests.findIndex((entry)=>entry.guestName===guestName);if(index<0)return fail(c,'guest_not_found',`${no}:${guestName}`);const remaining=guests.filter((_,i)=>i!==index);if(remaining.length)rooms[no]=remaining;else delete rooms[no];c.state.rooms=rooms;return ok(c,{roomNo:no,guestName});}),
  sale:scoped((c)=>{if(inCombat(c.state))return fail(c,'in_combat');const item=menu(c.schema,c.params.menuName),qty=Math.trunc(number(c.params.qty,1));if(!item)return fail(c,'unknown_menu',c.params.menuName);if(item.trade==='buy')return fail(c,'menu_not_sellable',c.params.menuName);if(qty<=0||qty>999)return fail(c,'invalid_qty',qty);if(number(item.requiresKitchenLevel,1)>number(record(c.state.facilities).kitchen,1))return fail(c,'menu_locked',c.params.menuName);const consumes=consumption(item,c.state);if(!Object.keys(consumes).length)return fail(c,'missing_consumption_rule',c.params.menuName);const resources=record(c.state.resources);for(const[id,amount]of Object.entries(consumes))if(number(resources[id])<number(amount)*qty)return fail(c,'insufficient_stock',id);const consumed:RuntimeRecord={};for(const[id,amount]of Object.entries(consumes)){const used=number(amount)*qty;resources[id]=number(resources[id])-used;consumed[id]=used;}const goldDelta=number(item.price)*qty;c.state.resources=resources;c.state.gold=number(c.state.gold)+goldDelta;return ok(c,{menuName:item.name,qty,goldDelta,consumed});}),
  // 옛 buy_item 파리티 복원(마이그레이션 감사 Major: 유실됨) — 식음료/소지품을 골드로 구매해 state.items에 적재.
  buy_item:scoped((c)=>{if(inCombat(c.state))return fail(c,'in_combat');if(Object.keys(record(c.params)).some((key)=>key!=='menuName'&&key!=='qty'))return fail(c,'item_number_not_allowed');const item=menu(c.schema,c.params.menuName);if(!item)return fail(c,'unknown_menu',c.params.menuName);if(item.trade!=='buy')return fail(c,'menu_not_buyable',c.params.menuName);const qty=Math.trunc(number(c.params.qty,1));if(qty<=0||qty>999)return fail(c,'invalid_qty',qty);const cost=number(item.price)*qty;if(number(c.state.gold)<cost)return fail(c,'insufficient_gold',c.params.menuName);const name=string(item.name);if(!safeKey(name))return fail(c,'unknown_menu',c.params.menuName);const items=record(c.state.items);c.state.gold=number(c.state.gold)-cost;items[name]=(Object.prototype.hasOwnProperty.call(items,name)?number(items[name]):0)+qty;c.state.items=items;return ok(c,{menuName:name,qty,goldDelta:-cost,owned:number(items[name])});}),
  gold_delta:scoped((c)=>{const amount=Math.trunc(number(c.params.amount)),before=number(c.state.gold);c.state.gold=Math.max(0,before+amount);return ok(c,{amount,before,after:c.state.gold,reason:string(c.params.reason)});}),
  reward:scoped((c)=>{const questId=string(c.params.questId),tier=string(c.params.tier),claimed=list<string>(c.state.claimedRewards),range=list<unknown>(record(record(c.schema.rewards).gold)[tier]);if(!questId)return fail(c,'missing_questId');if(claimed.includes(questId))return fail(c,'already_claimed',questId);if(range.length!==2)return fail(c,'unknown_reward_tier',tier);if('amount'in c.params||'goldDelta'in c.params)return fail(c,'reward_amount_not_allowed');const amount=c.rng.int(number(range[0]),number(range[1])),before=number(c.state.gold);c.state.gold=before+amount;c.state.claimedRewards=[...claimed,questId];return ok(c,{questId,tier,goldDelta:amount,before,after:c.state.gold,reason:string(c.params.reason)});}),
  attempt_quest:scoped((c)=>{if(['amount','gold','goldDelta','roll','tier'].some((key)=>key in c.params))return fail(c,'quest_number_not_allowed');if(inCombat(c.state))return fail(c,'in_combat');const id=string(c.params.questId),quest=activeQuests(c.schema,c.state).find((value)=>value.id===id);if(!quest)return fail(c,'unknown_quest',id);const rewardTier=string(quest.rewardTier),range=rewardRange(record(record(c.schema.rewards).gold)[rewardTier]);if(!range)return fail(c,'unknown_reward_tier',rewardTier);const pending=record(c.state.pendingQuest);if(Object.keys(pending).length&&pending.day!==c.state.day)delete c.state.pendingQuest;if(record(c.state.pendingQuest).questId===id&&record(c.state.pendingQuest).cleared){delete c.state.pendingQuest;}else{const encounter=rollQuestEncounter(c.schema,c.state,quest);if(encounter){const started=c.registry.dispatch(c.schema,c.state,{id:'start_encounter',params:{enemies:encounter.enemies}},c.rng);if(!started.log[0]?.ok)return started;c.state=started.state;record(c.state.combat).questId=id;c.state.pendingQuest={questId:id,day:c.state.day};return ok(c,{questId:id,name:quest.name??id,encounter:encounter.encounter.id,enemies:started.log[0].enemies,text:`${string(quest.name??id)} 수행 중 ${string(encounter.encounter.name)} 조우!`});}}const attempts=number(record(c.state.questAttempts).day)===number(c.state.day)?record(c.state.questAttempts):{day:c.state.day,ids:[]},ids=list<string>(attempts.ids);if(ids.includes(id))return fail(c,'already_attempted_today',id);ids.push(id);attempts.ids=ids;c.state.questAttempts=attempts;const check=record(quest.check),mode=check.mode==='rate'?'rate':'dc',roll=c.rng.int(1,mode==='rate'?100:number(check.sides,20)),modifier=check.stat?number(record(c.state.player)[string(check.stat)]??record(record(c.state.player).stats)[string(check.stat)]):number(check.mod),success=mode==='rate'?roll<=number(check.rate,50):roll+modifier>=number(check.dc,10),tier=success?(roll===(mode==='rate'?1:number(check.sides,20))?'critical_success':'success'):(roll===1?'critical_failure':'failure');if(!success)return ok(c,{questId:id,name:quest.name??id,roll,tier,success:false});const goldDelta=c.rng.int(range[0],range[1]);c.state.gold=number(c.state.gold)+goldDelta;if(!quest.repeatable)c.state.claimedRewards=[...list<string>(c.state.claimedRewards),id];return ok(c,{questId:id,name:quest.name??id,roll,tier,success:true,goldDelta,claimed:!quest.repeatable});})
},{
  'inn/staff-capacity':(...args)=>staffing(record(args[0]),record(args[1])),
  'inn/management':(...args)=>management(record(args[0]),record(args[1])),
  'inn/rooms':(...args)=>{const schema=record(args[0]),state=record(args[1]),level=number(record(state.facilities).room,1),occupied=record(state.rooms);return entities(schema,'room').map((value)=>({...value,locked:number(value.requiresRoomLevel,1)>level,guests:list(occupied[string(value.no)])}));},
  'inn/quests':(...args)=>activeQuests(record(args[0]),record(args[1]))
});}
