import type { CompiledPrompt,PromptBlock,PromptCompileInput,PromptRole,PromptTraceRow } from './contracts.ts';
const tokens=(text:string)=>Math.ceil(text.length/4);
function macro(text:unknown,input:PromptCompileInput,path:string,warnings:CompiledPrompt['warnings']){const vars:Record<string,string>={user:input.persona?.name??'User',char:input.card.name,persona:input.persona?.prompt??'',...Object.fromEntries(Object.entries(input.variables??{}).map(([key,value])=>[key,String(value)]))};return String(text??'').replace(/\{\{\s*([^{}]+?)\s*\}\}/g,(original,key:string)=>{const name=key.trim();if(name==='original'||name==='slot')return original;if(Object.prototype.hasOwnProperty.call(vars,name))return vars[name]??'';warnings.push({code:'unsupported_macro',path,detail:name});return original;});}
function inner(block:PromptBlock,content:string,input:PromptCompileInput,path:string,warnings:CompiledPrompt['warnings']){return'innerFormat'in block&&block.innerFormat?macro(block.innerFormat,input,path,warnings).replace('{{slot}}',content):content;}
export function compilePrompt(input:PromptCompileInput):CompiledPrompt{if(!input?.preset||!Array.isArray(input.preset.blocks))throw new TypeError('compilePrompt requires a normalized preset');const messages:CompiledPrompt['messages']=[],trace:PromptTraceRow[]=[],warnings:CompiledPrompt['warnings']=[],chat=input.chat??[],notes:Array<{message:{role:PromptRole;content:string};depth:number;trace:PromptTraceRow}>=[];let chatStart=-1;
 const inactive=(block:PromptBlock,index:number,reason:string,path=`preset.blocks[${index}]`)=>trace.push({blockId:block.id,blockType:block.type,sourcePath:path,role:'none',active:false,reason,chars:0,tokensEstimate:0});
 const emit=(block:PromptBlock,role:PromptRole,content:string,path:string,extra:Partial<PromptTraceRow>={})=>{trace.push({blockId:block.id,blockType:block.type,sourcePath:path,role,active:true,reason:'ok',chars:content.length,tokensEstimate:tokens(content),...extra});messages.push({role,content});};
 input.preset.blocks.forEach((block,index)=>{const path=`preset.blocks[${index}]`;if(!block.enabled)return inactive(block,index,'disabled');const role:'role' extends keyof typeof block?never:PromptRole=('role'in block&&block.role!=='all'?block.role:'system') as PromptRole;let content='';let source=path;
  if(block.type==='plain'||block.type==='jailbreak'){content=block.text;if(block.slot==='main'&&input.card.systemPrompt){content=input.card.systemPrompt.replaceAll('{{original}}',content);source=`card.systemPrompt+${path}`;}if(block.slot==='globalNote'&&input.card.postHistoryInstructions){content=input.card.postHistoryInstructions.replaceAll('{{original}}',content);source=`card.postHistoryInstructions+${path}`;}}
  else if(block.type==='description'){content=input.card.description??'';if(input.card.personality)content+=`\n\nDescription of {{char}}: ${input.card.personality}`;if(input.card.scenario)content+=`\n\nCircumstances and context of the dialogue: ${input.card.scenario}`;source='card.description';}
  else if(block.type==='persona'){content=input.persona?.prompt??'';source='input.persona.prompt';}
  else if(block.type==='lorebook'){content=(input.lore?.entries??[]).map((entry)=>entry.content).filter(Boolean).join('\n\n');source='input.lore.entries';}
  else if(block.type==='memory'){content=input.memory??'';source='input.memory';}
  else if(block.type==='engineFacts'||block.type==='availableActions'||block.type==='groundedMemory'){const key=block.type==='engineFacts'?'facts':block.type==='availableActions'?'availableActions':'groundedMemory';content=input.engineContext?.[key]??'';source=`engineContext.${key}`;}
  else if(block.type==='authornote'){content=input.authorNote?.content??'';source='input.authorNote';const final=inner(block,macro(content,input,source,warnings),input,path,warnings);if(!final.trim())return inactive(block,index,'empty',source);const row={blockId:block.id,blockType:block.type,sourcePath:source,role,active:true,reason:'ok',chars:final.length,tokensEstimate:tokens(final),insertedAt:`chat[-${Math.max(0,input.authorNote?.depth??0)}]`};notes.push({message:{role,content:final},depth:Math.max(0,input.authorNote?.depth??0),trace:row});trace.push(row);return;}
  else if(block.type==='chat'){let start=block.rangeStart,end=block.rangeEnd==='end'?chat.length:block.rangeEnd;if(start===-1000){start=0;end=chat.length;}if(start<0)start=Math.max(0,chat.length+start);if(end<0)end=Math.max(0,chat.length+end);const slice=chat.slice(start,end);if(!slice.length)return inactive(block,index,chat.length?'empty_range':'empty','input.chat');chatStart=messages.length;for(const [offset,message]of slice.entries()){let body=macro(message.content,input,`input.chat[${start+offset}]`,warnings),messageRole:PromptRole=message.role;if(input.preset.settings.sendChatAsSystem){body=`${message.role}: ${body}`;messageRole='system';}emit(block,messageRole,body,`input.chat[${start+offset}]`);}return;}
  else return inactive(block,index,block.type==='cache'?'unsupported':'empty');content=inner(block,macro(content,input,source,warnings),input,path,warnings);if(!content.trim())return inactive(block,index,'empty',source);emit(block,role,content,source);
 });
 if(notes.length){for(const [offset,note]of notes.entries()){const position=chatStart<0?messages.length:Math.max(chatStart,messages.length-note.depth);messages.splice(position+offset,0,note.message);}}
 let final=messages;if(input.options?.mergeConsecutiveRoles){final=[];for(const message of messages){const previous=final.at(-1);if(previous?.role===message.role)previous.content+=`\n\n${message.content}`;else final.push({...message});}}
 return{messages:final,assistantPrefill:macro(input.preset.settings.assistantPrefill,input,'preset.settings.assistantPrefill',warnings),trace,warnings};}
