'use strict';

function cloneProject(project) { return { manifest: JSON.parse(JSON.stringify(project.manifest)), files: Object.fromEntries(Object.entries(project.files || {}).map(([key, value]) => [key, Uint8Array.from(value)])) }; }
function editProject(project, edit) { const next = cloneProject(project); edit(next.manifest); next.manifest.revision = Number(next.manifest.revision || 0) + 1; return next; }
function setBasics(project, values) { return editProject(project, (manifest) => { manifest.title = String(values.title || manifest.title); const character = manifest.content.characters[0] || (manifest.content.characters[0] = { id: 'character', name: '' }); character.name = String(values.name ?? character.name ?? ''); character.description = String(values.description ?? character.description ?? ''); }); }
function setInitialState(project, value) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('initial_state_object_required'); return editProject(project, (manifest) => { manifest.runtime.schema = manifest.runtime.schema || {}; manifest.runtime.schema.initialState = JSON.parse(JSON.stringify(value)); manifest.runtime.initialState = JSON.parse(JSON.stringify(value)); }); }
function setModuleEnabled(project, id, enabled) { return editProject(project, (manifest) => { const module = manifest.modules.installed.find((item) => item.id === id); if (module) module.enabled = !!enabled; else manifest.modules.installed.push({ id, version: '1.0.0', enabled: !!enabled }); }); }
function setScreenPreset(project, preset) { const value = SCREEN_PRESETS[preset]; if (!value) throw new Error('unknown_screen_preset'); return editProject(project, (manifest) => { manifest.runtime.screens = JSON.parse(JSON.stringify(value.screens)); manifest.runtime.navigation = JSON.parse(JSON.stringify(value.navigation)); }); }
function updateLoreEntries(project, updates) { return editProject(project, (manifest) => { const book = manifest.content.lorebooks[0] || (manifest.content.lorebooks[0] = { entries: [] }); const byId = new Map((updates || []).map((item) => [String(item.id), item])); book.entries = (book.entries || []).map((entry, index) => { const update = byId.get(String(entry.id ?? index)); return update ? { ...entry, keys: String(update.keys || '').split(',').map((key) => key.trim()).filter(Boolean), content: String(update.content ?? entry.content ?? ''), enabled: update.enabled !== false } : entry; }); }); }
function validateEditorProject(project) { const issues = []; const manifest = project && project.manifest; if (!manifest) return [{ path: '$', reason: 'project_missing' }]; if (!manifest.title.trim()) issues.push({ path: 'title', reason: 'required' }); if (!manifest.runtime.schema) issues.push({ path: 'runtime.schema', reason: 'required' }); const ids = new Set(); for (const screen of manifest.runtime.screens || []) { if (!screen.id || ids.has(screen.id)) issues.push({ path: 'runtime.screens', reason: 'screen_id_invalid' }); ids.add(screen.id); } return issues; }

const SCREEN_PRESETS = {
  chat: { screens: [{ id: 'play', title: '대화', layout: 'stage-chat-hud', presentation: 'page', regions: { main: [{ widget: 'chat' }], side: [{ widget: 'sidebar' }] } }], navigation: [{ id: 'play', screenId: 'play', label: '대화' }] },
  adventure: { screens: [{ id: 'field', title: '현장', layout: 'stage-chat-hud', presentation: 'page', regions: { hud: [{ widget: 'stat-strip', source: 'core.summary' }], main: [{ widget: 'chat' }], side: [{ widget: 'map-nodes', source: 'location.map' }] } }, { id: 'party', title: '파티', layout: 'dashboard', presentation: 'page', regions: { main: [{ widget: 'detail-panel', source: 'party.formation' }] } }], navigation: [{ id: 'field', screenId: 'field', label: '현장' }, { id: 'party', screenId: 'party', label: '파티' }] },
  management: { screens: [{ id: 'management', title: '경영', layout: 'dashboard', presentation: 'page', regions: { hud: [{ widget: 'stat-strip', source: 'core.summary' }], main: [{ widget: 'facility-grid', source: 'core.facilities' }], side: [{ widget: 'inventory-grid', source: 'core.resources' }] } }], navigation: [{ id: 'management', screenId: 'management', label: '경영' }] },
};

module.exports = { SCREEN_PRESETS, cloneProject, setBasics, setInitialState, setModuleEnabled, setScreenPreset, updateLoreEntries, validateEditorProject };
