import{expect,test}from'@playwright/test';
import{zipSync}from'fflate';

function card(){return Buffer.from(JSON.stringify({spec:'chara_card_v3',spec_version:'3.0',data:{name:'모듈 카드',description:'분할 에셋 테스트',first_mes:'세 모듈 {{img::asset_one}} {{img::asset_two}} {{img::asset_three}}',mes_example:'',personality:'',scenario:'',creator_notes:'',system_prompt:'',post_history_instructions:'',alternate_greetings:[],tags:[],creator:'test',character_version:'1',extensions:{},group_only_greetings:[],character_book:{entries:[]},assets:[]}}));}
function moduleFile(number:number){return{name:`sprites-${number}.charx`,mimeType:'application/zip',buffer:Buffer.from(zipSync({[`assets/other/image/asset_${['one','two','three'][number-1]}.webp`]:Uint8Array.of(82,73,70,70,4,0,0,0,87,69,66,80,number)}))};}

test('에셋 탭에서 여러 모듈을 한 번에 연결하고 재시작 뒤 모두 복원한다',async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'카드 가져오기',exact:true})).toBeVisible();await page.locator('input[accept=".simpack,.charx,.png,.json"]').setInputFiles({name:'module-card.json',mimeType:'application/json',buffer:card()});const side=page.getByRole('complementary');await side.getByTitle('에셋').click();await page.locator('input[accept=".charx,.zip"]').setInputFiles([moduleFile(1),moduleFile(2),moduleFile(3)]);await expect(side.locator('.modules article')).toHaveCount(3);for(let number=1;number<=3;number+=1)await expect(side.locator('.modules')).toContainText(`sprites-${number}.charx`);await expect(page.locator('.message .text img')).toHaveCount(3);for(const image of await page.locator('.message .text img').all())await expect(image).toHaveAttribute('src',/^blob:/);await page.reload();await side.getByTitle('에셋').click();await expect(side.locator('.modules article')).toHaveCount(3);await expect(page.locator('.message .text img')).toHaveCount(3);});

test('카드와 세 에셋 모듈을 가져오기 한 번으로 함께 연결한다',async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'카드 가져오기',exact:true})).toBeVisible();await page.locator('input[accept=".simpack,.charx,.png,.json"]').setInputFiles([moduleFile(2),{name:'module-card.json',mimeType:'application/json',buffer:card()},moduleFile(1),moduleFile(3)]);const side=page.getByRole('complementary');await side.getByTitle('에셋').click();await expect(side.locator('.modules article')).toHaveCount(3);await expect(page.locator('.message .text img')).toHaveCount(3);});
