import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';
import{effectDisposition,KNOWN_TRIGGER_EFFECTS,prepareRuntimeEffects}from'../src/security/effect-policy.ts';
import{executeRuntimeRequest}from'../src/worker/execute.ts';

describe('trigger effect disposition policy',()=>{
 it('covers every effect type declared by the upstream port',()=>{const source=readFileSync(new URL('../src/port/triggers.ts',import.meta.url),'utf8').split('export async function runTrigger')[0]!,ignored=new Set(['start','manual','output','input','display','request','var','value','exists','chatindex','character','user','char','model','submodel','fail']),declared=[...source.matchAll(/\btype:\s*'([^']+)'/g)].map(match=>match[1]!).filter(type=>!ignored.has(type));expect([...new Set(declared)].filter(type=>!KNOWN_TRIGGER_EFFECTS.includes(type as never))).toEqual([]);expect(KNOWN_TRIGGER_EFFECTS.every(type=>['apply','block','approval'].includes(effectDisposition(type)))).toBe(true);});
 it('defaults unknown effects to block instead of silently accepting them',()=>{expect(effectDisposition('futureDangerousEffect')).toBe('block');const prepared=prepareRuntimeEffects({mode:'output',triggers:[{type:'output',effect:[{type:'futureDangerousEffect'}]}]});expect(prepared.effects).toEqual([{type:'futureDangerousEffect',disposition:'block',payload:{reason:'runtime_effect_unknown'}}]);expect(prepared.warnings[0]?.code).toBe('runtime_effect_blocked');});
 it('blocks a dangerous effect without killing the safe effect after it',async()=>{const response=await executeRuntimeRequest({type:'trigger',requestId:'policy-1',snapshot:{sessionId:'chat',cardId:'card',revision:'r1',variables:{},randomState:1,logicalTimeMs:1_700_000_000_000},input:{mode:'output',triggers:[{type:'output',conditions:[],effect:[{type:'command',value:'/danger'},{type:'setvar',operator:'=',var:'after',value:'ok'}]}]}});expect(response).toMatchObject({ok:true,patch:[{op:'set',key:'after',value:'ok'}],effects:[{type:'command',disposition:'block'}],warnings:[{code:'runtime_effect_blocked',effect:'command'}]});});
 it('returns approval-required mutations as explicit effects and does not execute them',async()=>{const response=await executeRuntimeRequest({type:'trigger',requestId:'policy-2',snapshot:{sessionId:'chat',cardId:'card',revision:'r1',variables:{},randomState:1,logicalTimeMs:1_700_000_000_000},input:{mode:'output',messages:[{role:'user',data:'original'}],triggers:[{type:'output',conditions:[],effect:[{type:'modifychat',index:'0',value:'changed'}]}]}});expect(response).toMatchObject({ok:true,patch:[],effects:[{type:'modifychat',disposition:'approval'}],warnings:[{code:'runtime_effect_approval',effect:'modifychat'}]});});
});
