import{describe,expect,it}from'vitest';import{activateLore,applyRegexPipeline,normalizeLoreEntries,resolveModules}from'../src/index.ts';
describe('safe Risu content compatibility',()=>{it('activates constant and selective lore in deterministic order',()=>{const entries=normalizeLoreEntries([{id:'b',content:'B',key:'inn',order:2},{id:'a',content:'A',constant:true,order:1},{id:'c',content:'C',key:'silvia',secondkey:'wage',selective:true,order:3}]);expect(activateLore(entries,[{content:'silvia discusses wage at the inn'}]).entries.map((value)=>value.id)).toEqual(['a','b','c']);});it('runs safe regex stages and rejects nested quantifiers',()=>{const result=applyRegexPipeline('hello foo',[{id:'ok',stage:'editoutput',pattern:'foo',replacement:'bar',flags:'g',enabled:true},{id:'bad',stage:'editoutput',pattern:'(a+)+',replacement:'x',flags:'g',enabled:true}],'editoutput');expect(result).toEqual({text:'hello bar',warnings:[{id:'bad',reason:'unsafe_pattern'}]});});it('uses later module scopes and blocks executable capabilities',()=>{const result=resolveModules([[{id:'a',namespace:'n',scope:'global',capabilities:['lore'],enabled:true}],[{id:'b',namespace:'n',scope:'character',capabilities:['regex'],enabled:true},{id:'x',namespace:'x',scope:'chat',capabilities:['lua'],enabled:true}]]);expect(result.modules.map((value)=>value.id)).toEqual(['b']);expect(result.blocked.map((value)=>value.id)).toEqual(['x']);});});

describe('advanced Risu lore parity',()=>{
  it('preserves probability and case-sensitive activation',()=>{const entries=normalizeLoreEntries([{id:'case',keys:['Hero'],content:'case',case_sensitive:true,probability:100},{id:'never',keys:['hero'],content:'never',probability:0}]);expect(activateLore(entries,[{content:'hero'}],{seed:7,turn:1}).entries).toEqual([]);expect(activateLore(entries,[{content:'Hero'}],{seed:7,turn:1}).entries.map(entry=>entry.id)).toEqual(['case']);});
  it('recursively activates lore from an already active lore body',()=>{const entries=normalizeLoreEntries([{id:'a',keys:['용'],content:'숨은 키는 여의주',recursive:true,order:0},{id:'b',keys:['여의주'],content:'두 번째 지식',order:1}]),result=activateLore(entries,[{content:'용이 나타났다'}],{seed:1,turn:2});expect(result.entries.map(entry=>entry.id)).toEqual(['a','b']);expect(result.matched.map(item=>item.activationPass)).toEqual([0,1]);});
  it('lets a later source replace the same namespace and identity deterministically',()=>{const entries=normalizeLoreEntries([{id:'same',content:'old',constant:true,_luckySourceScope:'global',_luckySourceNamespace:'weather',_luckySourceRank:0},{id:'same',content:'new',constant:true,_luckySourceScope:'module',_luckySourceNamespace:'weather',_luckySourceRank:4}]);expect(entries).toHaveLength(1);expect(entries[0]).toMatchObject({content:'new',sourceScope:'module'});});
  it('keeps folder definitions out of the prompt activation set',()=>{const entries=normalizeLoreEntries([{id:'folder',mode:'folder',content:'폴더 설명',alwaysActive:true},{id:'entry',key:'열쇠',content:'실제 지식',folder:'folder'}]);expect(activateLore(entries,[{content:'열쇠'}]).entries.map(entry=>entry.id)).toEqual(['entry']);});
});
