import{describe,expect,it,vi}from'vitest';
import{getCbsPortEnv}from'../src/port/parser.ts';
import{triggerPortEnv}from'../src/port/trigger-env.ts';
import{runCardTriggers}from'../src/trigger-runtime.ts';
import{RisuRuntimeWorkerClient,type RuntimeWorkerPort}from'../src/worker/client.ts';
import{executeRuntimeRequest}from'../src/worker/execute.ts';
import type{RuntimeWorkerMessage,RuntimeWorkerRequest,RuntimeWorkerResponse,RuntimeWorkerTriggerRequest}from'../src/worker/contract.ts';

const request=(requestId='r1'):RuntimeWorkerTriggerRequest=>({type:'trigger',requestId,snapshot:{sessionId:'chat-a',cardId:'card-a',revision:'rev-a',variables:{count:'1'},randomState:123,logicalTimeMs:1_700_000_000_000,stateOwnership:'card'},input:{mode:'output',triggers:[{type:'output',conditions:[],effect:[{type:'setvar',operator:'+=',var:'count',value:'2'}]}]}});
class FakeWorker implements RuntimeWorkerPort{onmessage:((event:{data:RuntimeWorkerMessage})=>void)|null=null;onerror:null=null;posted:RuntimeWorkerRequest[]=[];terminated=0;postMessage(value:RuntimeWorkerRequest){this.posted.push(value);}terminate(){this.terminated+=1;}respond(value:RuntimeWorkerResponse){this.onmessage?.({data:value});}}

describe('card runtime worker boundary',()=>{
 it('returns a patch instead of mutating the supplied snapshot',async()=>{const input=request(),response=await executeRuntimeRequest(input);expect(input.snapshot.variables).toEqual({count:'1'});expect(response).toMatchObject({ok:true,requestId:'r1',baseRevision:'rev-a',patch:[{op:'set',key:'count',value:'3'}]});});
 it('restores the scoped upstream environments after every run',async()=>{const cbs=getCbsPortEnv(),trigger=triggerPortEnv();await runCardTriggers({...request().input,variables:{}});expect(getCbsPortEnv()).toBe(cbs);expect(triggerPortEnv()).toBe(trigger);});
 it('terminates a timed-out worker and rejects every partial result',async()=>{vi.useFakeTimers();const worker=new FakeWorker(),warnings:string[]=[];const client=new RisuRuntimeWorkerClient(()=>worker,{hardTimeoutMs:50,onWarning:value=>warnings.push(value.code)}),pending=client.execute(request()),rejected=expect(pending).rejects.toThrow('runtime_timeout');await vi.advanceTimersByTimeAsync(51);await rejected;expect(worker.terminated).toBe(1);expect(warnings).toContain('runtime_timeout');vi.useRealTimers();});
 it('discards and reports a response that arrives after a session switch',async()=>{const worker=new FakeWorker(),warnings:string[]=[];const client=new RisuRuntimeWorkerClient(()=>worker,{onWarning:value=>warnings.push(value.code)}),pending=client.execute(request()),rejected=expect(pending).rejects.toThrow('session_changed');client.dispose('session_changed');await rejected;worker.respond({type:'result',ok:false,requestId:'r1',sessionId:'chat-a',cardId:'card-a',baseRevision:'rev-a',error:'late',warnings:[],durationMs:1});expect(worker.terminated).toBe(1);expect(warnings).toEqual(expect.arrayContaining(['runtime_disposed','runtime_stale_response']));});
 it('rejects oversized input before a Worker or structured clone is created',async()=>{let created=0;const warnings:string[]=[],client=new RisuRuntimeWorkerClient(()=>{created+=1;return new FakeWorker();},{onWarning:value=>warnings.push(value.code)}),huge=request();huge.input.triggers=[{type:'output',conditions:[],effect:Array.from({length:20_001},()=>({type:'setvar'}))}];await expect(client.execute(huge)).rejects.toThrow('runtime_budget_exceeded:effects');expect(created).toBe(0);expect(warnings).toEqual(['runtime_budget_rejected']);});
 it('replays random and clock-dependent card code identically from the same snapshot',async()=>{const input=request();input.input.triggers=[{type:'output',conditions:[],effect:[{type:'v2Random',min:'1',minType:'value',max:'1000000',maxType:'value',outputVar:'roll',indent:0},{type:'setvar',operator:'=',var:'clock',value:'{{unixtime}}'}]}];const first=await executeRuntimeRequest(input),second=await executeRuntimeRequest(structuredClone(input));expect(first).toMatchObject({ok:true,logicalTimeMs:1_700_000_001_000,patch:[{op:'set',key:'roll'},{op:'set',key:'clock',value:'1700000000'}]});expect(second).toMatchObject({patch:first.ok?first.patch:[],randomState:first.ok?first.randomState:0,logicalTimeMs:first.ok?first.logicalTimeMs:0});});
 it('keeps compatibility variables writable but makes full-sim variables read-only',async()=>{const compatible=request('compat'),simulation=request('sim');simulation.snapshot.stateOwnership='engine';const first=await executeRuntimeRequest(compatible),second=await executeRuntimeRequest(simulation);expect(first).toMatchObject({ok:true,patch:[{op:'set',key:'count',value:'3'}]});expect(second).toMatchObject({ok:true,patch:[],warnings:[{code:'runtime_state_write_blocked',actual:1,limit:0}]});});
 it('keeps Lua off by default and only returns variable patches when explicitly enabled',async()=>{const snapshot=request().snapshot,disabled=await executeRuntimeRequest({type:'lua',requestId:'lua-off',snapshot,code:'setChatVar("id", "count", "99")'}),enabled=await executeRuntimeRequest({type:'lua',requestId:'lua-on',snapshot,code:'setChatVar("id", "count", tonumber(getChatVar("id", "count")) + 4)',capabilities:{lua:true}});expect(disabled).toMatchObject({ok:true,patch:[],randomState:snapshot.randomState,logicalTimeMs:snapshot.logicalTimeMs,warnings:[{code:'runtime_lua_disabled'}]});expect(enabled).toMatchObject({ok:true,patch:[{op:'set',key:'count',value:'5'}],randomState:snapshot.randomState,logicalTimeMs:snapshot.logicalTimeMs});});
 it('rejects denied Lua capabilities and discards writes made before the attempt',async()=>{const response=await executeRuntimeRequest({type:'lua',requestId:'lua-denied',snapshot:request().snapshot,code:'setvar("count", "9"); request("id", "https://example.com")',capabilities:{lua:true}});expect(response).toMatchObject({ok:true,patch:[],warnings:[{code:'runtime_lua_capability_blocked',effect:'request'}]});});
 it('stops Lua at the instruction budget without changing session variables',async()=>{const response=await executeRuntimeRequest({type:'lua',requestId:'lua-loop',snapshot:request().snapshot,code:'while true do end',capabilities:{lua:true}});expect(response).toMatchObject({ok:true,patch:[],warnings:[{code:'runtime_lua_instruction_limit'}]});});
 it('uses the same engine-owned write barrier for Lua',async()=>{const snapshot=request().snapshot;snapshot.stateOwnership='engine';const response=await executeRuntimeRequest({type:'lua',requestId:'lua-engine-owned',snapshot,code:'setvar("count", "8")',capabilities:{lua:true}});expect(response).toMatchObject({ok:true,patch:[],warnings:[{code:'runtime_state_write_blocked',actual:1,limit:0}]});});
});
