import{RUNTIME_LIMITS,validateRuntimeRequest,validateRuntimeResponse}from'../security/runtime-budget.ts';
import type{RuntimeClientWarning,RuntimeWorkerMessage,RuntimeWorkerRequest,RuntimeWorkerResponse}from'./contract.ts';

export interface RuntimeWorkerPort{postMessage(value:RuntimeWorkerRequest):void;terminate():void;onmessage:((event:{data:RuntimeWorkerMessage})=>void)|null;onerror:((event:{message?:string})=>void)|null}
export interface RuntimeClientOptions{hardTimeoutMs?:number;luaStartupTimeoutMs?:number;onWarning?:(warning:RuntimeClientWarning)=>void}
type Pending={resolve:(value:RuntimeWorkerResponse)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>;requestType:RuntimeWorkerRequest['type']};
export class RisuRuntimeWorkerClient{
 #worker:RuntimeWorkerPort|null=null;#pending=new Map<string,Pending>();#disposed=false;#hardTimeoutMs:number;#luaStartupTimeoutMs:number;#onWarning:(warning:RuntimeClientWarning)=>void;
 constructor(private readonly factory:()=>RuntimeWorkerPort,options:RuntimeClientOptions={}){this.#hardTimeoutMs=options.hardTimeoutMs??RUNTIME_LIMITS.hardMs;this.#luaStartupTimeoutMs=options.luaStartupTimeoutMs??10_000;this.#onWarning=options.onWarning??(()=>{});}
 #ensure(){if(this.#disposed)throw new Error('runtime_client_disposed');if(this.#worker)return this.#worker;const worker=this.factory();worker.onmessage=event=>this.#receive(event.data);worker.onerror=event=>this.#onWarning({code:'runtime_worker_error',requestId:'(worker)',message:event.message??'runtime_worker_error'});return this.#worker=worker;}
 #expire(requestId:string,timeoutMs:number){const pending=this.#pending.get(requestId);if(!pending)return;this.#pending.delete(requestId);this.#onWarning({code:'runtime_timeout',requestId,message:`runtime_timeout:${timeoutMs}`});pending.reject(new Error('runtime_timeout'));this.#restart();}
 execute(request:RuntimeWorkerRequest){try{validateRuntimeRequest(request);}catch(error){const message=error instanceof Error?error.message:String(error);this.#onWarning({code:'runtime_budget_rejected',requestId:request.requestId,message});return Promise.reject(new Error(message));}const worker=this.#ensure();if(this.#pending.has(request.requestId))return Promise.reject(new Error('runtime_request_duplicate'));return new Promise<RuntimeWorkerResponse>((resolve,reject)=>{const timeoutMs=request.type==='lua'?this.#luaStartupTimeoutMs:this.#hardTimeoutMs,timer=setTimeout(()=>this.#expire(request.requestId,timeoutMs),timeoutMs);this.#pending.set(request.requestId,{resolve,reject,timer,requestType:request.type});worker.postMessage(request);});}
 #receive(message:RuntimeWorkerMessage){const pending=this.#pending.get(message.requestId);if(this.#disposed||!pending){this.#onWarning({code:'runtime_stale_response',requestId:message.requestId,message:'late_or_unknown_runtime_response'});return;}if(message.type==='ready'){if(pending.requestType!=='lua')return;clearTimeout(pending.timer);pending.timer=setTimeout(()=>this.#expire(message.requestId,this.#hardTimeoutMs),this.#hardTimeoutMs);return;}const response=message;try{validateRuntimeResponse(response);}catch(error){clearTimeout(pending.timer);this.#pending.delete(response.requestId);const text=error instanceof Error?error.message:String(error);this.#onWarning({code:'runtime_budget_rejected',requestId:response.requestId,message:text});pending.reject(new Error(text));this.#restart();return;}for(const warning of response.warnings){const text=`${warning.message}${warning.effect?`:effect=${warning.effect}`:''}`;if(warning.code==='runtime_soft_timeout')this.#onWarning({code:'runtime_soft_timeout',requestId:response.requestId,message:text});else if(warning.code==='runtime_budget_exceeded')this.#onWarning({code:'runtime_budget_rejected',requestId:response.requestId,message:text});else if(warning.code==='runtime_effect_blocked'||warning.code==='runtime_effect_approval'||warning.code==='runtime_state_write_blocked'||warning.code==='runtime_lua_disabled'||warning.code==='runtime_lua_capability_blocked'||warning.code==='runtime_lua_instruction_limit'||warning.code==='runtime_lua_error')this.#onWarning({code:warning.code,requestId:response.requestId,message:text});}clearTimeout(pending.timer);this.#pending.delete(response.requestId);pending.resolve(response);}
 #restart(){this.#worker?.terminate();this.#worker=null;for(const[requestId,pending]of this.#pending){clearTimeout(pending.timer);pending.reject(new Error('runtime_worker_restarted'));this.#onWarning({code:'runtime_disposed',requestId,message:'runtime_worker_restarted'});}this.#pending.clear();}
 dispose(reason='session_changed'){if(this.#disposed)return;this.#disposed=true;this.#worker?.terminate();this.#worker=null;for(const[requestId,pending]of this.#pending){clearTimeout(pending.timer);pending.reject(new Error(reason));this.#onWarning({code:'runtime_disposed',requestId,message:reason});}this.#pending.clear();}
}
