import type{CardAsset}from'@simbot/card';
export interface CardAtmosphere{background:string;border:string;backgroundRgb:[number,number,number];textContrast:number}
const TEXT:[number,number,number]=[230,232,238];
export function relativeLuminance(rgb:readonly number[]){const linear=(value:number)=>{const channel=value/255;return channel<=.03928?channel/12.92:((channel+.055)/1.055)**2.4;};return.2126*linear(rgb[0]??0)+.7152*linear(rgb[1]??0)+.0722*linear(rgb[2]??0);}
export function contrastRatio(a:readonly number[],b:readonly number[]){const first=relativeLuminance(a),second=relativeLuminance(b),high=Math.max(first,second),low=Math.min(first,second);return(high+.05)/(low+.05);}
export function cardAtmosphereFromRgb(red:number,green:number,blue:number):CardAtmosphere{const [h,s]=rgbToHsl(red,green,blue);let lightness=.18,rgb=hslToRgb(h,Math.min(.55,Math.max(.18,s)),lightness);while(contrastRatio(rgb,TEXT)<4.5&&lightness>.06){lightness-=.01;rgb=hslToRgb(h,Math.min(.55,Math.max(.18,s)),lightness);}const saturation=Math.round(Math.min(.55,Math.max(.18,s))*100),hue=h.toFixed(1);return{background:`hsl(${hue} ${saturation}% ${Math.round(lightness*100)}%)`,border:`hsl(${hue} ${saturation}% ${Math.round(Math.min(.42,lightness+.16)*100)}%)`,backgroundRgb:rgb,textContrast:contrastRatio(rgb,TEXT)};}
export function dominantAtmosphere(data:Uint8ClampedArray):CardAtmosphere|null{const bins=Array.from({length:12},()=>({weight:0,r:0,g:0,b:0}));for(let index=0;index+3<data.length;index+=4){const alpha=data[index+3]??0;if(alpha<128)continue;const r=data[index]??0,g=data[index+1]??0,b=data[index+2]??0,[h,s,l]=rgbToHsl(r,g,b);if(s<.12||l<.04||l>.94)continue;const weight=Math.max(.1,s)*alpha/255,bin=bins[Math.floor(h/30)%12]!;bin.weight+=weight;bin.r+=r*weight;bin.g+=g*weight;bin.b+=b*weight;}const best=bins.reduce((winner,bin)=>bin.weight>winner.weight?bin:winner,bins[0]!);return best.weight?cardAtmosphereFromRgb(best.r/best.weight,best.g/best.weight,best.b/best.weight):null;}
export async function applyCardTheme(asset:CardAsset|null,objectUrlFor:(asset:CardAsset)=>string|null){clearCardTheme();if(!asset||typeof document==='undefined')return null;try{const src=objectUrlFor(asset);if(!src)return null;const image=new Image();image.src=src;await image.decode();if(!image.naturalWidth||!image.naturalHeight)return null;const scale=Math.min(48/image.naturalWidth,48/image.naturalHeight,1),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)return null;context.drawImage(image,0,0,width,height);const theme=dominantAtmosphere(context.getImageData(0,0,width,height).data);if(!theme)return null;const root=document.documentElement.style;root.setProperty('--card-atmosphere-bg',theme.background);root.setProperty('--card-atmosphere-border',theme.border);return theme;}catch{return null;}}
export function clearCardTheme(){if(typeof document==='undefined')return;document.documentElement.style.removeProperty('--card-atmosphere-bg');document.documentElement.style.removeProperty('--card-atmosphere-border');}
function rgbToHsl(red:number,green:number,blue:number):[number,number,number]{const r=red/255,g=green/255,b=blue/255,max=Math.max(r,g,b),min=Math.min(r,g,b),lightness=(max+min)/2,difference=max-min;let hue=0;const saturation=difference===0?0:difference/(1-Math.abs(2*lightness-1));if(difference){if(max===r)hue=((g-b)/difference)%6;else if(max===g)hue=(b-r)/difference+2;else hue=(r-g)/difference+4;hue=(hue*60+360)%360;}return[hue,saturation,lightness];}
function hslToRgb(h:number,s:number,l:number):[number,number,number]{const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let rgb:[number,number,number];if(h<60)rgb=[c,x,0];else if(h<120)rgb=[x,c,0];else if(h<180)rgb=[0,c,x];else if(h<240)rgb=[0,x,c];else if(h<300)rgb=[x,0,c];else rgb=[c,0,x];return rgb.map((value)=>Math.round((value+m)*255))as[number,number,number];}
