<script lang="ts">
  import Button from '@simbot/ui/Button.svelte';
  import SpeakerStage from '@simbot/ui/SpeakerStage.svelte';
  import type { PlaySession } from '@simbot/session';
  import FactReceipt from './FactReceipt.svelte';
  let {session,version=0,onchange,portraitFor=()=>null}:{session:PlaySession;version?:number;onchange:()=>void;portraitFor?:(npcId:string,emotion?:string)=>string|null}=$props();
  let input=$state(''),busy=$state(false),error=$state(''),revision=$state(0);
  let messages=$derived.by(()=>{revision;version;return session.messages;}),speakers=$derived.by(()=>{revision;version;return session.lastSpeakers;});
  async function send(){if(!input.trim()||busy)return;const value=input;input='';busy=true;error='';revision+=1;try{await session.send(value);onchange();}catch(reason){error=reason instanceof Error?reason.message:String(reason);}finally{busy=false;revision+=1;}}
  async function undo(){if(busy||!session.checkpointDepth)return;await session.undoTurn();error='';revision+=1;onchange();}
  function keydown(event:KeyboardEvent){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send();}}
</script>
{#if speakers.length}<SpeakerStage {speakers} {portraitFor}/>{/if}
<div class="messages" aria-live="polite">{#if !messages.length}<p class="empty">대화를 시작하세요. 엔진은 수치와 선택지를 관리하고 LLM은 서사를 담당합니다.</p>{/if}{#each messages as message}<article class={message.role}><small>{message.role==='user'?'나':'AI'}</small><p>{message.content}</p>{#if message.facts?.length}<FactReceipt logs={message.facts}/>{/if}{#if message.chips?.length}<div class="chips">{#each message.chips as chip}<span class:rejected={!chip.ok}>{chip.text}</span>{/each}</div>{/if}</article>{/each}{#if busy}<p class="thinking">응답을 만들고 있습니다…</p>{/if}</div>
{#if error}<p class="error">{error}</p>{/if}<div class="composer"><textarea rows="3" bind:value={input} onkeydown={keydown} placeholder="행동이나 대화를 입력하세요" disabled={busy}></textarea><div class="controls"><button type="button" class="undo" onclick={()=>void undo()} disabled={busy||!session.checkpointDepth} title="직전 턴 상태로 완전 복원">↶ 되돌리기{#if session.checkpointDepth} <span class="depth">{session.checkpointDepth}</span>{/if}</button><Button onclick={send} disabled={busy||!input.trim()}>전송</Button></div></div>
<style>.messages small{color:var(--color-muted);font-size:.75rem}.messages{display:flex;flex-direction:column;gap:var(--space-3);min-height:14rem;max-height:32rem;overflow:auto;padding:var(--space-3)}article{max-width:85%;padding:var(--space-3);border-radius:var(--radius-lg);background:var(--color-inset)}article.user{align-self:flex-end;background:color-mix(in srgb,var(--color-accent) 18%,var(--color-inset))}article p{margin:.25rem 0 0;white-space:pre-wrap}.chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.chips span{padding:3px 7px;border:1px solid var(--color-line);border-radius:5px;font-size:.72rem}.chips .rejected{border-color:var(--color-danger);color:var(--color-danger)}.empty,.thinking{color:var(--color-muted)}.composer{display:grid;grid-template-columns:1fr auto;gap:var(--space-2);margin-top:var(--space-3)}.controls{display:flex;flex-direction:column;gap:var(--space-2);justify-content:stretch}.undo{display:inline-flex;align-items:center;gap:var(--space-1);min-height:2.4rem;padding:0 var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:transparent;color:var(--color-text);cursor:pointer}.undo:disabled{opacity:.4;cursor:default}.undo .depth{font-variant-numeric:tabular-nums;font-size:.72rem;color:var(--color-accent);background:color-mix(in srgb,var(--color-accent) 15%,transparent);border-radius:999px;padding:0 .4rem}textarea{resize:vertical;padding:var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:var(--color-inset);color:var(--color-text)}.error{color:var(--color-danger)}@media(max-width:600px){.composer{grid-template-columns:1fr}.controls{flex-direction:row}}</style>
