<script lang="ts">
  import{createVirtualizer}from'@tanstack/svelte-virtual';
  import{get}from'svelte/store';
  import{dollClasses,filterDolls,type DollPickerRow,type DollPickerSort}from'./doll-picker-model';
  import LazyDollPortrait from'./LazyDollPortrait.svelte';
  let{rows,onpick,pickLabel,priceKey,compact=false,selectedId=null,assetRevision=0,portraitFor=()=>null}:{rows:DollPickerRow[];onpick:(id:string)=>void;pickLabel:string;priceKey?:string;compact?:boolean;selectedId?:string|null;assetRevision?:number;portraitFor?:(id:string)=>string|null}=$props();
  let search=$state(''),classes=$state<Set<string>>(new Set()),minGrade=$state(0),sort=$state<DollPickerSort>('name'),scrollElement=$state<HTMLDivElement>(),width=$state(0);
  let availableClasses=$derived(dollClasses(rows)),filtered=$derived.by(()=>filterDolls(rows,{search,classes,minGrade,sort,...(priceKey?{priceKey}:{}),limit:Number.MAX_SAFE_INTEGER})),virtual=$derived(filtered.length>50),columns=$derived(width<700?1:Math.max(1,Math.floor((width+7)/(compact?180:220)))),rowCount=$derived(Math.ceil(filtered.length/columns));
  const virtualizer=createVirtualizer<HTMLDivElement,HTMLDivElement>({count:0,getScrollElement:()=>scrollElement??null,estimateSize:()=>compact?112:82,overscan:4});
  $effect(()=>{const count=rowCount,columnCount=columns,items=filtered;get(virtualizer).setOptions({count,getScrollElement:()=>scrollElement??null,estimateSize:()=>compact?112:82,overscan:4,getItemKey:index=>`${columnCount}:${String(items[index*columnCount]?.id??index)}`});});
  function toggle(value:string){classes=classes.has(value)?new Set([...classes].filter(item=>item!==value)):new Set([...classes,value]);}
  function measure(node:HTMLDivElement){const observer=new ResizeObserver(entries=>width=entries[0]?.contentRect.width??0);observer.observe(node);return{destroy:()=>observer.disconnect()};}
</script>
<section class:compact class="doll-picker" aria-label="전술인형 선택기">
  <div class="filters"><label>인형 검색<input aria-label="인형 이름 검색" placeholder="이름으로 검색" value={search} oninput={(event)=>search=event.currentTarget.value}/></label><div class="classes" aria-label="병과 필터">{#each availableClasses as value}<button class:active={classes.has(value)} aria-pressed={classes.has(value)} onclick={()=>toggle(value)}>{value}</button>{/each}</div><label>최소 등급<select aria-label="최소 별 등급" value={minGrade} onchange={(event)=>minGrade=Number(event.currentTarget.value)}><option value={0}>전체 ★</option>{#each [1,2,3,4,5,6] as grade}<option value={grade}>★ {grade} 이상</option>{/each}</select></label><label>정렬<select aria-label="인형 정렬" value={sort} onchange={(event)=>sort=event.currentTarget.value as DollPickerSort}><option value="name">이름</option><option value="grade">★</option><option value="power">전투력</option>{#if priceKey}<option value="price">가격</option>{/if}</select></label></div>
  {#if virtual}<div class="virtual-scroll" bind:this={scrollElement} use:measure aria-label={`인형 ${filtered.length}명 가상 목록`}><div class="virtual-space" style:height={`${$virtualizer.getTotalSize()}px`}>{#each $virtualizer.getVirtualItems() as virtualRow (virtualRow.key)}<div class="virtual-row" style:grid-template-columns={`repeat(${columns},minmax(0,1fr))`} style:transform={`translateY(${virtualRow.start}px)`}>{#each filtered.slice(virtualRow.index*columns,virtualRow.index*columns+columns) as row (String(row.id))}<article class:selected={String(row.id)===selectedId}><span class="portrait"><LazyDollPortrait id={String(row.id)} revision={assetRevision} {portraitFor}/></span><div><b>{String(row.name)}</b><small>{String(row.class)} · ★{String(row.grade)}{#if row.power!==undefined} · 전투력 {Number(row.power).toLocaleString()}{/if}</small>{#if priceKey}<strong>{Number(row[priceKey]??0).toLocaleString()} 자금</strong>{/if}</div><button aria-pressed={String(row.id)===selectedId} onclick={()=>onpick(String(row.id))}>{String(row.id)===selectedId?'✓ 선택됨':pickLabel}</button></article>{/each}</div>{/each}</div></div>{:else}<div use:measure class:roster={compact} class:doll-grid={!compact&&pickLabel==='선택'} class="results" aria-live="polite">{#each filtered as row (String(row.id))}<article class:selected={String(row.id)===selectedId}><span class="portrait"><LazyDollPortrait id={String(row.id)} revision={assetRevision} {portraitFor}/></span><div><b>{String(row.name)}</b><small>{String(row.class)} · ★{String(row.grade)}{#if row.power!==undefined} · 전투력 {Number(row.power).toLocaleString()}{/if}</small>{#if priceKey}<strong>{Number(row[priceKey]??0).toLocaleString()} 자금</strong>{/if}</div><button aria-pressed={String(row.id)===selectedId} onclick={()=>onpick(String(row.id))}>{String(row.id)===selectedId?'✓ 선택됨':pickLabel}</button></article>{/each}{#if !filtered.length}<p class="empty">조건에 맞는 인형이 없습니다.</p>{/if}</div>{/if}
</section>
<style>
  .doll-picker{display:grid;gap:10px}.filters{display:flex;align-items:end;gap:8px;flex-wrap:wrap;padding:9px;border:1px solid #35403f;background:#0d1416}.filters label{display:grid;gap:3px;color:#8fa09d;font-size:10px}.filters input,.filters select,.filters button{box-sizing:border-box;padding:7px 9px;border:1px solid #475353;border-radius:2px;background:#172024;color:#dce5e3}.classes{display:flex;gap:4px;flex-wrap:wrap}.classes button.active{border-color:#e5a84b;color:#ffd78e}.results{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:7px}.results article,.virtual-row article{display:grid;grid-template-columns:52px minmax(0,1fr) auto;align-items:center;gap:8px;padding:7px;border:1px solid #333e3d;background:#12191b}.results article.selected,.virtual-row article.selected{border-color:#e5a84b;box-shadow:inset 4px 0 #e5a84b,0 0 0 1px #e5a84b55;background:#24251f}.results article.selected button,.virtual-row article.selected button{border-color:#e5a84b;color:#ffd78e}.portrait{width:52px;height:66px;overflow:hidden;background:#0b1012}.results div,.virtual-row article>div{display:grid}.results small,.results strong,.virtual-row small,.virtual-row strong{color:#8fa09d;font-size:10px}.results button,.virtual-row button{padding:7px 9px;border:1px solid #475353;background:#172024;color:#dce5e3}.empty{color:#8fa09d}.virtual-scroll{height:min(56vh,560px);min-height:260px;overflow:auto;contain:strict}.virtual-space{position:relative;width:100%}.virtual-row{position:absolute;top:0;left:0;display:grid;width:100%;gap:7px}.compact .results{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}.compact .portrait{width:38px;height:48px}.compact .results article,.compact .virtual-row article{grid-template-columns:38px minmax(0,1fr)}.compact .results article>button,.compact .virtual-row article>button{grid-column:1/-1}@media(max-width:700px){.filters{align-items:stretch}.filters label:first-child{width:100%}.filters input{width:100%}.results{grid-template-columns:1fr}}
</style>
