<script lang="ts">
  import type {ProjectRuntime} from '@simbot/runtime';
  import Icon from '@simbot/ui/Icon.svelte';
  import type {SimulationActionHandler,SimulationActionMode} from './simulation-action';
  let {runtime,version,busy=false,onaction=null,onchange}:{runtime:ProjectRuntime;version:number;busy?:boolean;onaction?:SimulationActionHandler|null;onchange:()=>void}=$props();
  let lastLog=$state<Record<string,unknown>[]>([]),quantities=$state<Record<string,number>>({}),pending=$state(false);
  const rows=(value:unknown)=>Array.isArray(value)?value.filter(item=>item&&typeof item==='object') as Record<string,unknown>[]:[];
  const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
  function select(id:string){try{return runtime.select(id);}catch{return{};}}
  let engineState=$derived.by(()=>{version;return runtime.state;}),management=$derived.by(()=>{version;return object(select('inn/management'));}),traffic=$derived.by(()=>{version;return object(select('inn/traffic'));}),rooms=$derived.by(()=>{version;return rows(select('inn/rooms'));});
  let facilities=$derived(rows(management.facilities)),resources=$derived(rows(management.resources)),staff=$derived(object(management.staff)),staffItems=$derived(rows(staff.items)),quests=$derived(rows(management.quests)),lodging=$derived(rows(traffic.lodging)),mail=$derived(rows(traffic.mail)),waves=$derived(rows(traffic.waves));
  let purchaseTotal=$derived(resources.reduce((sum,item)=>sum+Number(item.basePrice??0)*Math.max(0,Math.trunc(quantities[String(item.id)]??0)),0));
  let status=$derived.by(()=>{const failed=lastLog.find(row=>row.ok===false);if(failed)return reasonText(String(failed.reason??'unknown'));return lastLog.length?'처리가 완료되었습니다.':'';});
  const money=(value:unknown)=>`${Number(value??0).toLocaleString('ko-KR')}원`;
  function reasonText(reason:string){return({insufficient_gold:'골드가 부족합니다.',max_level:'이미 최대 레벨입니다.',no_upgrade_cost:'증축 비용 정보가 없습니다.',staff_full:'직원 숙소가 가득 찼습니다.',already_attempted_today:'오늘 이미 시도한 의뢰입니다.',earlier_wave_pending:'앞선 영업을 먼저 진행해야 합니다.',incident_pending:'진행 중인 사건을 먼저 해결해야 합니다.',no_room_available:'수용 가능한 빈 객실이 없습니다.',lodging_already_reviewed:'오늘 숙박 문의는 이미 확인했습니다.',mail_already_checked:'오늘 우편은 이미 확인했습니다.'} as Record<string,string>)[reason]??`처리하지 못했습니다: ${reason}`;}
  async function run(id:string,params:Record<string,unknown>={},mode:SimulationActionMode='narrated',intent?:string){if(pending||busy)return;pending=true;lastLog=[];try{lastLog=onaction?await onaction({id,params,mode,...(intent?{intent}:{})}):mode==='scene'?[]:runtime.dispatch(id,params).log as Record<string,unknown>[];onchange();}finally{pending=false;}}
  function scene(intent:string){void run('',{},'scene',intent);}
  function purchase(){const items=resources.map(value=>({resource:value.id,qty:Math.trunc(quantities[String(value.id)]??0)})).filter(value=>value.qty>0);if(items.length)void run('purchase_batch',{items},'ledger');}
</script>

<div class="console">
  <section class="summary"><div><span>일차</span><b>{String(engineState.day??1)}</b></div><div><span>골드</span><b>{money(management.gold)}</b></div>{#each resources as resource}<div><span>{String(resource.label??resource.id)}</span><b>{String((engineState.resources as Record<string,unknown>)?.[String(resource.id)]??0)} {String(resource.unit??'')}</b></div>{/each}</section>

  <section><h2><Icon name="star"/> 영업</h2><div class="actions">{#each waves as wave}<span class="action"><span class="button-pair"><button disabled={busy||pending||!wave.available} onclick={()=>run('traffic_wave',{wave:wave.id})}>{String(wave.label??wave.id)}{wave.resolved?' · 완료':''}</button><button class="quiet" disabled={busy||pending||!wave.canSkip} onclick={()=>run('traffic_wave',{wave:wave.id,skip:true},'ledger')}>건너뛰기</button></span>{#if wave.reason}<small>{String(wave.reason)}</small>{/if}</span>{/each}<span class="action"><button disabled={busy||pending||object(traffic.lodgingReview).available===false} onclick={()=>run('lodging_review')}>숙박 문의</button>{#if object(traffic.lodgingReview).reason}<small>{String(object(traffic.lodgingReview).reason)}</small>{/if}</span><span class="action"><button disabled={busy||pending||object(traffic.mailCheck).available===false} onclick={()=>run('mail_check')}>우편 확인</button>{#if object(traffic.mailCheck).reason}<small>{String(object(traffic.mailCheck).reason)}</small>{/if}</span><button disabled={busy||pending} class="danger" onclick={()=>run('day_end')}>하루 마감</button></div></section>

  {#if traffic.incident}<section class="attention"><h2>{String(object(traffic.incident).label??'사건')}</h2><p>{String(object(traffic.incident).desc??'')}</p><div class="actions">{#each rows(object(traffic.incident).choices) as choice}<button disabled={busy||pending} onclick={()=>run('incident_choice',{choice:choice.id})}>{String(choice.label??choice.id)}</button>{/each}</div></section>{/if}

  {#if lodging.length}<section><h2>숙박 문의</h2>{#each lodging as request}<article><div><b>{String(request.name??request.label)}</b><small>{String(request.party)}명 · {String(request.stayDays)}박{request.available?` · ${String(request.roomNo)}호 · 매출 ${money(request.revenue)}`:''}</small>{#if request.reason}<small class="reason">{String(request.reason)}</small>{/if}</div><div class="actions"><button disabled={busy||pending||!request.available} onclick={()=>run('lodging_accept',{requestId:request.id})}>수락</button><button disabled={busy||pending} onclick={()=>run('lodging_reject',{requestId:request.id})}>거절</button></div></article>{/each}</section>{/if}

  {#if mail.length}<section><h2>우편</h2>{#each mail as letter}<article><div><b>{String(letter.type==='reward'?'감사 선물':'의뢰 편지')}</b><small>{String(letter.axis??'')}</small></div><button disabled={busy||pending} onclick={()=>run('mail_open',{mailId:letter.id},'ledger')}>열기</button></article>{/each}</section>{/if}

  <section><h2>재고 구매</h2><div class="purchase">{#each resources as resource}<label><span>{String(resource.label??resource.id)} · 개당 {money(resource.basePrice)}</span><input disabled={busy||pending} type="number" min="0" max="999" value={quantities[String(resource.id)]??0} oninput={(event)=>quantities[String(resource.id)]=Number(event.currentTarget.value)}/></label>{/each}<div class="purchase-total"><b>합계 {money(purchaseTotal)}</b>{#if purchaseTotal>Number(management.gold??0)}<small class="reason">{money(purchaseTotal-Number(management.gold??0))} 부족</small>{/if}</div><button disabled={busy||pending||purchaseTotal<=0||purchaseTotal>Number(management.gold??0)} onclick={purchase}>설정한 수량 일괄 구매</button></div></section>

  <section><h2>시설</h2>{#each facilities as facility}<article><div><b>{String(facility.label??facility.id)}</b><small>Lv.{String(facility.level)} / {String(facility.maxLevel)}{facility.cost!=null?` · 다음 증축 ${money(facility.cost)}`:''}</small>{#if facility.reason}<small class="reason">{String(facility.reason)}</small>{/if}</div><button disabled={busy||pending||!facility.available} onclick={()=>run('upgrade',{facilityId:facility.id},'ledger')}>증축</button></article>{/each}</section>

  <section><h2>직원 {String(staff.count??0)} / {String(staff.capacity??0)}</h2><article><div><b>새 직원</b><small>채팅에서 임금과 조건을 합의한 뒤 고용이 확정됩니다.</small>{#if staff.reason}<small class="reason">{String(staff.reason)}</small>{/if}</div><button disabled={busy||pending||!!staff.full} onclick={()=>scene('여관에 있는 인물 중 고용 후보와 자연스러운 고용 협상을 시작한다. 임금과 조건에 합의하기 전에는 고용을 확정하지 않는다.')}>고용 협상 시작</button></article>{#each staffItems as member}<article><div><b>{String(member.name??member.npcId)}</b><small>일급 {money(member.dailyWage)}</small></div><button disabled={busy||pending} onclick={()=>scene(`${String(member.name??member.npcId)} 직원과 자연스러운 퇴직 또는 해고 협상을 시작한다. 대화로 합의되기 전에는 해고를 확정하지 않는다.`)}>퇴직·해고 협상</button></article>{/each}</section>

  <section><h2>객실</h2><div class="grid">{#each rooms as room}<div class:locked={room.locked}><b>{String(room.no)}호 · {String(room.kind??'객실')}</b><small>{room.locked?'잠김':money(room.pricePerNight)}</small><small>{rows(room.guests).length?`투숙 ${rows(room.guests).length}팀`:'빈방'}</small></div>{/each}</div></section>

  <section><h2>의뢰 게시판</h2>{#if quests.length}{#each quests as quest}<article><div><b>{String(quest.name??quest.id)}</b><small>성공 가능성 {String(quest.chance)}%{Array.isArray(quest.reward)?` · 보상 ${money(quest.reward[0])}~${money(quest.reward[1])}`:''}</small>{#if quest.reason}<small class="reason">{String(quest.reason)}</small>{/if}</div><button disabled={busy||pending||!quest.available} onclick={()=>run('attempt_quest',{questId:quest.id})}>수행</button></article>{/each}{:else}<p class="muted">주점 2레벨에서 의뢰 게시판이 열리거나, 현재 가능한 의뢰가 없습니다.</p>{/if}</section>

  {#if status}<p class:failed={lastLog.some(row=>row.ok===false)} class="status" aria-live="polite">{status}</p>{/if}
</div>

<style>
  .console{display:grid;gap:12px;color:#e7e9ee}.console section{padding:12px;border:1px solid #343944;border-radius:9px;background:#191c22}.summary{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px}.summary div{display:grid;gap:3px;padding:8px;background:#222630;border-radius:6px}.summary span,small,.muted{font-size:11px;color:#9299a7}h2{display:flex;align-items:center;gap:6px;margin:0 0 9px;font-size:14px}.actions{display:flex;flex-wrap:wrap;gap:6px}.action{display:grid;gap:3px}.button-pair{display:flex}.button-pair button:first-child{border-radius:6px 0 0 6px}.button-pair button:last-child{border-left:0;border-radius:0 6px 6px 0}.quiet{color:#9ca7b8}button{padding:7px 10px;border:1px solid #46516a;border-radius:6px;background:#252c3a;color:#c9d8f5;cursor:pointer}button:hover{border-color:#6f91d2}button:disabled{opacity:.4;cursor:not-allowed}.danger{border-color:#6e493f;color:#e5a18d}.attention{border-color:#7c6334!important;background:#282316!important}.attention p{white-space:pre-wrap}article{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #2c3038}article:last-child{border:0}article>div{display:grid;gap:3px}.purchase{display:grid;gap:7px}.purchase label,.purchase-total{display:flex;align-items:center;justify-content:space-between;gap:8px}.purchase input{width:90px;padding:6px;border:1px solid #3d424d;border-radius:5px;background:#11141a;color:#eee}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:7px}.grid>div{display:grid;gap:4px;padding:8px;border:1px solid #343944;border-radius:6px}.grid .locked{opacity:.45}.reason{color:#d9a079}.status{position:sticky;bottom:0;margin:0;padding:9px;border:1px solid #3d6b54;border-radius:7px;background:#183023;color:#bce7ca}.status.failed{border-color:#805044;background:#351e1a;color:#efb8a8}@media(max-width:600px){article{align-items:flex-start;flex-direction:column}.summary{grid-template-columns:1fr 1fr}}
</style>
