<script lang="ts">
  import type{ChatIndex}from'@simbot/session';import type{CardLibraryMeta}from'./card-library';import Icon from'@simbot/ui/Icon.svelte';
  let{cardName='카드를 선택하세요',cards,index,activeId,onadd,oncard,onchat,onsettings}:{cardName?:string;cards:CardLibraryMeta[];index:ChatIndex;activeId:string|null;onadd:()=>void;oncard:(id:string)=>void;onchat:(id:string)=>void;onsettings:()=>void}=$props();
  let open=$state(false),tab=$state<'cards'|'chats'>('cards');const close=()=>open=false;
</script>
<svelte:window onkeydown={(event)=>{if(event.key==='Escape')close();}}/>
<header class="appbar"><button aria-label="메뉴 열기" aria-expanded={open} onclick={()=>open=true}><Icon name="list"/></button><strong>{cardName}</strong><button aria-label="설정 열기" onclick={onsettings}><Icon name="settings"/></button></header>
{#if open}<button class="scrim" aria-label="메뉴 닫기" onclick={close}></button><aside class="drawer" aria-label="카드와 채팅 목록"><div class="tabs"><button class:active={tab==='cards'} onclick={()=>tab='cards'}><Icon name="user"/> 카드</button><button class:active={tab==='chats'} onclick={()=>tab='chats'}><Icon name="message"/> 채팅</button></div>{#if tab==='cards'}<section><button class="create" onclick={()=>{close();onadd();}}><Icon name="plus"/> 카드 가져오기</button>{#each cards as card}<button class:active={card.projectId===activeId} onclick={()=>{close();oncard(card.projectId);}}><span class="avatar">{card.name.slice(0,1)}</span><span>{card.name}</span></button>{/each}</section>{:else}<section>{#if index.chats.length===0}<p>카드를 선택하면 채팅 목록이 나타납니다.</p>{/if}{#each index.chats as chat}<button class:active={chat.chatId===index.activeChatId} onclick={()=>{close();onchat(chat.chatId);}}><Icon name="message"/><span>{chat.name}</span><small>{chat.turn}턴</small></button>{/each}</section>{/if}</aside>{/if}
<style>.appbar,.drawer,.scrim{display:none}@media(max-width:999px){.appbar{position:fixed;inset:0 0 auto 0;z-index:35;min-height:56px;display:grid;grid-template-columns:52px minmax(0,1fr) 52px;align-items:center;border-bottom:1px solid #30343d;background:#111318;color:#eef0f5;padding-top:env(safe-area-inset-top)}.appbar strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:center}.appbar button,.drawer button{border:0;background:transparent;color:inherit;cursor:pointer}.appbar button{height:56px;display:grid;place-items:center}.scrim{display:block;position:fixed;inset:0;z-index:40;border:0;background:#0009}.drawer{display:flex;position:fixed;inset:0 auto 0 0;z-index:45;width:min(86vw,360px);flex-direction:column;background:#15171c;color:#e8eaf0;box-shadow:8px 0 28px #0008;animation:slide .18s ease-out;padding-top:env(safe-area-inset-top)}.tabs{height:56px;display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid #30343d}.tabs button{display:flex;align-items:center;justify-content:center;gap:7px;color:#8f97a6}.tabs button.active{color:#fff;border-bottom:2px solid #6c98f4}.drawer section{overflow-y:auto;padding:10px}.drawer section>button{width:100%;min-height:50px;display:flex;align-items:center;gap:10px;padding:8px;border-radius:7px;text-align:left}.drawer section>button:hover,.drawer section>button.active{background:#292d36}.drawer .create{border:1px dashed #4b5260;margin-bottom:8px;justify-content:center}.avatar{width:36px;height:36px;display:grid;place-items:center;border-radius:6px;background:#333844}.drawer small{margin-left:auto;color:#858c99}.drawer p{color:#9299a7;font-size:13px}@keyframes slide{from{transform:translateX(-100%)}to{transform:none}}}@media(prefers-reduced-motion:reduce){.drawer{animation:none}}</style>
