<script lang="ts">
  import type { ChatIndex, PlaySession } from '@simbot/session';
  import type { CardPassport, CardRuntimeProfile,Persona,PromptPreset } from '@simbot/risu';
  import PassportPanel from './PassportPanel.svelte';
  import { toFactLine } from './FactReceipt.svelte';
  import { summarizeEngineState } from './card-library';
  import PromptPanel from './PromptPanel.svelte';
  import PersonaPanel from './PersonaPanel.svelte';
  interface PromptUi{presets:PromptPreset[];active:PromptPreset;onselect:(id:string)=>void;onchange:(p:PromptPreset)=>void;onnew:()=>void;onclone:()=>void;onrename:()=>void;onremove:()=>void;onimport:(file:File)=>void;onexport:()=>void}
  interface PersonaUi{personas:Persona[];active:Persona;bound:boolean;onselect:(id:string)=>void;onsave:(p:Persona)=>void;onnew:()=>void;onclone:()=>void;onremove:()=>void;onbind:(v:boolean)=>void}
  let {profile,passport,index,session,version,promptUi,personaUi,open=false,oncreate,onselect,onrename,onremove,onundo}:{profile:CardRuntimeProfile;passport:CardPassport;index:ChatIndex;session:PlaySession;version:number;promptUi:PromptUi;personaUi:PersonaUi;open?:boolean;oncreate:()=>void;onselect:(id:string)=>void;onrename:(id:string)=>void;onremove:(id:string)=>void;onundo:()=>void}=$props();
  let tab=$state<'chat'|'basic'|'passport'|'prompt'|'persona'>('chat');
  let facts=$derived.by(()=>{void version;return session.lastLogs.map(toFactLine);});
  let confirmed=$derived(facts.filter(x=>!x.rejected).length),blocked=$derived(facts.filter(x=>x.rejected).length);
  let stateRows=$derived.by(()=>{void version;return summarizeEngineState(session.runtime.state);});
</script>
<aside class="side" class:open style:display={open?'flex':undefined}><header><strong>{profile.card.name}</strong><div class="tabs"><button class:active={tab==='chat'} onclick={()=>tab='chat'}>💬 채팅</button><button class:active={tab==='basic'} onclick={()=>tab='basic'}>👤 기본</button><button class:active={tab==='persona'} onclick={()=>tab='persona'}>🧑 페르소나</button><button class:active={tab==='prompt'} onclick={()=>tab='prompt'}>📝 프롬프트</button><button class:active={tab==='passport'} onclick={()=>tab='passport'}>🛂 여권</button></div></header>
{#if tab==='chat'}<section class="content chats"><button class="new" onclick={oncreate}>＋ 새 채팅</button>{#each index.chats as chat (chat.chatId)}<div class:active={index.activeChatId===chat.chatId} class="chat"><button class="select" onclick={()=>onselect(chat.chatId)}><b>{chat.name}</b><small>{chat.turn}턴</small></button><button onclick={()=>onrename(chat.chatId)}>✎</button><button onclick={()=>onremove(chat.chatId)}>🗑</button></div>{/each}</section>
<section class="engine"><div class="engine-head"><strong>엔진 확정</strong><span>{confirmed}확정 · {blocked}차단</span></div><div class="mode">{passport.mode==='full-sim'?'완전 시뮬':'일반 채팅'}</div>{#if stateRows.length}<dl>{#each stateRows as row}<div><dt>{row.label}</dt><dd>{row.value}</dd></div>{/each}</dl>{/if}{#if facts.length}<ul>{#each facts.slice(0,4) as fact}<li class:rejected={fact.rejected}>{fact.icon} {fact.label} {fact.delta??fact.note}</li>{/each}</ul>{/if}<button class="undo" disabled={!session.checkpointDepth} onclick={onundo}>↶ 되돌리기 <span>{session.checkpointDepth}</span></button></section>
{:else if tab==='basic'}<section class="content basic"><h3>{profile.card.name}</h3><h4>설명</h4><p>{profile.card.description||'설명 없음'}</p><h4>시나리오</h4><p>{profile.card.scenario||'시나리오 없음'}</p></section>{:else if tab==='persona'}<section class="content"><PersonaPanel {...personaUi}/></section>{:else if tab==='prompt'}<section class="content"><PromptPanel {...promptUi}/></section>{:else}<section class="content"><PassportPanel {passport}/></section>{/if}</aside>
<style>.side{width:300px;height:100dvh;flex:none;display:flex;flex-direction:column;background:#1c1f26;border-right:1px solid #30343e;color:#e8eaf0}header{padding:18px 16px 10px;border-bottom:1px solid #30343e}.tabs{display:flex;margin-top:14px;gap:4px}.tabs button{flex:1;padding:8px 2px;border:0;border-bottom:2px solid transparent;background:transparent;color:#858b97;font-size:12px}.tabs button.active{color:#8bb0ff;border-color:#6c98f4}.content{padding:12px;overflow:auto}.chats{flex:1}.new{width:100%;padding:10px;border:1px dashed #424753;background:transparent;color:#aeb4c1;border-radius:8px;margin-bottom:10px}.chat{display:flex;align-items:center;border-radius:7px}.chat.active{background:#2a3040}.chat>button{border:0;background:transparent;color:#9299a7;padding:7px 5px}.chat .select{flex:1;display:flex;justify-content:space-between;color:#e5e7ed;text-align:left}.chat small{color:#747b88}.engine{margin:12px;padding:12px;border:1px solid #3a414d;border-radius:10px;background:#171a20}.engine-head{display:flex;justify-content:space-between;font-size:12px}.engine-head span,.mode{color:#87909e;font-size:11px}.mode{margin-top:5px}.engine dl{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:10px 0}.engine dl div{display:flex;justify-content:space-between;background:#20242c;padding:5px 7px;border-radius:5px}.engine dt,.engine dd{font-size:11px;margin:0}.engine ul{list-style:none;padding:0;margin:8px 0;font-size:11px}.engine li{padding:3px;color:#a9cfbc}.engine li.rejected{color:#e0a7af}.undo{width:100%;border:1px solid #424753;background:transparent;color:#d5d8df;padding:8px;border-radius:7px}.basic p{white-space:pre-wrap;color:#aeb3bd;font-size:13px;line-height:1.6}@media(max-width:1000px){.side{display:none}}</style>
