import { SCREEN_PRESETS, setBasics, setInitialState, setModuleEnabled, setScreenPreset, updateLoreEntries, validateEditorProject } from '../core/editor/projectEditor.js';

export function renderEditorView(panel, ctx) {
  let project = ctx.ensureProject(); const root = document.createElement('div'); root.className = 'editor-workspace';
  const nav = document.createElement('nav'); nav.className = 'editor-sections'; const body = document.createElement('div'); body.className = 'editor-body';
  const sections = [['basics','기본 정보'],['prompt','프롬프트'],['lore','로어북'],['modules','모듈'],['rules','초기 상태'],['assets','에셋 연결'],['screens','화면'],['review','검토·저장']]; let active = 'basics';
  const save = (next) => { project = next; ctx.updateProject(next); draw(); };
  const draw = () => { nav.replaceChildren(); body.replaceChildren(); for (const [id,label] of sections) { const button = document.createElement('button'); button.type = 'button'; button.className = id === active ? 'tab editor-active' : 'tab'; button.textContent = label; button.addEventListener('click', () => { active = id; draw(); }); nav.append(button); } renderSection(body, active, project, save, ctx); };
  root.append(nav, body); panel.append(root); draw(); return () => {};
}

function renderSection(body, section, project, save, ctx) { const manifest = project.manifest; const heading = document.createElement('h2'); heading.textContent = sectionTitle(section); body.append(heading);
  if (section === 'basics') { const character = manifest.content.characters[0] || {}; const title = field('프로젝트 이름', manifest.title); const name = field('주 캐릭터 이름', character.name || ''); const desc = area('설명', character.description || ''); body.append(title.wrap, name.wrap, desc.wrap, action('저장', () => save(setBasics(project, { title: title.input.value, name: name.input.value, description: desc.input.value })))); }
  else if (section === 'prompt') { body.append(note('Risu 프리셋 블록 순서와 원본은 그대로 보존됩니다. 이 MVP에서는 프리셋을 선택하고 실제 요청 추적 화면에서 결과를 검토합니다.')); const select = document.createElement('select'); for (const preset of manifest.prompts.presets || []) { const option = document.createElement('option'); option.value = preset.id; option.textContent = preset.name || preset.id; option.selected = preset.id === manifest.prompts.defaultPresetId; select.append(option); } select.addEventListener('change', () => save(edit(project, (m) => { m.prompts.defaultPresetId = select.value || null; }))); body.append(select, rawDetails(manifest.prompts)); }
  else if (section === 'lore') { const entries = manifest.content.lorebooks[0]?.entries || []; const drafts = []; entries.slice(0, 100).forEach((entry, index) => { const row = document.createElement('details'); const summary = document.createElement('summary'); summary.textContent = entry.name || entry.comment || `로어 ${index + 1}`; const keys = field('호출 키(쉼표 구분)', (entry.keys || []).join(', ')); const content = area('내용', entry.content || ''); row.append(summary, keys.wrap, content.wrap); body.append(row); drafts.push({ id: String(entry.id ?? index), keys, content, enabled: entry.enabled !== false }); }); body.append(action('표시된 로어 일괄 저장', () => save(updateLoreEntries(project, drafts.map((item) => ({ id: item.id, keys: item.keys.input.value, content: item.content.input.value, enabled: item.enabled })))))); }
  else if (section === 'modules') { for (const module of manifest.modules.installed || []) { const label = document.createElement('label'); label.className = 'editor-check'; const input = document.createElement('input'); input.type = 'checkbox'; input.checked = module.enabled !== false; input.addEventListener('change', () => save(setModuleEnabled(project, module.id, input.checked))); label.append(input, document.createTextNode(`${module.id} · ${module.version || '1.0.0'}`)); body.append(label); } body.append(note('Lua처럼 낮은 수준의 실행 코드는 보존되지만 이 화면에서 안전하다고 자동 승인하지 않습니다.')); }
  else if (section === 'rules') { const json = area('초기 상태(JSON)', JSON.stringify(manifest.runtime.schema?.initialState || {}, null, 2)); const status = document.createElement('p'); body.append(json.wrap, action('검증하고 저장', () => { try { save(setInitialState(project, JSON.parse(json.input.value))); status.textContent = '저장했습니다.'; } catch (error) { status.textContent = `저장하지 못했습니다: ${error.message}`; } }), status); }
  else if (section === 'assets') { body.append(note('에셋의 canonical NPC와 감정 연결을 확인합니다. 원본 파일은 변경하지 않습니다.')); const table = document.createElement('table'); for (const asset of (manifest.assets || []).slice(0, 200)) { const tr = document.createElement('tr'); tr.append(cell(asset.name || asset.id), cell(asset.canonical?.entityId || '미연결'), cell(asset.canonical?.emotion || '-')); table.append(tr); } body.append(table); }
  else if (section === 'screens') { const select = document.createElement('select'); for (const [id,value] of Object.entries(SCREEN_PRESETS)) { const option = document.createElement('option'); option.value = id; option.textContent = ({ chat:'대화 중심', adventure:'모험·파티', management:'경영' })[id]; select.append(option); } body.append(select, action('화면 프리셋 적용', () => save(setScreenPreset(project, select.value))), rawDetails(manifest.runtime.screens)); }
  else { const issues = validateEditorProject(project); body.append(note(issues.length ? `확인할 문제 ${issues.length}개: ${issues.map((item) => `${item.path}(${item.reason})`).join(', ')}` : '필수 구조 검사를 통과했습니다.')); body.append(action('라이브 플레이테스트', () => { ctx.activateProject(project); ctx.goToPlay(); }), action('SimPack 저장', () => ctx.exportProject(project)), rawDetails(manifest)); }
}
function edit(project, fn) { const next = { manifest: JSON.parse(JSON.stringify(project.manifest)), files: project.files }; fn(next.manifest); next.manifest.revision += 1; return next; }
function field(label, value) { const wrap = document.createElement('label'); wrap.className = 'editor-field'; const span = document.createElement('span'); span.textContent = label; const input = document.createElement('input'); input.value = value; wrap.append(span, input); return { wrap, input }; }
function area(label, value) { const result = field(label, value); const input = document.createElement('textarea'); input.value = value; input.rows = Math.min(18, Math.max(5, String(value).split('\n').length)); result.wrap.replaceChild(input, result.input); result.input = input; return result; }
function action(label, handler) { const button = document.createElement('button'); button.type = 'button'; button.className = 'primary-btn'; button.textContent = label; button.addEventListener('click', handler); return button; }
function note(text) { const p = document.createElement('p'); p.className = 'editor-note'; p.textContent = text; return p; }
function rawDetails(value) { const details = document.createElement('details'); const summary = document.createElement('summary'); summary.textContent = '원본 구조 함께 보기'; const pre = document.createElement('pre'); pre.textContent = JSON.stringify(value, null, 2); details.append(summary, pre); return details; }
function cell(value) { const td = document.createElement('td'); td.textContent = String(value); return td; }
function sectionTitle(id) { return ({ basics:'기본 정보', prompt:'Risu 호환 프롬프트', lore:'로어북', modules:'모듈과 권한', rules:'초기값과 규칙', assets:'에셋 연결', screens:'화면 프리셋', review:'검토·저장' })[id]; }
