import{describe,expect,it,vi}from'vitest';import{createFixedEmbeddingProvider,createVoyageProvider,decideAbstention,EmbeddingCache,MemoryLedger,memoryRecord,planGroundedMemory}from'../src/index.ts';
const evidence=(id:string)=>[{kind:'message' as const,id}];
describe('restored memory safety contracts',()=>{
  it('abstains below the confidence floor and on strict ambiguity',()=>{expect(decideAbstention([.1],{mode:'soft',minConfidence:.2}).reason).toBe('insufficient_grounding');expect(decideAbstention([.8,.75],{mode:'strict',minMargin:.1}).reason).toBe('ambiguous_grounding');});
  it('enforces scene, privacy, kind quota and token budget',async()=>{const ledger=new MemoryLedger();ledger.add(memoryRecord({id:'public',text:'실비아 급료 약속',turn:9,status:'approved',kind:'promise',sceneId:'inn',evidence:evidence('m1')}));ledger.add(memoryRecord({id:'old',text:'실비아 급료 과거 약속',turn:1,status:'approved',kind:'promise',sceneId:'inn',evidence:evidence('m2')}));ledger.add(memoryRecord({id:'other-scene',text:'실비아 급료 약속',turn:10,status:'approved',kind:'promise',sceneId:'dungeon',evidence:evidence('m3')}));ledger.add(memoryRecord({id:'secret',text:'실비아 비밀 급료',turn:10,status:'approved',kind:'secret',knowledge:{privacy:'secret',holderEntityIds:['silvia']},evidence:evidence('m4')}));const result=await planGroundedMemory(ledger,'실비아 급료 약속',{atTurn:10,sceneId:'inn',perKindQuota:1,budgetTokens:20,abstention:{mode:'off'}});expect(result.records.map((record)=>record.id)).toEqual(['public']);});
  it('retrieves superseded facts only for an explicit past query',async()=>{const ledger=new MemoryLedger(),first=memoryRecord({id:'old-room',text:'예전 방은 101호',turn:1,status:'approved',kind:'engine-fact',canonicalAnchors:['room'],evidence:[{kind:'event',id:'e1'}]});ledger.add(first);ledger.replace(memoryRecord({id:'new-room',text:'현재 방은 202호',turn:4,status:'approved',kind:'engine-fact',canonicalAnchors:['room'],evidence:[{kind:'event',id:'e2'}]}),4);expect((await planGroundedMemory(ledger,'현재 방',{atTurn:5,queryMode:'current',abstention:{mode:'off'}})).records.map((record)=>record.id)).toEqual(['new-room']);expect((await planGroundedMemory(ledger,'예전 방',{atTurn:5,queryMode:'past',abstention:{mode:'off'}})).records.map((record)=>record.id)).toContain('old-room');expect(ledger.get('new-room')?.supersedes).toEqual(['old-room']);});
  it('keeps the embedding cache bounded and model-context keyed',()=>{const cache=new EmbeddingCache(2);cache.set('model-a:doc:x',[1]);cache.set('model-b:doc:x',[2]);cache.set('model-a:doc:y',[3]);expect(cache.size).toBe(2);expect(cache.get('model-a:doc:x')).toBeNull();});
  it('keeps fixed semantic retrieval deterministic',async()=>{const provider=createFixedEmbeddingProvider(),first=await provider.embedQueries(['same']),second=await provider.embedQueries(['same']);expect(first).toEqual(second);});
});
describe('Voyage safety adapter',()=>{
  it('chunks batches, uses contextual inputs, caches, and retries 429',async()=>{let attempts=0;const fetch=vi.fn(async(_url:unknown,init?:RequestInit)=>{attempts++;if(attempts===1)return new Response('',{status:429});const body=JSON.parse(String(init?.body))as{inputs:string[][]};return new Response(JSON.stringify({data:body.inputs.map((_,index)=>({embeddings:[[attempts,index]]}))}),{status:200});}),provider=createVoyageProvider({apiKey:'secret',fetch:fetch as unknown as typeof globalThis.fetch,batchSize:2,sleep:async()=>{}});const vectors=await provider.embedDocuments(['a','b','c']);expect(vectors).toHaveLength(3);expect(fetch).toHaveBeenCalledTimes(3);expect(JSON.parse(String(fetch.mock.calls[1]?.[1]?.body)).inputs).toEqual([['a'],['b']]);await provider.embedDocuments(['a','b','c']);expect(fetch).toHaveBeenCalledTimes(3);});
  it('rejects provider limits before fetch',async()=>{const fetch=vi.fn(),provider=createVoyageProvider({apiKey:'secret',fetch:fetch as unknown as typeof globalThis.fetch});await expect(provider.embedDocuments(['x'.repeat(480001)])).rejects.toThrow('voyage_limit_tokens');expect(fetch).not.toHaveBeenCalled();});
  it('forwards abort signals and masks keys from thrown errors',async()=>{const controller=new AbortController(),key='voyage-secret',fetch=vi.fn(async(_url:unknown,init?:RequestInit)=>{expect(init?.signal).toBe(controller.signal);throw new Error(`failed ${key}`);}),provider=createVoyageProvider({apiKey:key,fetch:fetch as unknown as typeof globalThis.fetch});await expect(provider.embedQueries(['hello'],controller.signal)).rejects.not.toThrow(key);});
});
