import type{MemoryKind,MemoryKnowledge,MemoryLifecycle,MemoryRecord}from'@simbot/contracts';
import type{MemoryLedger}from'./index.ts';

export interface MemoryCandidateInput{kind?:string;text?:string;entities?:string[];evidenceQuote?:string;eventIds?:string[];canonicalKey?:string;knowledgeScope?:string;importance?:number;knowledge?:MemoryKnowledge;lifecycle?:MemoryLifecycle}
export interface MemoryEvidenceEvent{id:string;index:number;ok:boolean;summary:string}
export interface MemoryTurnInput{turn:number;sceneId?:string;userMessage?:{id:string;content:string};assistantMessage:{id:string;content:string};candidates:MemoryCandidateInput[];events?:MemoryEvidenceEvent[];userId?:string}
export interface MemoryDecision{recordId:string;status:MemoryRecord['status'];reason:'user-quote'|'engine-event'|'duplicate'|'needs-review'|'invalid'}
export interface FactReferenceInput{claim:string;refs:string[]}
export interface FactReferenceVerdict extends FactReferenceInput{ok:boolean;invalidRefs:string[]}
export interface ContinuityPatchInput{confirmMemoryIds?:string[];resolveMemoryIds?:string[];reason?:string}
export interface ContinuityPatchRecord{id:string;turn:number;confirmMemoryIds:string[];resolveMemoryIds:string[];reason:string;status:'pending'|'applied'|'rejected'}

const kinds=new Set<MemoryKind>(['engine-fact','event','promise','secret','relation','episode','summary']);
const clean=(value:unknown,max=500)=>typeof value==='string'?value.trim().slice(0,max):'';
const strings=(value:unknown,maxItems=12,maxChars=120)=>{const out:string[]=[],seen=new Set<string>();for(const item of Array.isArray(value)?value:[]){const text=clean(item,maxChars);if(!text||seen.has(text))continue;seen.add(text);out.push(text);if(out.length>=maxItems)break;}return out;};
const scope=(value:string,userId:string)=>value==='user'?{kind:'user' as const,userId}:value.startsWith('entity:')?{kind:'entity' as const,entityId:value.slice(7)}:{kind:'public' as const};

export function ingestMemoryTurn(ledger:MemoryLedger,input:MemoryTurnInput):MemoryDecision[]{const decisions:MemoryDecision[]=[];if(!Number.isInteger(input.turn)||input.turn<0)return[{recordId:'',status:'rejected',reason:'invalid'}];const events=(input.events??[]).filter(event=>event.ok),userText=input.userMessage?.content??'';for(const[ordinal,candidate]of(input.candidates.slice(0,12).entries())){const text=clean(candidate?.text),quote=clean(candidate?.evidenceQuote,300),requested=new Set(strings(candidate?.eventIds,8)),matched=events.filter(event=>requested.has(event.id)),quoteVerified=quote.length>=4&&userText.includes(quote),stored=matched.length?matched.map(event=>clean(event.summary)).filter(Boolean).join(' / '):quoteVerified?quote:text;if(!stored){decisions.push({recordId:'',status:'rejected',reason:'invalid'});continue;}const duplicate=ledger.all().find(record=>record.status!=='rejected'&&record.text.normalize('NFKC').toLowerCase()===stored.normalize('NFKC').toLowerCase());if(duplicate){decisions.push({recordId:duplicate.id,status:duplicate.status,reason:'duplicate'});continue;}const id=`narrative:${input.turn}:${input.assistantMessage.id}:${ordinal}`,status=quoteVerified||matched.length?'approved':'candidate',kind=kinds.has(candidate.kind as MemoryKind)?candidate.kind as MemoryKind:'episode',knowledgeScope=clean(candidate.knowledgeScope,100),record:MemoryRecord={id,text:stored,validFromTurn:input.turn,validToTurn:null,scope:scope(knowledgeScope,input.userId??'user'),evidence:[...(quoteVerified&&input.userMessage?.id?[{kind:'message' as const,id:input.userMessage.id}]:[]),{kind:'message',id:input.assistantMessage.id},...matched.map(event=>({kind:'event' as const,id:String(event.index)}))],status,kind,sourceMessageIds:[...(quoteVerified&&input.userMessage?.id?[input.userMessage.id]:[]),input.assistantMessage.id],sourceEventIndexes:matched.map(event=>event.index),entities:strings(candidate.entities),createdTurn:input.turn,supersedes:[],importance:Math.max(0,Math.min(1,Number.isFinite(Number(candidate.importance))?Number(candidate.importance):.5)),canonicalAnchors:strings([candidate.canonicalKey,...(candidate.entities??[])]),...(input.sceneId?{sceneId:input.sceneId,sourceLocator:{sceneId:input.sceneId}}:{}),...(candidate.knowledge?{knowledge:candidate.knowledge}:{}),...(candidate.lifecycle?{lifecycle:candidate.lifecycle}:{})};ledger.add(record);decisions.push({recordId:id,status,reason:matched.length?'engine-event':quoteVerified?'user-quote':'needs-review'});}return decisions;}

export function reconcileMemorySources(ledger:MemoryLedger,input:{messageIds:string[];eventIndexes:number[];atTurn:number}){const messages=new Set(input.messageIds),events=new Set(input.eventIndexes),removed:string[]=[];for(const record of ledger.all()){const messageSources=record.sourceMessageIds??record.evidence.filter(item=>item.kind==='message').map(item=>item.id),eventSources=record.sourceEventIndexes??record.evidence.filter(item=>item.kind==='event').map(item=>Number(item.id)).filter(Number.isInteger),had=messageSources.length>0||eventSources.length>0,live=eventSources.length?eventSources.some(index=>events.has(index)):messageSources.some(id=>messages.has(id));if(had&&!live&&record.status!=='rejected'&&record.status!=='superseded'){ledger.supersede(record.id,Math.max(record.validFromTurn,input.atTurn));removed.push(record.id);}}return removed;}

export function validateFactReferences(input:FactReferenceInput[]|undefined,context:{hasState:boolean;userMessageId?:string;events?:MemoryEvidenceEvent[]}):FactReferenceVerdict[]{const eventIds=new Set((context.events??[]).filter(event=>event.ok).map(event=>event.id));return(input??[]).slice(0,20).map(item=>{const claim=clean(item?.claim,300),refs=strings(item?.refs),invalidRefs=refs.filter(ref=>ref==='state'?!context.hasState:ref==='user-message'?!context.userMessageId:ref.startsWith('event:')?!eventIds.has(ref.slice(6)):true);return{claim,refs,ok:!!claim&&!!refs.length&&!invalidRefs.length,invalidRefs};});}

export class ContinuityPatchLedger{#patches:ContinuityPatchRecord[]=[];all(){return structuredClone(this.#patches);}reset(value:ContinuityPatchRecord[]=[]){this.#patches=structuredClone(value);}propose(input:ContinuityPatchInput|undefined,turn:number,knownIds:string[]){const known=new Set(knownIds),confirmMemoryIds=strings(input?.confirmMemoryIds,20).filter(id=>known.has(id)),resolveMemoryIds=strings(input?.resolveMemoryIds,20).filter(id=>known.has(id));if(!confirmMemoryIds.length&&!resolveMemoryIds.length)return null;const patch:ContinuityPatchRecord={id:`continuity-patch-${turn}-${this.#patches.length+1}`,turn,confirmMemoryIds,resolveMemoryIds,reason:clean(input?.reason,300),status:'pending'};this.#patches.push(patch);return structuredClone(patch);}apply(id:string,ledger:MemoryLedger,turn:number){const patch=this.#required(id);if(patch.status!=='pending')throw new Error(`continuity_patch_not_pending:${id}`);for(const memoryId of patch.confirmMemoryIds)if(ledger.get(memoryId)?.status==='candidate')ledger.approve(memoryId);for(const memoryId of patch.resolveMemoryIds){const record=ledger.get(memoryId);if(record&&record.status!=='rejected')ledger.supersede(memoryId,Math.max(turn,record.validFromTurn));}patch.status='applied';return structuredClone(patch);}reject(id:string){const patch=this.#required(id);if(patch.status!=='pending')throw new Error(`continuity_patch_not_pending:${id}`);patch.status='rejected';return structuredClone(patch);}#required(id:string){const patch=this.#patches.find(value=>value.id===id);if(!patch)throw new Error(`continuity_patch_not_found:${id}`);return patch;}}
