import type { EvidenceReference, KnowledgeScope, MemoryArchivePage, MemoryKind, MemoryKnowledge, MemoryLifecycle, MemoryRecord, MemorySourceLocator } from '@simbot/contracts';

export interface Viewer { userId?: string; entityIds?: readonly string[] }
export interface Retrieval { records: MemoryRecord[]; abstained: boolean; reason?: string }
export interface ScoredMemory { record: MemoryRecord; evidenceScore: number }

export class MemoryLedger {
  #records = new Map<string, MemoryRecord>();
  #archivePages: MemoryArchivePage[] = [];
  add(record: MemoryRecord){validate(record);this.#records.set(record.id,structuredClone(record));}
  reset(records: MemoryRecord[],archivePages:readonly MemoryArchivePage[]=[]){this.#records.clear();for(const record of records)this.add(record);this.#archivePages=structuredClone([...archivePages]);}
  approve(id: string){const value=this.#required(id);this.#records.set(id,{...value,status:'approved'});}
  reject(id: string){const value=this.#required(id);this.#records.set(id,{...value,status:'rejected'});}
  supersede(id: string,turn: number){const value=this.#records.get(id);if(value){this.#records.set(id,{...value,status:'superseded',validToTurn:turn,lifecycle:{...value.lifecycle,state:'superseded',timeScope:'past'}});return;}for(let pageIndex=0;pageIndex<this.#archivePages.length;pageIndex+=1){const page=this.#archivePages[pageIndex]!,recordIndex=page.records.findIndex((record)=>record.id===id);if(recordIndex<0)continue;const records=[...page.records],record=records[recordIndex]!;records[recordIndex]={...record,status:'superseded',validToTurn:turn,lifecycle:{...record.lifecycle,state:'superseded',timeScope:'past'}};this.#archivePages[pageIndex]={...page,records};return;}throw new Error(`memory_not_found:${id}`);}
  replace(record: MemoryRecord,turn: number){const anchors=new Set(record.canonicalAnchors??[]),supersedes:string[]=[];if(record.status!=='approved'||!anchors.size)throw new Error('memory_replacement_requires_approved_anchor');for(const value of this.#records.values())if(value.status==='approved'&&(value.canonicalAnchors??[]).some((anchor)=>anchors.has(anchor))){this.supersede(value.id,turn);supersedes.push(value.id);}this.add({...record,supersedes,lifecycle:{...record.lifecycle,state:'active',timeScope:'current'}});if(record.kind==='engine-fact')this.#compactEngineAnchors(anchors,1);}
  get(id: string){const value=this.#records.get(id)??this.#archivePages.flatMap((page)=>page.records).find((record)=>record.id===id);return value?structuredClone(value):null;}
  all(){return[...this.#records.values()].map((value)=>structuredClone(value));}
  allStored(){return[...this.all(),...this.#archivePages.flatMap((page)=>page.records).map((record)=>structuredClone(record))];}
  archivePages(){return structuredClone(this.#archivePages);}
  // 체크포인트는 외부에 노출되지 않는 불변 레코드 참조를 공유한다. 원장의 모든 변경 메서드는
  // 기존 객체를 수정하지 않고 Map의 값을 교체하므로, 과거 체크포인트는 이후 행동에도 변하지 않는다.
  checkpoint(){return[...this.#records.values()];}
  archiveCheckpoint(){return this.#archivePages;}
  archiveNarrativeMemories(currentTurn:number,options:{minimumAge?:number;maxActive?:number;pageSize?:number}={}){const minimumAge=options.minimumAge??300,maxActive=options.maxActive??600,pageSize=options.pageSize??100,candidates=[...this.#records.values()].filter((record)=>record.status==='approved'&&['event','episode','summary'].includes(record.kind??'summary')&&currentTurn-record.validFromTurn>=minimumAge).sort((a,b)=>a.validFromTurn-b.validFromTurn||a.id.localeCompare(b.id)),excess=Math.max(0,this.#records.size-maxActive),moving=candidates.slice(0,excess);for(let offset=0;offset<moving.length;offset+=pageSize){const records=moving.slice(offset,offset+pageSize),fromTurn=Math.min(...records.map((record)=>record.validFromTurn)),toTurn=Math.max(...records.map((record)=>record.validToTurn??record.validFromTurn)),keywords=[...new Set(records.flatMap((record)=>tokens(record.text)))].sort();this.#archivePages.push({id:`memory-page:${fromTurn}:${toTurn}:${this.#archivePages.length}`,fromTurn,toTurn,keywords,records:structuredClone(records)});}for(const record of moving)this.#records.delete(record.id);return moving.length;}
  // 엔진 사실의 원본 감사 기록은 이벤트 저널에 영구 보존된다. 기억 검색에는 앵커별 현재값과
  // 직전값만 남겨 오래 플레이해도 저장/undo가 같은 사실의 수천 사본을 복제하지 않게 한다.
  compactEngineFacts(maxPastPerAnchor=1){const anchors=new Set<string>();for(const value of this.#records.values())if(value.kind==='engine-fact')for(const anchor of value.canonicalAnchors??[])anchors.add(anchor);return this.#compactEngineAnchors(anchors,maxPastPerAnchor);}
  eligible(turn: number,viewer: Viewer={},includePast=false){return[...this.#records.values()].filter((value)=>(value.status==='approved'||value.status==='superseded'&&(includePast||value.validToTurn==null||value.validToTurn>=turn))&&value.validFromTurn<=turn&&(includePast||value.validToTurn==null||value.validToTurn>=turn)&&visible(value,viewer)).map((value)=>structuredClone(value));}
  searchable(query:string,turn:number,viewer:Viewer={},includePast=false){const terms=tokens(query),active=this.eligible(turn,viewer,includePast),archived=this.#archivePages.filter((page)=>terms.some((term)=>page.keywords.some((word)=>word===term||word.includes(term)||term.includes(word)))).flatMap((page)=>page.records).filter((record)=>(record.status==='approved'||record.status==='superseded'&&includePast)&&record.validFromTurn<=turn&&(includePast||record.validToTurn==null||record.validToTurn>=turn)&&visible(record,viewer));return[...active,...archived.map((record)=>structuredClone(record))];}
  score(query: string,turn: number,viewer: Viewer={},includePast=false){const terms=tokens(query);return this.searchable(query,turn,viewer,includePast).map((record)=>({record,evidenceScore:lexicalScore(terms,tokens(record.text))})).filter((entry)=>entry.evidenceScore>0).sort((a,b)=>b.evidenceScore-a.evidenceScore||b.record.validFromTurn-a.record.validFromTurn||a.record.id.localeCompare(b.record.id));}
  retrieve(query: string,turn: number,viewer: Viewer={},limit=8): Retrieval {const records=this.score(query,turn,viewer).slice(0,limit).map(({record})=>record);return records.length?{records,abstained:false}:{records:[],abstained:true,reason:'insufficient_grounding'};}
  #compactEngineAnchors(anchors:Set<string>,maxPast:number){let removed=0;for(const anchor of anchors){const past=[...this.#records.values()].filter((value)=>value.kind==='engine-fact'&&value.status==='superseded'&&(value.canonicalAnchors??[]).includes(anchor)).sort((a,b)=>(b.validToTurn??b.validFromTurn)-(a.validToTurn??a.validFromTurn)||b.validFromTurn-a.validFromTurn||b.id.localeCompare(a.id));for(const value of past.slice(Math.max(0,maxPast)))if(this.#records.delete(value.id))removed+=1;}return removed;}
  #required(id: string){const value=this.#records.get(id);if(!value)throw new Error(`memory_not_found:${id}`);return value;}
}

function validate(value: MemoryRecord){if(!value.id||!value.text.trim())throw new Error('memory_invalid');if(!value.evidence.length)throw new Error('memory_evidence_required');if(value.validFromTurn<0||value.validToTurn!=null&&value.validToTurn<value.validFromTurn)throw new Error('memory_interval_invalid');}
function visible(value:MemoryRecord,viewer: Viewer){const scope=value.scope;if(scope.kind==='user'&&scope.userId!==viewer.userId)return false;if(scope.kind==='entity'&&!(viewer.entityIds??[]).includes(scope.entityId))return false;const knowledge=value.knowledge,entities=viewer.entityIds??[];if(knowledge?.state==='hidden'||knowledge?.state==='forgotten')return false;if(knowledge?.visibleToEntityIds?.length&&!knowledge.visibleToEntityIds.some((id)=>entities.includes(id)))return false;if(knowledge?.deniedToEntityIds?.some((id)=>entities.includes(id)))return false;if((knowledge?.privacy==='private'||knowledge?.privacy==='secret'||knowledge?.privacy==='internal')&&knowledge.holderEntityIds?.length&&!knowledge.holderEntityIds.some((id)=>entities.includes(id)))return false;return true;}
function tokens(value: string){return[...new Set(value.toLowerCase().match(/[가-힣]{2,}|[a-z0-9_-]{2,}/g)??[])];}
function lexicalScore(query: string[],document: string[]){return query.reduce((total,term)=>total+(document.some((value)=>value===term||value.includes(term)||term.includes(value))?1:0),0)/Math.max(1,query.length);}
export function memoryRecord(input: {id:string;text:string;turn:number;scope?:KnowledgeScope;evidence:EvidenceReference[];status?:MemoryRecord['status'];kind?:MemoryKind;sourceMessageIds?:readonly string[];sourceEventIndexes?:readonly number[];entities?:readonly string[];supersedes?:readonly string[];importance?:number;canonicalAnchors?:readonly string[];sceneId?:string;sourceLocator?:MemorySourceLocator;knowledge?:MemoryKnowledge;lifecycle?:MemoryLifecycle}): MemoryRecord {return{id:input.id,text:input.text,validFromTurn:input.turn,validToTurn:null,scope:input.scope??{kind:'public'},evidence:input.evidence,status:input.status??'candidate',...(input.kind?{kind:input.kind}:{}),...(input.sourceMessageIds?{sourceMessageIds:input.sourceMessageIds}:{}),...(input.sourceEventIndexes?{sourceEventIndexes:input.sourceEventIndexes}:{}),...(input.entities?{entities:input.entities}:{}),createdTurn:input.turn,...(input.supersedes?{supersedes:input.supersedes}:{}),...(input.importance!=null?{importance:input.importance}:{}),...(input.canonicalAnchors?{canonicalAnchors:input.canonicalAnchors}:{}),...(input.sceneId?{sceneId:input.sceneId}:{}),...(input.sourceLocator?{sourceLocator:input.sourceLocator}:{}),...(input.knowledge?{knowledge:input.knowledge}:{}),...(input.lifecycle?{lifecycle:input.lifecycle}:{})};}

export * from './abstention.ts';
export * from './embedding-cache.ts';
export * from './planner.ts';
export * from './semantic.ts';
export * from './narrative-verifier.ts';
export * from './continuity.ts';
export * from './providers/fixed.ts';
