<script lang="ts">
  import Button from '@simbot/ui/Button.svelte'; import Panel from '@simbot/ui/Panel.svelte'; import { createSimPack, packSimPack, unpackSimPack, type SimPackProject } from '@simbot/simpack'; import { ProjectRuntime, runtimeFromManifest } from '@simbot/runtime'; import ScreenRenderer from '../player/ScreenRenderer.svelte';
  let project=$state<SimPackProject>(blank()); let revision=$state(0); let section=$state('basics'); let error=$state(''); let stateText=$state('{}'); const sections: [string,string][]=[['basics','기본 정보'],['state','초기 상태'],['modules','모듈'],['screens','화면'],['review','검토·저장']];
  let manifest=$derived(project.manifest as unknown as Record<string,unknown>); let runtime=$derived.by(()=>{try{return new ProjectRuntime(runtimeFromManifest(manifest));}catch{return null;}});
  function blank(){return createSimPack({id:'new-project',title:'새 프로젝트',schema:{meta:{id:'new-project'},progression:{sources:{train:[5,5]},thresholds:[20]},initialState:{day:1,gold:0,player:{level:1,exp:0}}},screens:chatScreens(),navigation:[{id:'play',screenId:'play',label:'플레이'}],characters:[{id:'primary',name:'새 캐릭터',description:''}]});}
  function mutate(change:(value:Record<string,unknown>)=>void){const next=structuredClone(project.manifest) as unknown as Record<string,unknown>;change(next);next.revision=Number(next.revision??0)+1;project={manifest:next as unknown as SimPackProject['manifest'],files:project.files};revision+=1;error='';}
  async function open(event:Event){const input=event.currentTarget as HTMLInputElement,file=input.files?.[0];if(!file)return;try{project=unpackSimPack(new Uint8Array(await file.arrayBuffer()));stateText=JSON.stringify(((project.manifest.runtime.schema as Record<string,unknown>)?.initialState??{}),null,2);revision+=1;}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function saveState(){try{const parsed=JSON.parse(stateText) as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('초기 상태는 객체여야 합니다.');mutate((value)=>{const runtime=value.runtime as Record<string,unknown>,schema=runtime.schema as Record<string,unknown>;schema.initialState=parsed;runtime.initialState=parsed;});}catch(reason){error=reason instanceof Error?reason.message:String(reason);}}
  function preset(id:string){mutate((value)=>{const runtime=value.runtime as Record<string,unknown>;runtime.screens=id==='dashboard'?[{id:'dashboard',title:'대시보드',layout:'dashboard',regions:{hud:[{widget:'detail-panel',source:'engine:progression/summary'}],main:[{widget:'chat'}],actions:[{widget:'action-group',actions:[{label:'훈련',event:{id:'progression/gain',params:{source:'train'}}}]}]}}]:chatScreens();runtime.navigation=[{id:'play',screenId:id==='dashboard'?'dashboard':'play',label:'플레이'}];});}
  function download(){const bytes=packSimPack(project),buffer=bytes.slice().buffer as ArrayBuffer,url=URL.createObjectURL(new Blob([buffer],{type:'application/zip'})),link=document.createElement('a');link.href=url;link.download=`${project.manifest.title}.simpack`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function chatScreens(){return[{id:'play',title:'대화',layout:'stage-chat-sidebar',regions:{main:[{widget:'chat'}]}}];}
</script>
<div class="editor"><aside><label class="open">SimPack 열기<input type="file" accept=".simpack" onchange={open}/></label>{#each sections as item}<button class:active={section===item[0]} onclick={()=>section=item[0]}>{item[1]}</button>{/each}</aside><div class="form"><h1>{project.manifest.title}</h1>{#if error}<p class="error">{error}</p>{/if}{#if section==='basics'}<Panel title="프로젝트 기본 정보"><label>프로젝트 이름<input value={project.manifest.title} oninput={(event)=>mutate((value)=>value.title=(event.currentTarget as HTMLInputElement).value)}/></label><p>원본 카드와 호환 정보는 폼 수정과 별도로 보존됩니다.</p></Panel>{:else if section==='state'}<Panel title="초기 상태"><textarea bind:value={stateText} rows="18"></textarea><Button onclick={saveState}>검증하고 저장</Button></Panel>{:else if section==='modules'}<Panel title="모듈"><pre>{JSON.stringify((manifest.modules as Record<string,unknown>)?.installed??[],null,2)}</pre><p>실행 코드 권한은 자동 승인하지 않습니다.</p></Panel>{:else if section==='screens'}<Panel title="화면 프리셋"><div class="actions"><Button onclick={()=>preset('chat')}>대화 중심</Button><Button variant="secondary" onclick={()=>preset('dashboard')}>대시보드</Button></div></Panel>{:else}<Panel title="검토·저장"><p>revision {project.manifest.revision}</p><Button onclick={download}>SimPack 저장</Button></Panel>{/if}</div><div class="preview">{#if runtime}<ScreenRenderer {runtime} version={revision}/>{:else}<Panel title="미리보기 불가"><p>스키마를 확인하세요.</p></Panel>{/if}</div></div>
<style>.editor{display:grid;grid-template-columns:12rem minmax(18rem,1fr) minmax(22rem,1.2fr);gap:var(--space-4)}aside{display:flex;flex-direction:column;gap:var(--space-2)}aside button,.open{min-height:2.5rem;padding:var(--space-2) var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:transparent;color:var(--color-text);text-align:left;cursor:pointer}.open input{position:absolute;opacity:0;width:1px}.active{border-color:var(--color-accent)!important}.form,.preview{min-width:0}.form{display:flex;flex-direction:column;gap:var(--space-4)}label{display:grid;gap:var(--space-2)}input,textarea{width:100%;padding:var(--space-3);border:1px solid var(--color-line);border-radius:var(--radius-md);background:var(--color-inset);color:var(--color-text)}textarea,pre{font:12px var(--font-mono);white-space:pre-wrap;overflow:auto}.actions{display:flex;gap:var(--space-2)}.error{color:var(--color-danger)}@media(max-width:1000px){.editor{grid-template-columns:10rem 1fr}.preview{grid-column:1/-1}}@media(max-width:640px){.editor{grid-template-columns:1fr}aside{flex-direction:row;overflow-x:auto}.preview{grid-column:1}}</style>
