import { describe,expect,it } from 'vitest';
import { createRng,type RuntimeRecord } from '@simbot/kernel';
import { createStandardRegistry } from '../src/index.ts';

const schema:RuntimeRecord={combat:{d:20,minDamage:1,critMult:2,guardMult:.5,fleeRate:50,heavyRate:30,heavyMult:1.5,heavyAcc:-2,defeatReviveRatio:.2,expTable:{E:[10,10]},lootGold:{E:[5,5]}},ladders:[{id:'player_level',thresholds:[100]}],skills:{power_strike:{pool:'mp',cost:3,power:5,acc:1}}};
const initial=():RuntimeRecord=>({gold:0,resources:{},items:{},player:{level:1,exp:0,atk:12,def:2,evade:10,acc:20,pools:{hp:{cur:30,max:30},mp:{cur:5,max:5}},dead:false},combat:null,pendingQuest:null});

describe('turn based combat module',()=>{
  it('owns the complete deterministic encounter lifecycle',()=>{const registry=createStandardRegistry(),rng=createRng(7);let state=initial();let result=registry.dispatch(schema,state,{id:'start_encounter',params:{enemies:[{name:'goblin',hp:6,def:0,evade:1,rank:'E'}]}},rng);expect(result.log[0]).toMatchObject({ok:true,event:'start_encounter'});state=result.state;result=registry.dispatch(schema,state,{id:'combat_action',params:{action:'attack',target:'e1'}},rng);expect(result.log[0]).toMatchObject({ok:true,cleared:true,damage:12});state=result.state;result=registry.dispatch(schema,state,{id:'end_encounter',params:{}},rng);expect(result.log[0]).toMatchObject({ok:true,outcome:'victory',expGained:10,goldGained:5});expect(result.state).toMatchObject({gold:5,combat:null,player:{exp:10}});});
  it('rejects LLM supplied damage and rolls back state and RNG',()=>{const registry=createStandardRegistry(),rng=createRng(11),before=rng.snapshot();let state=registry.dispatch(schema,initial(),{id:'start_encounter',params:{enemies:[{name:'goblin',hp:30}]}},rng).state;const afterStart=rng.snapshot(),result=registry.dispatch(schema,state,{id:'combat_action',params:{action:'attack',target:'e1',damage:999}},rng);expect(result.log[0]).toMatchObject({ok:false,reason:'combat_number_not_allowed'});expect(result.state).toEqual(state);expect(rng.snapshot()).toBe(afterStart);expect(before).not.toBe(afterStart);});
  it('applies guard once across an enemy turn and prepares next intents',()=>{const registry=createStandardRegistry(),rng=createRng(3);let state=registry.dispatch(schema,initial(),{id:'start_encounter',params:{enemies:[{name:'a',hp:20,atk:10,acc:20},{name:'b',hp:20,atk:10,acc:20}]}},rng).state;state=registry.dispatch(schema,state,{id:'combat_action',params:{action:'defend'}},rng).state;const result=registry.dispatch(schema,state,{id:'enemy_turn',params:{}},rng);const log=result.log[0] as RuntimeRecord,turns=log.results as RuntimeRecord[];expect(turns).toHaveLength(2);expect(Number(turns[0]?.damage)).toBeLessThanOrEqual(Number(turns[1]?.damage));expect((result.state.combat as RuntimeRecord).guard).toBe(false);});
});
