import { describe,expect,it } from 'vitest';
import { createRng,type RuntimeRecord } from '@simbot/kernel';
import { createStandardRegistry } from '../src/index.ts';

const schema:RuntimeRecord={combat:{d:20,minDamage:1,critMult:2,guardMult:.5,fleeRate:50,heavyRate:30,heavyMult:1.5,heavyAcc:-2,defeatReviveRatio:.2,expTable:{E:[10,10]},lootGold:{E:[5,5]}},ladders:[{id:'player_level',thresholds:[100]}],skills:{power_strike:{pool:'mp',cost:3,power:5,acc:1}}};
const initial=():RuntimeRecord=>({gold:0,resources:{},items:{},player:{level:1,exp:0,atk:12,def:2,evade:10,acc:20,pools:{hp:{cur:30,max:30},mp:{cur:5,max:5}},dead:false},combat:null,pendingQuest:null});

describe('turn based combat module',()=>{
  it('owns the complete deterministic encounter lifecycle',()=>{const registry=createStandardRegistry(),rng=createRng(7);let state=initial();let result=registry.dispatch(schema,state,{id:'start_encounter',params:{enemies:[{name:'goblin',hp:6,def:0,evade:1,rank:'E'}]}},rng);expect(result.log[0]).toMatchObject({ok:true,event:'start_encounter'});state=result.state;result=registry.dispatch(schema,state,{id:'combat_action',params:{action:'attack',target:'e1'}},rng);expect(result.log[0]).toMatchObject({ok:true,cleared:true,damage:12});state=result.state;result=registry.dispatch(schema,state,{id:'end_encounter',params:{}},rng);expect(result.log[0]).toMatchObject({ok:true,outcome:'victory',expGained:10,goldGained:5});expect(result.state).toMatchObject({gold:5,combat:null,player:{exp:10}});});
  it('rejects LLM supplied damage and rolls back state and RNG',()=>{const registry=createStandardRegistry(),rng=createRng(11),before=rng.snapshot();let state=registry.dispatch(schema,initial(),{id:'start_encounter',params:{enemies:[{name:'goblin',hp:30}]}},rng).state;const afterStart=rng.snapshot(),result=registry.dispatch(schema,state,{id:'combat_action',params:{action:'attack',target:'e1',damage:999}},rng);expect(result.log[0]).toMatchObject({ok:false,reason:'combat_number_not_allowed'});expect(result.state).toEqual(state);expect(rng.snapshot()).toBe(afterStart);expect(before).not.toBe(afterStart);});
  it('applies guard once across an enemy turn and prepares next intents',()=>{const registry=createStandardRegistry(),rng=createRng(3);let state=registry.dispatch(schema,initial(),{id:'start_encounter',params:{enemies:[{name:'a',hp:20,atk:10,acc:20},{name:'b',hp:20,atk:10,acc:20}]}},rng).state;state=registry.dispatch(schema,state,{id:'combat_action',params:{action:'defend'}},rng).state;const result=registry.dispatch(schema,state,{id:'enemy_turn',params:{}},rng);const log=result.log[0] as RuntimeRecord,turns=log.results as RuntimeRecord[];expect(turns).toHaveLength(2);expect(Number(turns[0]?.damage)).toBeLessThanOrEqual(Number(turns[1]?.damage));expect((result.state.combat as RuntimeRecord).guard).toBe(false);});
  it('returns the empty combat console contract when no encounter block exists',()=>{const value=createStandardRegistry().select('combat/console',schema,initial()) as RuntimeRecord;expect(value).toEqual({present:false,active:false,round:0,guard:false,cleared:false,fled:false,playerDead:false,pools:[],enemies:[],skills:[],fleeRate:50,canAct:false,end:{available:false,outcome:null}});});
  it('exposes normalized pools, living enemy intents and skill affordability',()=>{const state=initial(),player=state.player as RuntimeRecord;player.pools={hp:{cur:99,max:30},mp:{cur:-2,max:5},sp:{cur:3}};state.combat={active:true,round:4,guard:true,cleared:false,fled:false,enemies:[{id:'e1',name:'오우거',rank:'B',hp:{cur:7,max:10},dead:false},{id:'e2',name:'쓰러진 적',rank:null,hp:{cur:0,max:4},dead:true}],intents:{e1:'heavy',e2:'attack'}};const value=createStandardRegistry().select('combat/console',schema,state) as RuntimeRecord;expect(value).toMatchObject({present:true,active:true,round:4,guard:true,playerDead:false,fleeRate:50,canAct:true,pools:[{id:'hp',cur:30,max:30},{id:'mp',cur:0,max:5},{id:'sp',cur:3,max:3}],enemies:[{id:'e1',name:'오우거',rank:'B',hp:{cur:7,max:10},dead:false,intent:'heavy'},{id:'e2',dead:true,intent:null}],skills:[{id:'power_strike',label:'power_strike',pool:'mp',cost:3,affordable:false,reason:'MP 부족'}],end:{available:false,outcome:null}});});
  it.each([{flags:{active:true,cleared:true,fled:false},dead:false,outcome:'victory'},{flags:{active:false,cleared:false,fled:true},dead:false,outcome:'fled'},{flags:{active:true,cleared:false,fled:false},dead:true,outcome:'defeat'}] as const)('offers the matching end encounter outcome for $outcome',({flags,dead,outcome})=>{const state=initial(),player=state.player as RuntimeRecord;player.dead=dead;state.combat={...flags,round:2,guard:false,enemies:[],intents:{}};const value=createStandardRegistry().select('combat/console',schema,state) as RuntimeRecord;expect(value).toMatchObject({present:true,playerDead:dead,end:{available:true,outcome}});});
});
