import { describe, expect, it } from 'vitest';
import { createRng, createState, type RuntimeRecord } from '@simbot/kernel';
import { createHunterRegistry } from '../src/index.ts';
import { record } from '../src/support.ts';

const encounter={chance:100,enemies:[{name:'마수',hp:1,atk:0,def:0,evade:1,acc:0,rank:'E'}]};
const schema:RuntimeRecord={progression:{sources:{gate:[1,1]},thresholds:[100]},party:{maxSize:4,roles:['leader']},lootTables:[{id:'gate',entries:[{itemId:'mana_stone',qty:[1,1]}]}],entities:[{type:'npc',instances:[{id:'ally'}]}],combat:{heavyRate:0,expTable:{E:[1,1]},lootGold:{E:[1,1]}},hunter:{assessment:{defaultScore:120,variance:[0,0],ranks:[{id:'E',min:0,label:'E급'},{id:'D',min:100,label:'D급'}]},gates:[{id:'d-gate',name:'D급 게이트',minRank:'D',minParty:1,encounter,settlement:{gold:[50,50],exp:[5,5],manaStone:[2,2]}},{id:'legacy-gate',name:'구형 게이트',minRank:'D',minParty:1,settlement:{gold:[1,1],exp:[1,1],manaStone:[0,0]}}]},initialState:{day:1,gold:0,resources:{mana_stone:0},player:{level:1,exp:0,atk:20,acc:20,pools:{hp:{cur:30,max:30}}},party:{members:['ally'],formation:{}},hunter:{registered:true,rank:'D',activeGateId:null,clearedGateId:null}}};
const setup=(gateId='d-gate')=>{const registry=createHunterRegistry(),rng=createRng(17);let state=createState(schema,17);state=registry.dispatch(schema,state,{id:'hunter/gate-accept',params:{gateId}},rng).state;return{registry,rng,state};};

describe('Alternate Hunters V2 representative loop',()=>{
  it('starts a gate encounter and namespaces its combat and pending quest state',()=>{const{registry,rng,state}=setup();const result=registry.dispatch(schema,state,{id:'hunter/gate-raid',params:{gateId:'d-gate'}},rng);expect(result.log[0]).toMatchObject({ok:true,event:'hunter/gate-raid',gateId:'d-gate',encounter:true});expect(result.state).toMatchObject({combat:{active:true,gateId:'d-gate',questId:'gate:d-gate'},pendingQuest:{questId:'gate:d-gate',day:1}});});
  it('rejects an unconquered gate, then accepts victory proof and clears the pending quest',()=>{const{registry,rng,state}=setup();const rejected=registry.dispatch(schema,state,{id:'hunter/gate-clear',params:{gateId:'d-gate'}},rng);expect(rejected.log[0]).toMatchObject({ok:false,reason:'gate_not_conquered'});let next=registry.dispatch(schema,state,{id:'hunter/gate-raid',params:{gateId:'d-gate'}},rng).state;next=registry.dispatch(schema,next,{id:'combat_action',params:{action:'attack',target:'e1'}},rng).state;next=registry.dispatch(schema,next,{id:'end_encounter',params:{}},rng).state;expect(next.pendingQuest).toEqual({questId:'gate:d-gate',day:1,cleared:true});const cleared=registry.dispatch(schema,next,{id:'hunter/gate-clear',params:{gateId:'d-gate'}},rng);expect(cleared.log[0]).toMatchObject({ok:true,gateId:'d-gate'});expect(cleared.state.pendingQuest).toBeUndefined();});
  it('keeps encounter-free gates backward compatible',()=>{const{registry,rng,state}=setup('legacy-gate');const result=registry.dispatch(schema,state,{id:'hunter/gate-clear',params:{gateId:'legacy-gate'}},rng);expect(result.log[0]).toMatchObject({ok:true,gateId:'legacy-gate'});});
  it('exposes every stage availability and a Korean reason through hunter/status',()=>{const registry=createHunterRegistry(),base=createState(schema,17),initial=registry.select('hunter/status',schema,{...base,hunter:{registered:false}})as RuntimeRecord;expect(initial).toMatchObject({canRegister:true,canAssess:false,canRaid:false,canClear:false,canSettle:false,reason:'헌터 등록이 가능합니다.'});const assessable=registry.select('hunter/status',schema,{...base,hunter:{registered:true,rank:null}})as RuntimeRecord;expect(assessable).toMatchObject({canRegister:false,canAssess:true,reason:'헌터 등급 평가가 가능합니다.'});const accepted=setup().state,status=registry.select('hunter/status',schema,accepted)as RuntimeRecord;expect(status).toMatchObject({canRegister:false,canAssess:false,canRaid:true,canClear:false,canSettle:false,reason:'게이트 공략이 가능합니다.'});const conquered=registry.select('hunter/status',schema,{...accepted,pendingQuest:{questId:'gate:d-gate',day:1,cleared:true}})as RuntimeRecord;expect(conquered).toMatchObject({canRaid:false,canClear:true,canSettle:false,reason:'클리어 보고가 가능합니다.'});const cleared=registry.select('hunter/status',schema,{...accepted,hunter:{...record(accepted.hunter),clearedGateId:'d-gate'}})as RuntimeRecord;expect(cleared).toMatchObject({canRaid:false,canClear:false,canSettle:true,reason:'보상 정산이 가능합니다.'});});
  it('runs registration, assessment, gate raid, combat, clear, and settlement without app branches',()=>{const registry=createHunterRegistry(),rng=createRng(17);let state=createState(schema,17);state.hunter={registered:false};state.party={members:[],formation:{}};const step=(id:string,params:RuntimeRecord={})=>{const result=registry.dispatch(schema,state,{id,params},rng);expect(result.log[0]?.ok,`${id}: ${JSON.stringify(result.log)}`).toBe(true);state=result.state;};step('hunter/register',{name:'신규 헌터'});const injected=registry.dispatch(schema,state,{id:'hunter/assess',params:{score:9999}},rng);expect(injected.log[0]).toMatchObject({ok:false,reason:'hunter_score_not_allowed'});step('hunter/assess');step('party/add',{memberId:'ally'});step('hunter/gate-accept',{gateId:'d-gate'});step('hunter/gate-raid',{gateId:'d-gate'});step('combat_action',{action:'attack',target:'e1'});step('end_encounter');step('hunter/gate-clear',{gateId:'d-gate'});step('hunter/settle',{gateId:'d-gate'});expect(state).toMatchObject({gold:51,resources:{mana_stone:2},hunter:{registered:true,rank:'D',activeGateId:null,clearedGateId:null},player:{exp:6}});});
});
