import { describe,expect,it } from 'vitest';
import { createRng,type RuntimeRecord } from '@simbot/kernel';
import { createInnRegistry } from '../src/index.ts';

const schema:RuntimeRecord={staffing:{facility:'quarter',capacityByLevel:{'1':1,'2':3}},questBoard:{facility:'tavern',unlockLevel:2},quests:[{id:'herbs'}],entities:[{type:'facility',instances:[{id:'quarter',maxLevel:2,upgradeCosts:{'2':750000}},{id:'tavern',maxLevel:2,upgradeCosts:{'2':500000}}]},{type:'npc',instances:[{id:'silvia'}]},{type:'room',instances:[{no:'101',capacity:1,requiresRoomLevel:1,pricePerNight:30000}]},{type:'menuItem',instances:[{name:'stew',category:'food',price:5000}]}]};
const initial=():RuntimeRecord=>({gold:1_000_000,facilities:{quarter:1,tavern:1,room:1,kitchen:1},staff:[],rooms:{},resources:{food:2},items:{},npcs:{silvia:{}},player:{pools:{hp:{cur:10,max:10}}},combat:null});
const questSchema=():RuntimeRecord=>({...schema,questBoard:{},quests:[{id:'escort',name:'Escort',encounterChance:100,rewardTier:'E',check:{mode:'rate',rate:100}}],rewards:{gold:{E:[10,10]}},combat:{d:20,minDamage:1,critMult:2,guardMult:.5,fleeRate:100,heavyRate:30,heavyMult:1.5,heavyAcc:-2,defeatReviveRatio:.2,expTable:{E:[0,0]},lootGold:{E:[0,0]}},encounters:{pool:[{id:'wolves',name:'Wolf',rank:'E',count:[1,3]}]}});
const questInitial=():RuntimeRecord=>({...initial(),gold:0,day:3,seed:77,claimedRewards:[],player:{atk:100,acc:100,pools:{hp:{cur:30,max:30}}},pendingQuest:null});

describe('inn genre module',()=>{
  it('uses the configured staff quarters and supports wage changes',()=>{const registry=createInnRegistry(),rng=createRng(1);let state=initial();let result=registry.dispatch(schema,state,{id:'hire',params:{npcId:'silvia',dailyWage:5000}},rng);expect(result.log[0]).toMatchObject({ok:true,dailyWage:5000});state=result.state;result=registry.dispatch(schema,state,{id:'set_wage',params:{npcId:'silvia',dailyWage:10000}},rng);expect(result.log[0]).toMatchObject({ok:true,before:5000,dailyWage:10000});expect((result.state.staff as RuntimeRecord[])[0]).toMatchObject({npcId:'silvia',dailyWage:10000});});
  it('keeps the quest board hidden until the configured tavern upgrade',()=>{const registry=createInnRegistry(),rng=createRng(2);let state=initial();expect(registry.select('inn/quests',schema,state)).toEqual([]);state=registry.dispatch(schema,state,{id:'upgrade',params:{facility:'tavern'}},rng).state;expect(registry.select('inn/quests',schema,state)).toEqual([{id:'herbs'}]);});
  it('prevents free sales and preserves room capacity',()=>{const registry=createInnRegistry(),rng=createRng(3);let state=initial();state=registry.dispatch(schema,state,{id:'sale',params:{menuName:'stew',qty:2}},rng).state;expect(state).toMatchObject({gold:1_010_000,resources:{food:0}});state=registry.dispatch(schema,state,{id:'checkin',params:{roomNo:'101',guestName:'A',stayDays:2}},rng).state;const rejected=registry.dispatch(schema,state,{id:'checkin',params:{roomNo:'101',guestName:'B',stayDays:1}},rng);expect(rejected.log[0]).toMatchObject({ok:false,reason:'room_full'});expect(rejected.state).toEqual(state);});
  it('exposes only real incident choices and clears each lodging decision',()=>{const source:RuntimeRecord={...schema,traffic:{capacityFacility:'tavern',base:[[2,2]],capacity:[5],waves:[{id:'lunch',share:1}],incidents:{chance:100,deck:[{id:'thief',label:'thief',choices:[{id:'chase',label:'catch',effects:{}}]}]},lodging:{roomFacility:'room',roomsEntity:'room',base:[[2,2]],segments:[{id:'traveler',label:'traveler',weight:1,party:[1,1],stay:{'1':1}}]}}},rng=createRng(4),registry=createInnRegistry();let state=initial();const incident=registry.dispatch(source,state,{id:'traffic_wave',params:{wave:'lunch'}},rng);expect(incident.log[0]).toMatchObject({awaitingChoice:true,choices:[{id:'chase',label:'catch'}]});state=incident.state;state=registry.dispatch(source,state,{id:'incident_choice',params:{choice:'chase'}},rng).state;let review=registry.dispatch(source,state,{id:'lodging_review',params:{}},rng);expect((review.log[0] as RuntimeRecord).requests).toHaveLength(2);state=review.state;const requests=((state.lodging as RuntimeRecord).requests as RuntimeRecord[]),accepted=registry.dispatch(source,state,{id:'lodging_accept',params:{requestId:requests[0]?.id}},rng);expect(((registry.select('inn/traffic',source,accepted.state) as RuntimeRecord).lodging as RuntimeRecord[])).toHaveLength(1);expect((accepted.state.rooms as RuntimeRecord)['101']).toBeDefined();});
  it('rotates a deterministic quest board by day and owns quest rewards',()=>{const source:RuntimeRecord={...schema,questBoard:{facility:'tavern',unlockLevel:2,size:2},quests:['a','b','c','d'].map((id)=>({id,name:id,rewardTier:'E',check:{mode:'rate',rate:100}})),rewards:{gold:{E:[10,10]}}},registry=createInnRegistry(),rng=createRng(5);let state={...initial(),seed:77,facilities:{quarter:1,tavern:2,room:1,kitchen:1},claimedRewards:[]}as RuntimeRecord;const first=registry.select('inn/quests',source,state)as RuntimeRecord[];expect(first).toHaveLength(2);const result=registry.dispatch(source,state,{id:'attempt_quest',params:{questId:first[0]?.id}},rng);expect(result.log[0]).toMatchObject({ok:true,success:true,goldDelta:10});state={...result.state,day:2};const second=registry.select('inn/quests',source,state)as RuntimeRecord[];expect(second).toHaveLength(2);expect(second.map((value)=>value.id)).not.toEqual(first.map((value)=>value.id));});
  it('starts a quest encounter, clears it through combat, then pays on re-attempt',()=>{const source=questSchema(),registry=createInnRegistry(),rng=createRng(21);let result=registry.dispatch(source,questInitial(),{id:'attempt_quest',params:{questId:'escort'}},rng);expect(result.log[0]).toMatchObject({ok:true,encounter:'wolves'});expect((result.log[0] as RuntimeRecord).enemies).toEqual(expect.any(Array));expect(((result.log[0] as RuntimeRecord).enemies as RuntimeRecord[]).length).toBeGreaterThan(0);expect(result.log[0]).not.toHaveProperty('goldDelta');expect(result.state).toMatchObject({gold:0,combat:{active:true,questId:'escort'}});expect(result.state.pendingQuest).toEqual({questId:'escort',day:3});expect(result.state.questAttempts).toBeUndefined();for(const foe of ((result.state.combat as RuntimeRecord).enemies as RuntimeRecord[])){result=registry.dispatch(source,result.state,{id:'combat_action',params:{action:'attack',target:foe.id}},rng);expect(result.log[0]).toMatchObject({ok:true});}result=registry.dispatch(source,result.state,{id:'end_encounter',params:{}},rng);expect(result.log[0]).toMatchObject({ok:true,outcome:'victory'});expect(result.state.pendingQuest).toEqual({questId:'escort',day:3,cleared:true});result=registry.dispatch(source,result.state,{id:'attempt_quest',params:{questId:'escort'}},rng);expect(result.log[0]).toMatchObject({ok:true,success:true,goldDelta:10});expect(result.state.pendingQuest).toBeUndefined();});
  it('re-rolls the quest encounter after an unresolved flee without paying',()=>{const source=questSchema(),registry=createInnRegistry(),rng=createRng(22);let result=registry.dispatch(source,questInitial(),{id:'attempt_quest',params:{questId:'escort'}},rng);result=registry.dispatch(source,result.state,{id:'combat_action',params:{action:'flee'}},rng);expect(result.log[0]).toMatchObject({ok:true,fled:true});result=registry.dispatch(source,result.state,{id:'end_encounter',params:{}},rng);expect(result.state.pendingQuest).toEqual({questId:'escort',day:3});result=registry.dispatch(source,result.state,{id:'attempt_quest',params:{questId:'escort'}},rng);expect(result.log[0]).toMatchObject({ok:true,encounter:'wolves'});expect(((result.log[0] as RuntimeRecord).enemies as RuntimeRecord[]).length).toBeGreaterThan(0);expect(result.log[0]).not.toHaveProperty('goldDelta');expect(result.state.questAttempts).toBeUndefined();});
  it('falls back to immediate quest resolution without an encounter pool',()=>{const source=questSchema();delete source.encounters;const result=createInnRegistry().dispatch(source,questInitial(),{id:'attempt_quest',params:{questId:'escort'}},createRng(23));expect(result.log[0]).toMatchObject({ok:true,success:true,goldDelta:10});expect(result.state.combat).toBeNull();});
  it('derives identical quest encounters from equal seed, day, and quest id',()=>{const source=questSchema(),run=()=>createInnRegistry().dispatch(source,questInitial(),{id:'attempt_quest',params:{questId:'escort'}},createRng(24)),first=run(),second=run();expect(first.log[0]).toMatchObject({ok:true,encounter:'wolves'});expect(second.log[0]).toMatchObject({ok:true,encounter:'wolves'});expect((first.log[0] as RuntimeRecord).enemies).toEqual((second.log[0] as RuntimeRecord).enemies);});
  it('clears stale pending quest state when advancing to a new day',()=>{const state:RuntimeRecord={...questInitial(),clock:{day:3,hour:8,turn:0},pendingQuest:{questId:'escort',day:3}},result=createInnRegistry().dispatch(questSchema(),state,{id:'time/advance',params:{unit:'day'}},createRng(25));expect(result.log[0]).toMatchObject({ok:true,unit:'day'});expect(result.state.day).toBe(4);expect(result.state.pendingQuest).toBeUndefined();});
});
