import type { MemoryRecord } from '@simbot/contracts';
import { MemoryLedger } from '@simbot/memory';
import type { SessionRepository } from '@simbot/persistence';
import { compilePrompt,type CompiledPrompt,type Persona,type PromptPreset } from '@simbot/risu';
import type { ProjectRuntime } from '@simbot/runtime';

export interface ChatMessage{id:string;index:number;role:'user'|'assistant';content:string;createdAt:string;}
export interface ProposedEvent{id:string;params?:Record<string,unknown>;}
export interface NarrativeResponse{text:string;events?:ProposedEvent[];speakers?:Array<{npcId:string;emotion?:string}>;}
export interface ModelRequest{prompt:CompiledPrompt;signal?:AbortSignal;}
export interface ModelProvider{complete(request:ModelRequest):Promise<NarrativeResponse>;}
export interface SessionSnapshot{contract:'simbot-play-session/0.1';id:string;projectId:string;turn:number;messages:ChatMessage[];engine:{state:Record<string,unknown>;rng:number};memory:MemoryRecord[];lastLogs:Record<string,unknown>[];}
export interface PlaySessionOptions{id:string;runtime:ProjectRuntime;provider:ModelProvider;preset:PromptPreset;persona?:Persona|null;card:{name:string;description?:string;personality?:string;scenario?:string;systemPrompt?:string;postHistoryInstructions?:string};memory?:MemoryLedger;repository?:SessionRepository<SessionSnapshot>;historyWindow?:number;}

export class PlaySession{readonly id:string;readonly runtime:ProjectRuntime;readonly memory:MemoryLedger;readonly #provider:ModelProvider;readonly #preset:PromptPreset;readonly #persona:Persona|null;readonly #card:PlaySessionOptions['card'];readonly #repository:SessionRepository<SessionSnapshot>|undefined;readonly #historyWindow:number;#messages:ChatMessage[]=[];#turn=0;#lastLogs:Record<string,unknown>[]=[];#busy=false;
 constructor(options:PlaySessionOptions){this.id=options.id;this.runtime=options.runtime;this.#provider=options.provider;this.#preset=structuredClone(options.preset);this.#persona=options.persona?structuredClone(options.persona):null;this.#card=structuredClone(options.card);this.memory=options.memory??new MemoryLedger();this.#repository=options.repository;this.#historyWindow=Math.max(8,options.historyWindow??40);}
 get messages(){return this.#messages.map((value)=>({...value}));}get turn(){return this.#turn;}get busy(){return this.#busy;}get lastLogs(){return structuredClone(this.#lastLogs);}
 async send(content:string,signal?:AbortSignal){const text=content.trim();if(!text)throw new Error('message_empty');if(this.#busy)throw new Error('session_busy');this.#busy=true;try{this.#append('user',text);const prompt=this.#compile(text);const response=await this.#provider.complete({prompt,...(signal?{signal}:{})});if(!response||typeof response.text!=='string')throw new Error('model_response_invalid');this.#lastLogs=[];for(const event of response.events??[]){if(!event||!this.runtime.registry.hasEvent(event.id)){this.#lastLogs.push({ok:false,event:String(event?.id??''),reason:'unregistered_model_event'});continue;}const result=this.runtime.dispatch(event.id,event.params??{});this.#lastLogs.push(...result.log);}this.#append('assistant',response.text);this.#turn+=1;await this.save();return{response,logs:this.lastLogs,prompt};}finally{this.#busy=false;}}
 async save(){if(!this.#repository)return;await this.#repository.put({id:this.id,schemaHash:this.runtime.project.projectId,title:this.#card.name,updatedAt:Date.now(),payload:this.snapshot()});}
 snapshot():SessionSnapshot{return{contract:'simbot-play-session/0.1',id:this.id,projectId:this.runtime.project.projectId,turn:this.#turn,messages:this.messages,engine:this.runtime.snapshot(),memory:this.memory.all(),lastLogs:this.lastLogs};}
 restore(value:SessionSnapshot){if(value.contract!=='simbot-play-session/0.1'||value.projectId!==this.runtime.project.projectId)throw new Error('session_snapshot_incompatible');this.#turn=value.turn;this.#messages=structuredClone(value.messages);this.#lastLogs=structuredClone(value.lastLogs);this.runtime.restore(value.engine);for(const record of value.memory)this.memory.add(record);}
 #append(role:'user'|'assistant',content:string){this.#messages.push({id:`m${this.#messages.length+1}`,index:this.#messages.length,role,content,createdAt:new Date().toISOString()});}
 #compile(query:string){const retrieval=this.memory.retrieve(query,this.#turn,{},8),memory=retrieval.records.map((value)=>`- ${value.text} [${value.evidence.map((item)=>`${item.kind}:${item.id}`).join(', ')}]`).join('\n');return compilePrompt({preset:this.#preset,persona:this.#persona,card:this.#card,chat:this.#messages.slice(-this.#historyWindow).map(({role,content})=>({role,content})),memory,engineContext:{facts:`다음 JSON은 엔진이 소유한 현재 사실이다. 서사로 수치를 바꾸지 말고 이벤트 결과만 따른다.\n${JSON.stringify(this.runtime.state)}`,availableActions:`실행 가능한 이벤트 ID: ${this.runtime.registry.eventIds().join(', ')}. 결정 카드가 있는 경우 본문에 별도 번호 선택지를 만들지 않는다.`,groundedMemory:retrieval.abstained?'관련 근거가 부족하므로 과거 사실을 추측하지 않는다.':memory}});}}
