'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { createSimPack, packSimPack, unpackSimPack } = require('../core/simpack/simpack.js');
const { setBasics, setInitialState, setModuleEnabled, setScreenPreset, updateLoreEntries, validateEditorProject } = require('../core/editor/projectEditor.js');
function sample() { return createSimPack({ id: 'sample', title: 'Sample', schema: { meta: { id: 'sample' }, initialState: { day: 1 } }, characters: [{ id: 'hero', name: 'Hero' }], lorebooks: [{ entries: [{ id: 'town', name: 'Town', keys: ['town'], content: 'old', enabled: true }] }], installedModules: [{ id: 'core.time', version: '1.0.0', enabled: true }] }); }
test('폼 편집은 원본 프로젝트를 변이하지 않고 revision과 기본 정보를 갱신한다', () => { const before = sample(); const after = setBasics(before, { title: '새 게임', name: '용사', description: '설명' }); assert.equal(before.manifest.title, 'Sample'); assert.equal(after.manifest.title, '새 게임'); assert.equal(after.manifest.content.characters[0].name, '용사'); assert.equal(after.manifest.revision, 2); });
test('초기 상태·모듈·로어·화면 프리셋을 폼 계약으로 편집한다', () => { let project = sample(); project = setInitialState(project, { day: 3, gold: 20 }); project = setModuleEnabled(project, 'core.time', false); project = updateLoreEntries(project, [{ id: 'town', keys: '마을, 광장', content: 'new', enabled: true }]); project = setScreenPreset(project, 'adventure'); assert.equal(project.manifest.runtime.schema.initialState.day, 3); assert.equal(project.manifest.modules.installed[0].enabled, false); assert.deepEqual(project.manifest.content.lorebooks[0].entries[0].keys, ['마을', '광장']); assert.equal(project.manifest.runtime.screens.length, 2); assert.deepEqual(validateEditorProject(project), []); });
test('편집한 결과는 SimPack으로 저장하고 다시 열어도 유지된다', () => { const project = setScreenPreset(setBasics(sample(), { title: '왕복', name: 'A' }), 'chat'); const restored = unpackSimPack(packSimPack(project)); assert.equal(restored.manifest.title, '왕복'); assert.equal(restored.manifest.runtime.screens[0].id, 'play'); });
test('초기 상태에는 객체만 허용하고 알 수 없는 화면 프리셋은 거부한다', () => { assert.throws(() => setInitialState(sample(), []), /initial_state_object_required/); assert.throws(() => setScreenPreset(sample(), 'unknown'), /unknown_screen_preset/); });
