import { cloneState } from './clone.ts';
import type { DeterministicRng } from './rng.ts';

export type RuntimeRecord = Record<string, unknown>;
export interface LegacyLogEntry extends RuntimeRecord { ok: boolean; event: string; }
export interface DispatchResult<TState extends RuntimeRecord = RuntimeRecord> { state: TState; log: LegacyLogEntry[]; }
export interface HandlerContext<TState extends RuntimeRecord = RuntimeRecord> { schema: RuntimeRecord; state: TState; event: RuntimeEvent; params: RuntimeRecord; rng: DeterministicRng; registry: ModuleRegistry; module: NormalizedModule; }
export type EventHandler = (context: HandlerContext) => DispatchResult;
export type SelectorHandler = (...args: unknown[]) => unknown;
export type ProcessHandler = (...args: unknown[]) => unknown;
export interface RuntimeEvent extends RuntimeRecord { id: string; params?: RuntimeRecord; }
export interface ModuleDefinition { id: string; version: string; dependencies?: readonly string[]; stateAccess?: Partial<StateAccess>; events?: Record<string, EventHandler>; selectors?: Record<string, SelectorHandler>; processes?: Record<string, ProcessHandler>; initialState?: (schema: RuntimeRecord) => RuntimeRecord; promptFacts?: (schema: RuntimeRecord, state: RuntimeRecord) => unknown; migrations?: RuntimeRecord; }
export interface StateAccess { owns: readonly string[]; reads: readonly string[]; writes: readonly string[]; }
export interface NormalizedModule extends ModuleDefinition { dependencies: readonly string[]; stateAccess: StateAccess; events: Readonly<Record<string, EventHandler>>; selectors: Readonly<Record<string, SelectorHandler>>; processes: Readonly<Record<string, ProcessHandler>>; migrations: RuntimeRecord; }
interface Route<T> { module: NormalizedModule; handler: T; }

export class ModuleRegistry {
  readonly #modules = new Map<string, NormalizedModule>(); readonly #events = new Map<string, Route<EventHandler>>(); readonly #selectors = new Map<string, Route<SelectorHandler>>(); readonly #processes = new Map<string, Route<ProcessHandler>>(); readonly #stateOwners = new Map<string, string>();
  register(definition: ModuleDefinition): this { const module = normalizeModule(definition); if (this.#modules.has(module.id)) throw new Error(`duplicate_module:${module.id}`); for (const dependency of module.dependencies) if (!this.#modules.has(dependency)) throw new Error(`missing_module_dependency:${module.id}:${dependency}`); this.#assertRoutes(this.#events, module.events, 'event'); this.#assertRoutes(this.#selectors, module.selectors, 'selector'); this.#assertRoutes(this.#processes, module.processes, 'process'); for (const path of module.stateAccess.owns) { const owner = this.#stateOwners.get(path); if (owner) throw new Error(`duplicate_state_owner:${path}:${owner}`); } this.#modules.set(module.id, module); this.#registerRoutes(this.#events, module, module.events); this.#registerRoutes(this.#selectors, module, module.selectors); this.#registerRoutes(this.#processes, module, module.processes); for (const path of module.stateAccess.owns) this.#stateOwners.set(path, module.id); return this; }
  dispatch<TState extends RuntimeRecord>(schema: RuntimeRecord, state: TState, event: RuntimeEvent, rng: DeterministicRng): DispatchResult<TState> { const route = this.#events.get(event.id); if (!route) return unknownEvent(state, event.id); const workingState = cloneState(state); const snapshot = rng.snapshot(); let result: DispatchResult; try { result = route.handler({ schema, state: workingState, event, params: event.params ?? event, rng, registry: this, module: route.module }); } catch (error: unknown) { rng.restore(snapshot); return moduleFailure(state, event.id, 'module_exception', error instanceof Error ? error.message : String(error)); } if (!validResult(result)) { rng.restore(snapshot); return moduleFailure(state, event.id, 'module_contract', 'Module must return { state, log[] }.'); } if (!result.log.some((entry) => entry.ok)) { rng.restore(snapshot); return { state, log: result.log } as DispatchResult<TState>; } return result as DispatchResult<TState>; }
  select(id: string, ...args: unknown[]): unknown { const route = this.#selectors.get(id); if (!route) throw new Error(`unknown_selector:${id}`); return route.handler(...args); }
  runProcess(id: string, ...args: unknown[]): unknown { const route = this.#processes.get(id); if (!route) throw new Error(`unknown_process:${id}`); return route.handler(...args); }
  eventIds(): string[] { return [...this.#events.keys()]; } selectorIds(): string[] { return [...this.#selectors.keys()]; } processIds(): string[] { return [...this.#processes.keys()]; }
  hasEvent(id: string): boolean { return this.#events.has(id); } eventOwner(id: string): string | null { return this.#events.get(id)?.module.id ?? null; } selectorOwner(id: string): string | null { return this.#selectors.get(id)?.module.id ?? null; } stateOwner(path: string): string | null { return this.#stateOwners.get(path) ?? null; } getModule(id: string): NormalizedModule | null { return this.#modules.get(id) ?? null; }
  listModules() { return [...this.#modules.values()].map((module) => ({ id:module.id, version:module.version, dependencies:[...module.dependencies], eventIds:Object.keys(module.events), selectorIds:Object.keys(module.selectors), processIds:Object.keys(module.processes), stateAccess:{ owns:[...module.stateAccess.owns], reads:[...module.stateAccess.reads], writes:[...module.stateAccess.writes] } })); }
  #assertRoutes<T>(registry: Map<string, Route<T>>, routes: Record<string, T>, kind: string): void { for (const id of Object.keys(routes)) { const existing = registry.get(id); if (existing) throw new Error(`duplicate_${kind}:${id}:${existing.module.id}`); } }
  #registerRoutes<T>(registry: Map<string, Route<T>>, module: NormalizedModule, routes: Record<string, T>): void { for (const [id, handler] of Object.entries(routes)) registry.set(id, { module, handler }); }
}

function normalizeModule(definition: ModuleDefinition): NormalizedModule { if (!definition || typeof definition !== 'object') throw new TypeError('invalid_module'); const id = String(definition.id || '').trim(); const version = String(definition.version || '').trim(); if (!id) throw new TypeError('missing_module_id'); if (!version) throw new TypeError(`missing_module_version:${id}`); const dependencies = [...new Set((definition.dependencies ?? []).map(String).map((value) => value.trim()).filter(Boolean))]; return Object.freeze({ ...definition, id, version, dependencies, stateAccess:normalizeStateAccess(definition.stateAccess), events:normalizeRoutes(definition.events, id, 'event'), selectors:normalizeRoutes(definition.selectors, id, 'selector'), processes:normalizeRoutes(definition.processes, id, 'process'), migrations:definition.migrations ?? {} }); }
function normalizeStateAccess(access?: Partial<StateAccess>): StateAccess { return Object.freeze({ owns:normalizePaths(access?.owns), reads:normalizePaths(access?.reads), writes:normalizePaths(access?.writes) }); }
function normalizePaths(paths?: readonly string[]): readonly string[] { return [...new Set((paths ?? []).map(String).map((path) => path.trim()).filter(Boolean))]; }
function normalizeRoutes<T>(routes: Record<string,T> | undefined, moduleId: string, kind: string): Readonly<Record<string,T>> { if (routes == null) return {}; if (typeof routes !== 'object' || Array.isArray(routes)) throw new TypeError(`invalid_${kind}_routes:${moduleId}`); for (const [id, handler] of Object.entries(routes)) if (!id.trim() || typeof handler !== 'function') throw new TypeError(`invalid_${kind}_handler:${moduleId}:${id}`); return Object.freeze({ ...routes }); }
function validResult(result: unknown): result is DispatchResult { if (!result || typeof result !== 'object') return false; const candidate = result as Partial<DispatchResult>; return !!candidate.state && typeof candidate.state === 'object' && Array.isArray(candidate.log) && candidate.log.length > 0 && candidate.log.every((entry) => entry && typeof entry === 'object' && typeof entry.ok === 'boolean'); }
function unknownEvent<TState extends RuntimeRecord>(state:TState,event:string):DispatchResult<TState>{return{state,log:[{ok:false,event,reason:'unknown_event',detail:`Unknown event id: ${event}`}]} as DispatchResult<TState>;}
function moduleFailure<TState extends RuntimeRecord>(state:TState,event:string,reason:string,detail?:string):DispatchResult<TState>{return{state,log:[{ok:false,event,reason,...(detail?{detail}:{})}]} as DispatchResult<TState>;}
